### ISSUE TITLE
fis watch 跟livereload的bug--第一次不能livereload

### ISSUE THREAD

**Issue by looping84** [fex-team/fis#115]
重现步骤如下
- fis server start
- fis release -wL
  
  结果：修改代码的时候，不能自动刷新。

经测试：
start后，手动刷新一下，后续才可以livereload

**Comment by Softor** [comment]
@looping84 ,通过 -L 发布后，fis 会在你的页面里注入一个 js 文件。
刷新后，才能使新注入的文件载入到浏览器。
