### ISSUE TITLE
fis start的时候提示java not support!

### ISSUE THREAD

**Issue by webbill** [fex-team/fis#172]
sudo fis server start
执行这个之后，提示
checking java support : java not support!To start the node server willstarting fis-server .. at port [8080]

 [NOTIC] start npm install
npm WARN package.json fis-quickstart-demo@0.0.7 No README data

 [NOTIC] browse http://127.0.0.1:8080/

但执行java -version提示
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

我系统是mac os 10.10，请问如何解决呢？谢谢

**Comment by shenxiaolong** [comment]
@xiangshouding 安装完你给的版本，问题解决了。十分感谢！
