### ISSUE TITLE
“fis-server fails to start at port：8080” 是为什么

### ISSUE THREAD

**Issue by nancy-Gao** [fex-team/fis#174]
![image](https://cloud.githubusercontent.com/assets/4142296/4839024/53d9bf6c-5ff7-11e4-8790-a9937c0b1369.png)

**Comment by whvision** [comment]
fis-server fails to start at port [8080], error: org.eclipse.jetty.webapp.WebAppContext  这个错误是为什么

![image](https://user-images.githubusercontent.com/12840945/34081134-dd43d9aa-e383-11e7-8faf-ee657f203328.png)

**Comment by xiangshouding** [comment]
@whvision Java 9 现在还没有适配
