### ISSUE TITLE
我想问下less编译依赖的文件能不能在fis里面配置，不需要在每个less文件里面写import?

### ISSUE THREAD

**Issue by lilJay-lin** [fex-team/fis#231]
<p>写less的时候需要导入一些基础less文件，如果在每一个less文件里面都加个import显的有点繁琐，</p>

<p>请问下fis可不可以配置这种依赖，编译的时候自动引入依赖文件这样写less的时候不用每次都手动</p><p>写import,在官方文档没有找到答案</p>

**Comment by leeyeh** [comment]
https://github.com/leeyeh/fis-parser-less-import
