### ISSUE TITLE
fis release 非常的慢 这是什么原因导致的

### ISSUE THREAD

**Issue by liupeng110112** [fex-team/fis#232]
![image](https://cloud.githubusercontent.com/assets/2655916/5276457/b3c75210-7af3-11e4-810e-ffacb20eef75.png)
我想对这个目录结构下js做压缩和md5 ,但是这个过程非常的长久，这个是为什么？

**Comment by CaroseKYS** [comment]
@fouber 龙哥，fis在watch模式的时候，如果修改一个文件，会引起一大堆无关文件的编译，导致更新到目标目录的速度非常慢，这个有好的方式解决吗？
