### ISSUE TITLE
npm ERR! git clone https://github.com/pipobscure/fsevents undefined

### ISSUE THREAD

**Issue by digdeep126** [fex-team/fis#274]
C:\nodejs>npm install -g fis
npm ERR! git clone https://github.com/pipobscure/fsevents undefined
npm ERR! git clone https://github.com/pipobscure/fsevents undefined
npm WARN optional dep failed, continuing fsevents@git+https://github.com/pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c6
npm WARN optional dep failed, continuing fsevents@0.3.1
D:\NodeLearn\node-global\fis -> D:\NodeLearn\node-global\node_modules\fis\bin\fis
fis@1.8.13 D:\NodeLearn\node-global\node_modules\fis
├── fis-postprocessor-jswrapper@0.0.8
├── fis-command-install@0.0.7
├── fis-packager-map@0.0.9
├── fis-deploy-default@0.0.2
├── colors@0.6.2
├── commander@1.3.2 (keypress@0.1.0)
├── fis-optimizer-clean-css@0.0.9 (clean-css@1.1.7)
├── fis-optimizer-uglify-js@0.1.6 (uglify-js@2.4.15)
├── fis-command-release@0.11.3 (async@0.9.0, chokidar@0.8.4, livereload-server-spec@0.2.3)
├── fis-command-server@0.7.1 (step@0.0.5, chokidar@0.10.5)
├── fis-kernel@2.0.12 (iconv-lite@0.2.10, tar@0.1.17)
├── fis-spriter-csssprites@0.2.5 (node-images@1.5.5)
└── fis-optimizer-png-compressor@0.0.6 (node-pngquant-native@0.0.11, node-pngcrush@0.1.1)

C:\nodejs>

**Comment by digdeep126** [comment]
npm install -g fis 报错了，但是好像最终又安装成功了。

**Comment by hefangshi** [comment]
```
npm WARN optional dep failed, continuing 
```

只是一个可选依赖异常，可以忽略，NPM把这个警告弄的太吓人了
