### ISSUE TITLE
Does fis support jsp project? why "permission denied" throw?

### ISSUE THREAD

**Issue by iFrankWu** [fex-team/fis#277]
When I use below command run fis, an "permission denied" error throw out, that project is JSP project. so I have a question, does fis support jsp project? and why "permission denied" throw?
fis release --optimize --md5 --pack -r /home/tomcat/360weixin -d /home/tomcat/fis-quickstart-demo/360weixin --verbose
 [DEBUG] 19:18:47.0044 cache is valid

 [DEBUG] 19:18:47.0044 revert cache finished

 [DEBUG] 19:18:47.0044 compile [/home/tomcat/360weixin/wx/myservice/register.jsp] end

 [DEBUG] 19:18:47.0048 [packager.map] start

 [DEBUG] 19:18:47.0052 [packager.map] end

 [DEBUG] 19:18:47.0068 [spriter.csssprites] start

 [DEBUG] 19:18:47.0288 [spriter.csssprites] end

 [DEBUG] 19:18:47.0295 [postpackager.simple] start

 [DEBUG] 19:18:47.0339 [postpackager.simple] end
2036ms

 [ERROR] EACCES, permission denied '/home/tomcat/fis-quickstart-demo/360weixin/skin'

/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-command-release/release.js:161
                throw e;
                      ^
Error: EACCES, permission denied '/home/tomcat/fis-quickstart-demo/360weixin/skin'
    at Object.fs.mkdirSync (fs.js:653:18)
    at /home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:352:16
    at Array.reduce (native)
    at Function._.mkdir (/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:350:21)
    at Function._.write (/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-kernel/lib/util.js:457:11)
    at deliver (/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-deploy-default/index.js:42:14)
    at module.exports (/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-deploy-default/index.js:83:9)
    at /home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:121:17
    at prepareDeploy (/home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:91:21)
    at /home/tomcat/nodejs/lib/node_modules/fis/node_modules/fis-command-release/lib/deploy.js:120:13

**Comment by fouber** [comment]
@iFrankWu 

支持，但是你的项目，这个目录没有文件创建的权限，所以报错了，设置一下权限就好了

**Comment by iFrankWu** [comment]
Thanks a lot, I tried this, but still fail.  But I change the source root dictionary to my Project source code, it's works well.  
Thanks again.

**Comment by fouber** [comment]
@iFrankWu 

```bash
chmod -R 755 /home/tomcat/fis-quickstart-demo/360weixin
```
