### ISSUE TITLE
关于fis的logo……

### ISSUE THREAD

**Issue by Lomyal** [fex-team/fis#279]
fis的这个logo让我想到了：

![201212202048488080](https://cloud.githubusercontent.com/assets/7030676/5701477/cf28781a-9a86-11e4-8152-7b6f7878beda.jpg)

:)

**Comment by xiangshouding** [comment]
。。。

**Comment by 2betop** [comment]
。。。。

**Comment by fouber** [comment]
....

**Comment by jsonxu** [comment]
人才

**Comment by simechiang** [comment]
。。。
