### ISSUE TITLE
有什么可以提高构建速度的良方?

### ISSUE THREAD

**Issue by atomicmm** [fex-team/fis#280]
辛苦研究了几天,终于初步掌握了fis的构建,现在剩下最后一个问题了,请同学们解答

我的部署脚本为
```javascript
fis release -opwL --dest local_deploy //发布到本地的php部署服务上
```
主要进行的操作有:
```javascript
    //pack
    'static/js/app.js': [
        '/src/app/**.js'//
    ],
    'static/js/lib.js': ['angularxxx'],
    'static/css/app.css': [
        '/src/components/**.css',
        '/src/app/**.css'
    ],
//替换内联
        path: [{
            //项目入口
            reg: '/src/index.html',
            release: '/index.html'
        }, {
            reg: /^\/src\/app\/(.*\.tpl.html$)/i,//src/app下的模板文件,输出到/template下,以app为根
            release: '/template/$1'
        }]
```

这样每次一保存,连分析,发布,合并的时间在我的本本(`I5 8G`)上,一次得花`8s`左右才能完成,经常刷新的速度跟不上写代码的速度,这个liveload还时不时会崩溃...略坑爹

有什么办法或者建议可以提高这个编译发布的速度么?

**Comment by xiangshouding** [comment]
- 升级最近版本fis试试，因为livereload这块我做了一次优化，还没有人尝鲜，你可以试试
- 是否是第三方库不必要文件太多了，可以exclude掉
- 其实开发时不需要做`-o`压缩的，等上线回归测试时再打开此选项；关闭压缩足够速度提升很多了。
- 拆分项目

**Comment by fouber** [comment]
@atomicmm 

https://github.com/fex-team/fis/issues/269#issuecomment-69451936

**Comment by atomicmm** [comment]
@fouber 有否可能有maven哪种机制,有一个完整的分模块构建的解决方案?fis-conf可以定义当前模块需要先构建那些模块,然后只watch当前的模块...

**Comment by hefangshi** [comment]
建议开发的时候不要进行o和p操作，这样可以加快不少编译速度，开发期本来就不需要做这些处理吧。

**Comment by atomicmm** [comment]
最终打了个擦边球,每个子模块自己有自己的fis-conf
个人先把大工程中的自己部分排除掉
然后再构建自己的小模块
略麻烦,但总能先用着了
结贴
