### ISSUE TITLE
提一个关于background  color sprite 的BUG

### ISSUE THREAD

**Issue by jsonxu** [fex-team/fis#281]
background: #ffffff url("/app_img/im/v1/em/all.jpg?__sprite") 10px 10px no-repeat;
这样编译后，FIS把背景颜色搞丢了，也就是backround-color:#ffffff 不会被编译出来

**Comment by xiangshouding** [comment]
@jsonxu 嗯，好；我看看，不过你先规避吧。我没有用类似词法分析类的东西，只是写正则搞定的，可能确实有一些小纰漏；

**Comment by jsonxu** [comment]
恩，好的。我现在把背景图片和背景颜色单独分开写就没问题了。
