### ISSUE TITLE
js如何禁用try/catch

### ISSUE THREAD

**Issue by felixyale** [fex-team/fis#282]
fis 1.9版本会在javascript文件自动加上

!function(){try{

//自己的代码

}catch(e){}}();

try/catch，全局变量都不能写了，求问怎么禁用，谢谢

**Comment by 2betop** [comment]
是所有的 js 还是 部分？ fis 默认配置了 components 目录下面的才会包。

**Comment by felixyale** [comment]
是所有的js，
我现在临时的解决方案是

	modules: {
		postprocessor: {
			'js': null
		}
	}

**Comment by 2betop** [comment]
1.9 引入了组件生态功能，引入了以下规则。


```js
{
     reg: 'components/**/*.js',
     isMod: true
}
```

**Comment by 2betop** [comment]
已去掉这个规则，请升级 fis

**Comment by felixyale** [comment]
@2betop 嗯，收到了，谢谢
