### ISSUE TITLE
关于fis-kernel中的OO处理疑惑的问题

### ISSUE THREAD

**Issue by chenming142** [fex-team/fis#283]
在fis-kernel.js的OO实现代码中的derive方法，应该主要是为了实现 oo的继承与多重继承
![qq 20150114100945](https://cloud.githubusercontent.com/assets/653458/5732912/6ad51c60-9bd5-11e4-8689-4dbc94395b0c.jpg)

可是在我的测试中，
![qq 20150114101119](https://cloud.githubusercontent.com/assets/653458/5732962/3e9a3ba2-9bd6-11e4-861d-ecc68abf7d71.png)

那么问题有
1）我这么测试是正确的嘛？？
2）如果是，第一张图的代码 38行的作用是什么 ？
3）导致出现这个问题的原因是什么？

**Comment by hefangshi** [comment]
这里是没有问题的，实际上不存在你说的B这个继承，B在整个继承过程中只是用来提供C的构造函数的。

所以实际上是这样的

```javascript
function A(){
    this.a = 'a';
}

var C = A.derive(function(){
    this.a = 'b';
});

var a = new A();
var c = new C();

console.log('a.a', a.a);
console.log('c.a', c.a);
console.log('a instanceof A', a instanceof A);
console.log('c instanceof C', c instanceof C);
console.log('a instanceof C', a instanceof C);
console.log('c instanceof A', c instanceof A);
```

```
a.a a
c.a b
a instanceof A true
c instanceof C true
a instanceof C false
c instanceof A true
```

**Comment by chenming142** [comment]
如果是这样的话，我能不能理解，并未“完全的实现多重继承”?		

或者，这么说，对于多重继承，只实现了拷贝属性与原型属性?
> 2）如果是，第一张图的代码 38行的作用是什么？
   
到底该如何解释呢？

**Comment by hefangshi** [comment]
"完全的实现多重继承"不知道是引用自哪里，FIS的继承从来都不是多重继承，多重继承是指一个子类可以同时拥有多个父类的行为，和继承链是没有关系的，Javascript中需要使用多重继承的案例也很少，FIS中也不需要这样的能力。

38行的代码作用类似场景的原型继承

```javascript
function A(){
}

function B(){
}

B.prototype = new A();

B.prototype.constructor = B
```

中 `B.prototype.constructor = B` 的功能

**Comment by chenming142** [comment]
OK,那我知道了，有关“多重继承”的问题，可能是我理解有误。
> 实际上不存在你说的B这个继承，B在整个继承过程中只是用来提供C的构造函数的。

嗯，这句话就是当初设计的初衷么？

**Comment by hefangshi** [comment]
这个和设计初衷也没什么关系，应该说此处只是一个构建一个子类的参数，和类这个概念是没有什么关系的。

**Comment by xiangshouding** [comment]
:100: 已阅

**Comment by fouber** [comment]
38行确实没用，之前有人跟我吐槽过，后来忘记修改了。。。

fis中的oo使用场景很少，主要是几个类的定义，从Object派生过来，我个人喜欢在js中使用“派生”语义，而不是“继承”，觉得js更适合用“派生”方式创建新类

**Comment by xiangshouding** [comment]
嗯，那就改一下；
