### ISSUE TITLE
项目不是根据相对路径引用静态静态资源，怎么处理

### ISSUE THREAD

**Issue by aimpsmile** [fex-team/fis#287]
利用框架的模板常量 
例如：
      <script type="text/javascript" src="__js__/a.js"></script>
类似于这种情况。fis可以先把这个常量替换了，然后在找路径吗？
或者那个域名的替换，能不能把字符串替换成路径啊，求解答。

**Comment by xiangshouding** [comment]
- fis是静态编译，实在不知道你的哪部分是常量
- 常量从某些角度考虑违背了前后端分离的设计意图
- 你这个常量非得如此做，可以根据`roadmap.domain`来处理，由`roadmap.domain`来负责你的所谓常量的作用。

**Comment by aimpsmile** [comment]
首先谢谢你的答复
现在是这样的：
<script type="text/javascript" src="__js__/home_card.js"></script>
我想在release 的时候可以找到相对应的路径。但是不知道FIS支不支持，可不可以配置一下。
如果改成相对的路径的话，就要对项目做大的改动，我们小公司，可没有你们那么多的人力、精力。如果不支持的话，就没办法用了。用不起。
