### ISSUE TITLE
widget 只适用于fisp？

### ISSUE THREAD

**Issue by xuhuan** [fex-team/fis#297]
如题，看fis的文档没有widget相关的文档，fisp文档里有相关的。

**Comment by xiangshouding** [comment]
嗯，是的。

**Comment by 2betop** [comment]
jello 和 yog 也有啊！

**Comment by xuhuan** [comment]
@xiangshouding 能否扩展到一般的普通项目也能用，比如纯静态页面项目。

**Comment by xiangshouding** [comment]
@xuhuan 可提PR

**Comment by hefangshi** [comment]
@xuhuan 纯静态页可以组合使用autoload，然后利用fis中html的inline功能来加载widget，用autoload来加载widget依赖的资源

可以参考下https://github.com/fex-team/fis-pure

**Comment by xuhuan** [comment]
@hefangshi 希望能有个一致的开发体验，而不是每种类型要一种方式，学习成本提高不少。
一致的话组件能通用起来。

**Comment by 2betop** [comment]
理想很美好，现实很残酷！每一种语言都有一定模版限制

**Comment by xiangshouding** [comment]
@xuhuan 我相信一个技术团队，选择技术方案在一定时期内是固定的，除非换个团队。另外，确实可能现在FIS以及FIS的诸多解决方案确实给你带来了一些困惑。这块我们会努力把她做得更好的~
