### ISSUE TITLE
js中使用__uri定位json文件，同时配置的domain， 域名配置会无效

### ISSUE THREAD

**Issue by yqfang** [fex-team/fis#302]
js中代码
<code>
      url:  __uri('../../resources/mocks/dao/getResult.json')
</code>
fis-conf中json格式文件的domain代码
<code>
fis.config.merge({
    roadmap : {
        domain : {
            '**.json': 'webRoot'
        }
    }
});
</code>
编译后生成的js文件中url:并没有出现我预期的webRoot域名前缀,请问是什么原因？

**Comment by xiangshouding** [comment]
`json`不在`useDomain`行列

```
fis.config.set('roadmap.path', [{
    reg: '**.json',
    useDomain: true
}]);
```
后

`fis release -D....`
