### ISSUE TITLE
jsp中引用js的url和js文件的实际路径不一致，这时候fis如何将二者关联起来

### ISSUE THREAD

**Issue by comcaptain** [fex-team/fis#304]
经过试验，发现FIS的roadmap等配置基于一个前提：源“类html文件”中的js url和js文件的实际路径必须一致。e.g. 在jsp中有`<script src="../test.js"></script>`，则test.js必须在jsp文件的上级目录，不然fis就无法将二者关联起来。

我想在我们既存的系统上引入fis，但jsp中用的js url和js的实际位置并不一致，e.g. 
文件路径如下：
`webRoot/test/jsp/test.jsp`
`webRoot/test/js/test.js`
test.js相对于test.jsp的相对路径是`../js/test.js`，或者绝对路径是/test/js/test.js，但是实际的
jsp中是`<script src="./test/js/test.js"></script>`(因为这个jsp在struts的action中对应的url是根路径)。

这种情况下fis有对应的处理方法吗，比如加个预处理，将jsp中所有的js路径前面的`.`去掉

Thanks in advance.

**Comment by comcaptain** [comment]
new title, make my question more clear

**Comment by 2betop** [comment]
没有这样的限制，你写路径的时候都直接写项目中相对目录，或者 在项目中的绝对路径。

fis 编译后，会全部换成绝对路径。至于为何要换成绝对路径，请查看 https://github.com/fex-team/fis/issues/86

**Comment by comcaptain** [comment]
感谢回复。
请问你回复中写的`"写路径的时候"`是指在配置roadmap的时候吗，对roadmap配置我做了如下尝试：
读了[官方文档](http://fis.baidu.com/docs/advance/roadmap.html)后发现应该用reg和url属性来达到我的需求，以下引用自[官方文档](http://fis.baidu.com/docs/advance/roadmap.html)
> reg： 他用于指定这条规则适用的文件路径
> url： 资源引用路径

因此我的fis-conf.js配置如下：
>fis.config.set('roadmap.path', [{
>  reg: '/test/js/test.js',
>  url: './test/js/test.js'
>}]);

在webRoot/test/jsp/test.jsp文件中有如下资源引用：
`<script src="./test/js/test.js"></script>`

test.js的实际文件路径是`webRoot/test/js/test.js`
之后在webRoot文件路径下执行`fis release --optimize --md5`，结果生成的test.jsp中依然是`<script src="./test/js/test.js"></script>`


我想可能是我配置的有问题，所以我修改jsp中的js引用，让引用的url路径和js的实际路径一致，即：
`<script src="/test/js/test.js"></script>`
此时我再次执行`fis release --optimize --md5`，结果fis成功将这处引用和js文件关联起来了，生成的jsp中变成：
`<script src="./test/js/test_61f4eb2.js"></script>`
由此可知，我原来的配置没有问题，从而可以验证以前的猜测：fis在默认配置下，碰到这种情况：“jsp中引用js的url(e.g. `./test/js/test.js`)和实际js的文件路径(e.g. `/test/js/test.js`)不一致”，就不能正确的关联jsp中的js引用和js文件。

请问，在这种情况下，如果我不修改jsp文件，fis可不可以通过某种配置应对这种情况呢
（不太理解你回复中说的方法，所以就凭自己的猜测做了些尝试，如果我理解错了敬请原谅）

**Comment by comcaptain** [comment]
这里有人吗。。。。。

**Comment by 2betop** [comment]
> `<script src="/test/js/test.js"></script>`
  此时我再次执行`fis release --optimize --md5`，结果fis成功将这处引用和js文件关联起来了，生成的jsp变成：
    `<script src="./test/js/test_61f4eb2.js"></script>`

你确定是变成  `<script src="./test/js/test_61f4eb2.js"></script>` 而不是  `<script src="/test/js/test_61f4eb2.js"></script>`

fis 里面写路径，都是编译前的路径，关于路径有两种写法：

1. `/` 反斜线开头的，绝对路径。文件查找从项目跟目录开始，即你的 webRoot
2. 不以 `/` 反斜线开头的都是相对路径，都是相对与当前文件的。

那么，如果你在  `webRoot/test/jsp/test.jsp` 写的路径是 `./test/jsp/test.js` 那么，实际上你引入的是 `webRoot/test/jsp/test/jsp/test.js`，如果你要引用  `webRoot/test/jsp/test.js` 应该直接就写 `./test.js` 或者 '/test/jsp/test.js'

**Comment by comcaptain** [comment]
不好意思第一个是笔误，应该是变成`<script src="/test/js/test_61f4eb2.js"></script>`

为什么在jsp中写./test/jsp/test.js而不是/test/jsp/test.js，在最开始的问题里我就说过：
>  jsp中是`<script src="./test/js/test.js"></script>`(因为这个jsp在struts的action中对应的url是根路径)。


我问的问题是在不修改jsp的情况下fis是否能够实现这个，然后你告诉我可以，现在你的意思是其实不可以吗

**Comment by 2betop** [comment]
你是想要产出的路径变成 `<script src="./test/js/test_61f4eb2.js"></script>`  而不是 `<script src="/test/js/test_61f4eb2.js"></script>` ? 

你确定 struts 不支持  `<script src="/test/js/test_61f4eb2.js"></script>` 这种路径吗？

如果实在不行，你配置 domain 配置，可以实现你的需求。

```javascript
fis.config.set('roadmap.domain', '.');
```

然后 fis release 的时候加上 --domain 选项。

**Comment by comcaptain** [comment]
我问的是不修改的前提下，我什么时候说过struts不支持

**Comment by 2betop** [comment]
那如果能支持，你为何不批量改一下路径？我以为你是必须要保证产出后是那种写法才能正常工作。

**Comment by 2betop** [comment]
你这是想吧fis 中默认的相对路径改成绝对路径的路径的逻辑，当然不支持啊。

**Comment by xiangshouding** [comment]
- 首先，可能文档说的不够明白
- 其次，FIS 要求必须写源码路径，编译产出的结果才是需要上到线上的代码
- 再次，迁移 FIS 是有成本的
- 再再次，聊技术心态平和一点

**Comment by comcaptain** [comment]
心态不平和的原因是: 第一次回答没有仔细看我问题就草率的给了一个含糊其辞的答案，第三次回答依旧如此。你可以不回答，框架是免费的，你没有义务回答我的问题，但请不要草率地给一个误导性的答案。


fis是个很不错的框架，但是太重了些，我已经转进gulp.自己写了个gulp插件实现了我的需求

**Comment by xiangshouding** [comment]
@comcaptain 适合自己的就是最好的

**Comment by fouber** [comment]
@comcaptain 

fis在设计的时候就是严格的遵守 “**开发中使用工程路径，发布后替换为部署路径**” 的原则，所以如果开发中没有使用工程路径，而是基于部署规范去写源码中的资源路径，这是fis不推荐的做法。

按照工程路径写源码的规范可以让路径处理变得统一，而且不会产生二义性；与此同时，组件也具备了可移植性，将来需要目录结构调整都是没有任何影响的。

fis面向项目的工程化管理，经过反复实践和总结的结果，以目前的情况来看，在不修改jsp源码的前提下，你的需求 **确实不能被roadmap直接配置出来（当然，写插件预处理是可以的）** ，因为这种做法会导致路径识别的混乱，“写代码还要时刻关心部署和server的router配置关系”这种开发体验是fis所不提倡的，后面你用gulp实现fis的功能的过程中可能会慢慢体会到为什么fis要这么设计。

**Comment by comcaptain** [comment]
有类似需求的可以参考我的[gulp实现](https://github.com/comcaptain/gulp-based-front-end-preprocessor)，为了解决实际路径和引用路径不一致的问题，在配置中加了两个function：convertRelativePathToReferenceUrl和convertReferenceUrlToRelativePath
