### ISSUE TITLE
关于fis的的输出目录。

### ISSUE THREAD

**Issue by fengyuxiang1201** [fex-team/fis#316]
q1:使用 fis release -d deploy 怎么把fis-conf.js 和 此文件父目录,传到服务器端。
q2:使用 fis release -d deploy 时候会把文件发布到www目录下，这个怎么去自定义。

q1中fis-conf.js文件位置不能修改。
q2中不能改变webserver的 rootDirectory

**Comment by fouber** [comment]
举一个具体的例子呢
