### ISSUE TITLE
求解，如何debug ，THX!

### ISSUE THREAD

**Issue by csulyl** [fex-team/fis#322]
fis  release -p  时，我想debug fis.js  或者其他的代码  ，我通过  node-inspector 调试,没玩起来,醉了

**Comment by xiangshouding** [comment]
- `-w` 后用 node-inspector
- `console.log`
- `require('fis')`

**Comment by 2betop** [comment]
Node --debug --debug-brk $(which fis) release

**Comment by csulyl** [comment]
666
