### ISSUE TITLE
部署配置中POST文件到服务器的问题

### ISSUE THREAD

**Issue by hxqbeyond** [fex-team/fis#328]
问题一：
使用部署配置（deploy）中的receiver可以在编译后把文件上传到服务器，但这样有一个问题，假如目录里面的文件越来越多的话会导致上传占用过多时间。
是否有配置项可以让每次编译后只上传有改动的文件。
问题二：
前端模块化，假如我在一个a.js文件中require了b.js，现在b.js做了修改，如何在编译的时候修改a.js中b.js的时间戳。

**Comment by hefangshi** [comment]
## 问题一

使用fis release -d remote -w后，会开启文件监听模式，在这个模式下，检测到有文件修改后，会自动编译，并增量上传

## 问题二

如果使用的是mod.js，我们并不是根据a.js中的b.js的名称来获取b.js的地址的，举例来说

```
// a.js
require('b.js')
```

在获取b.js的真实路径的时候，我们会查询map.json表，其内容是ID到URL资源的映射，例如

```
{
    "b.js": "http://www.blahblah.com/b.js?t=2014"
}
```

我们会根据获得的URL路径再进行请求。而map.json中的路径的修改，可以参考roadmap.path配置。不过相比时间戳，更建议使用MD5，详细内容可以在官方文档和issue里面查看。

**Comment by hxqbeyond** [comment]
多谢回答哈，另外在麻烦一下您
问题二：
因为某些原因，我们没用mod.js并且也没有用md5做增量发布，还是那个问题，有没其他方法可以在js中监控到哪些文件是修改过的则自动更新时间戳。或者没实现这种方案的思路，多谢了。PS：对fis的api还不是很熟悉，看了云龙大神的前端开发体系建设日记后虽然熟悉了不少，不过很多语法还不懂。

**Comment by hefangshi** [comment]
如果是<script引用的也是支持的，但如果是时间戳的格式，目前不能根据修改自动更新时间戳，只能全量更新

https://github.com/fex-team/fis/issues/73

**Comment by hxqbeyond** [comment]
明白了，多谢了。
最后一个问题，比如我的文件是a.js，要增量压缩成a.min.js（每次压缩都覆盖这个文件），正则应该怎么写？
