### ISSUE TITLE
fis 如何对待非模块化的jquery插件

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#329]
需要手动修改插件代码，增加类似module.exports = jquery.fn.plugin之类的吗

**Comment by xiangshouding** [comment]
- jQuery 不做组件化处理，挂全局，这样所有的插件都可以挂全局了。
- jQuery 做组件化处理，那么这时候插件就需要改造一下了，先 `require('jquery')`，然后绑上插件，再`exports`出去。

**Comment by fancyboynet** [comment]
谢谢，建议是哪种呢？
