### ISSUE TITLE
fis log 怎么查看？

### ISSUE THREAD

**Issue by jameswhf** [fex-team/fis#333]
在开发FIS编译期的插件时，发现测试比较麻烦，必须要发布更新后才能测试。
从compile.js看，FIS应该打了很多log出来，但是没有找到，请问怎么查看log?
难道需要配置log选项，但是在配置API里也没有说明啊。谢谢指导！

**Comment by xiangshouding** [comment]
加命令行参数 `--verbose`

**Comment by jameswhf** [comment]
多谢~
为什么配置文档里没有提及呀？

**Comment by xiangshouding** [comment]
```
fis release -h
```
帮助信息里面有
