### ISSUE TITLE
如何release出“http://xxx.com/xxx/static”形式的资源

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#334]
本地开发release出的资源引用都是相对根目录的，类似"/static/xxx"，没有问题，现在要部署到正式环境中，资源引用必须是“http://xxx.com/xxx/"开头的，要怎么配置呢？
我试过fis.config.set('statics', 'http://xxx.com/xxx/static');输出的都变成
"/http_/xxx.com/xxx/static"

**Comment by hefangshi** [comment]
http://fis.baidu.com/docs/api/fis-conf.html#roadmapdomain
