### ISSUE TITLE
请问__sprite可以指定哪些图片合并在一张图吗

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#336]
默认是把当前页面中的所有__sprite图合并在一起？这样多个页面会不会造成重复的图片，可以共用图片吗，特别像icon这种可以归类的图片

**Comment by hefangshi** [comment]
目前并不能，目前图片的合并是以CSS文件为单位的。

**Comment by xiangshouding** [comment]
为了使 `csssprite` 足够通用，而且足够简单，所以针对每一个css来做图片合并的。如果想实现某些图片进行合并，可以考虑将其写到某一个 css 里面来实现。

**Comment by fancyboynet** [comment]
csssprite是在css合并之前吗，因为上线后多个css文件是合并在一起的，如果这时候再合并图片是不是就会集合在一起了？

**Comment by xiangshouding** [comment]
在合并之后做的，而且对合并的文件默认开启 spriter 处理的，只需要加 query `__sprite`，而不需其他操作，大概酱紫。

**Comment by fancyboynet** [comment]
合并之后再sprite，那是不是就会有刚开始的疑问了，会出现图片被重复合并的问题了？

**Comment by xiangshouding** [comment]
同一个 CSS 文件里面使用的图片，如果路径相同会去重。

**Comment by fancyboynet** [comment]
不是，可能我没表述清楚，我是意思是我有A,B两个页面，上线后分别引用A.css跟B.css，其中A跟B都会引用相同的icon，按现在相当于会产生两张sprite,A.png跟B.png，那这两张集成的图中都会包含那些共同的icon吧
我的本意是想A跟B页面都引用一张icon集合图，这样可以共用icon
不过你们这样设计从单个页面的优化来说是合理的，不知道是不是有考虑过这类问题，所以最终是按现在的合并思路来
