### ISSUE TITLE
uri运行时动态定位某一个资源时值是空

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis#338]
代码如下：
                &lt;img src="{%uri name="home:static/index/img/2.png"%}" class="vertical-align-bottom" width="350" height="200" /&gt;
页面输出：
&lt;img src="" class="vertical-align-bottom" width="350" height="200"&gt;

编译是正常的，没有报错，求帮看看

**Comment by xiangshouding** [comment]
图片不入表，也就是图片的 `useMap: false`，所以你拿是拿不到的。

**Comment by trainGitHub** [comment]
多谢回复，那有什么解决办法吗， 把useMap: true ?

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis/wiki/%E9%85%8D%E7%BD%AEAPI#roadmapdomain

**Comment by xiangshouding** [comment]
```javascript
fis.config.get('roadmap.path').unshift({
    reg: 'xxxx',
    useMap: true,
    release: 'xxxxxxxxxx'
});
```
