### ISSUE TITLE
前后端都一个人做，后端是PHP，不用Smarty，该怎么使用FIS？

### ISSUE THREAD

**Issue by cos800** [fex-team/fis#339]
我的情况是这样的：
前端后端都是我一个人在做，后端是PHP，
但我不用 Smarty 模板引擎，不用任何模板引擎，有 MVC 分离，我是直接 `include` 模板文件， 在模板中 `<?=$title?>`
然后开发时 都是前端和后台同时开发。

现在前端想用 FIS（FIS-PLUS 恐怕用不上）
想问下有没有类似情况的，你的项目结构是怎么安排的？

**Comment by cos800** [comment]
我打算 直接把模板变量 `<?=$title?>` 直接在 FIS项目 中写，然后输出到 PHP项目 的模板目录里。

**Comment by xiangshouding** [comment]
如果直接是 php 项目，可以参考 https://github.com/fouber/phiz 的实现。

**Comment by cos800** [comment]
有没有办法把 PHP文件 也放在 FIS 项目 里，然后输出时 把 PHP 文件也跟着输出？

**Comment by xiangshouding** [comment]
当然，可以，不过首先你得定制适合你项目的**目录规范**

**Comment by cos800** [comment]
phiz 就写了几个类，看不懂是什么意思。

**Comment by cos800** [comment]
目录规范 怎么定制？

**Comment by cos800** [comment]
目录规划 指的就是 roadmap.path 配置吧？
我想我应该知道怎么做了，谢谢~

**Comment by xiangshouding** [comment]
#393
