### ISSUE TITLE
关于md5戳的问题

### ISSUE THREAD

**Issue by carriey** [fex-team/fis#346]
a.min_a4bbf66.js内容发生变化以后，生成了新的md5戳a.min_8dbb11c.js这两个文件会并列存在，有没有什么配置方法可以只保留最新的一个文件。
![image](https://cloud.githubusercontent.com/assets/10162033/6364603/b78472e8-bce3-11e4-95ac-8a917f698541.png)

**Comment by fouber** [comment]
@carriey 

release到一个新的目录中

**Comment by carriey** [comment]
谢谢fouber  @fouber
