### ISSUE TITLE
运行fis server start --type node 报错，求解决

### ISSUE THREAD

**Issue by ayu2012** [fex-team/fis#348]
运行fis server start --type node 报错
[ERROR] Cannot find module 'express'
求高手解决，我运行express version 又没有问题

**Comment by xiangshouding** [comment]
fis server clean后重试

**Comment by ayu2012** [comment]
非常感谢 OK了 发自网易邮箱大师
            在2015年02月26日 11:08，fansekey 写道:fis server clean后重试
