### ISSUE TITLE
[FAQ]执行MD5戳后报错，求大牛解决

### ISSUE THREAD

**Issue by ayu2012** [fex-team/fis#350]
运行 fis release --optimize --md5之后，
报错如下：
[WARNI] missing config file [fis-conf.js]
求高手解决，非常感谢

**Comment by fouber** [comment]
@ayu2012 

执行fis release命令的目录没有 ``fis-conf.js`` 文件，你确定这是一个fis项目么？

**Comment by ayu2012** [comment]
ok了 问题得到解决
