### ISSUE TITLE
图片合并不成功呢，求解决

### ISSUE THREAD

**Issue by ayu2012** [fex-team/fis#352]
压缩 和MD5戳都可以，事例用的官方的事例，但是就是不成功，求高手解决

**Comment by fouber** [comment]
* fis release的时候没有加 ``-p`` 参数
* css中图片没有加 ``?__sprite``` 参数
* 图片路径不正确

也就这些可能了，逐一检查一下看看

**Comment by ayu2012** [comment]
用的官方事例，检查了 都是正确的

**Comment by trainGitHub** [comment]
请教 @fouber 图片用的是相对路径是不是不行？

**Comment by ayu2012** [comment]
自己解决了，本地弄了2哥fis-quickstart-demo目录，修改fis-conf.js这个文件的时候，修改错了，采用vi fis-conf.js的时候才发现，操作的文件的不对！

**Comment by fouber** [comment]
@trainGitHub 

可以
