### ISSUE TITLE
编译路径问题少了命名空间

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis#353]
命名空间home目录下的widget路径如下
home/widget/bread/bread.scss
正常请求的地址应该是这个
http://127.0.0.1:8080/static/home/widget/bread/bread.css

但是fis-conf.js加了图片合并的配置后请求的地址就少了命名空间，地址如下
http://127.0.0.1:8080/widget/bread/bread.css

这是 fis-conf.js 加的图片合并的配置
```javascript
fis.config.get('roadmap.path').unshift({
    reg: '**.scss',
    useSprite: true
});
fis.config.set('settings.spriter.csssprites.margin', 10);
```
请教这是什么问题？编译没报错，但是这个文件没有编译成功

**Comment by xiangshouding** [comment]
1. 先说问题，你的规则覆盖了已有的规则，那么就需要配置 `release`（产出路径）

    ```javascript
    fis.config.get('roadmap.path').unshift({
      reg: '**.scss',
      useSprite: true,
      release: '/static/${namespace}/$&'
    });
    ```
2. 再说`useSprite`，FIS 默认会对打包的 css （类css文件）进行图片合并处理，这样就不需要给每一个 css 文件配置 Sprite 处理了，除非有特殊需求。

**Comment by trainGitHub** [comment]
嗯，懂了，多谢。我在哪可以看到默认的配置吗？
