### ISSUE TITLE
有一个将css文件包装成js并改名的需求请问应该如何实现？

### ISSUE THREAD

**Issue by Gerhut** [fex-team/fis#358]
功能类似于 [hefangshi/fis-prepackager-csswrapper](https://github.com/hefangshi/fis-prepackager-csswrapper)

但是有额外的要求就是扩展名改成 `.css.js`

如果放到 prepackager 阶段的话，因为 map.json 的 res 项是在 package 之前生成，会导致 map.json 中的文件名对不上，如果放到 postprocessor 的话无法 optimise css 。

请问用什么方法可以实现该需求？

谢谢

**Comment by fouber** [comment]
@Gerhut 

https://github.com/scrat-team/scrat/blob/master/plugins/prepackager/framework-conf.js#L155-L168

基于fis设计的scrat又这个功能，是在prepackager中实现的，有问题可以在这里继续提问
