### ISSUE TITLE
 fis release -p 的时候提示 csssprites does not support your node v0.10.30

### ISSUE THREAD

**Issue by baihuibo** [fex-team/fis#360]
![qq 20150302103726](https://cloud.githubusercontent.com/assets/5130197/6434667/3dfb2c8a-c0c8-11e4-9dce-9cedc5cd1720.png)

**Comment by xiangshouding** [comment]
重新安装 FIS 试试。

**Comment by xiangshouding** [comment]
发布新版已经支持 0.12.0 重装即可。
