### ISSUE TITLE
手机页面 css有设置background-size的时候进行 csssprite 要怎么处理

### ISSUE THREAD

**Issue by linjingming** [fex-team/fis#363]
源码 css中设置background: url(../images/icon_close.png?__sprite) no-repeat;background-size: 100%；
产出的代码 background-size 这个属性没了 导致背景图片变大

**Comment by xwenliang** [comment]
这时候需要设置图片的缩放比，详情见[fis-spriter-csssprites](https://github.com/fex-team/fis-spriter-csssprites)

**Comment by linjingming** [comment]
生成后单background-size的单位为px我想改成rem能指定吗

**Comment by xiangshouding** [comment]
现在还不能~

**Comment by fouber** [comment]
@linjingming 

csssprite需要确定像素值才能计算合并的方式，rem没办法用于这样的计算。如果全局都是rem控制background-size，那就放弃fis的csssprite，或者自己写一个插件批量替换。如果只是个别背景图要rem控制，那就别让它们参与csssprite了。

fis的csssprite只被设计用来解决70%的sprite问题，才能做到“只需要在图片后面加?__sprite”这么简单的使用方式，它并不完美，但是是折衷了使用和维护成本之后的方案，服从工程化原则
