### ISSUE TITLE
fis-parser-sass插件安装失败

### ISSUE THREAD

**Issue by jasonzhao588** [fex-team/fis#365]
我之前很轻松的安装了fis-parser-less,可不知道为什么fis-parser-sass总数安装不上，是不是缺少什么东西啊？

**Comment by Megasu** [comment]
别说的那么笼统 ，npm install -g fis-parser-sass 安装一下，会有什么报错信息吗。

**Comment by 2betop** [comment]
一般来说两种可能。

1. fis-parser-sass 不支持 node >= 0.11
2. 把 bae 给屏蔽了，导致 预编译版本下载不下来。

**Comment by jasonzhao588** [comment]
红字提示信息如下：
C:\Users\Jason\AppData\Roaming\npm\node_modules\fis-parser-sass\node_modules\fis-sass\build\binding.vcxproj(47,46): error MSB4025: 未能加载项目文件。给定编码中的字符无效。 第 47 行，位置46。

**Comment by xiangshouding** [comment]
This issue was moved to fex-team/fis-parser-sass#21
