### ISSUE TITLE
html里资源定位时的问题

### ISSUE THREAD

**Issue by mpr0xy** [fex-team/fis#366]
如果我html里的资源本身就是url不对应相对目录。
比如我有一个项目目录叫project
project/templates里有一个html文件里写里有如下语句。

```html
<link href="static_root/css/a.css" rel="stylesheet">
```

能正常使用，因为程序运行时有后端路由定位。比如使用的django。

但实际上a.css在以下目录
project/static_root/css/a.cc

使用fis进行压缩时，我不知道怎么进行资源定位，请帮助我。谢谢。

**Comment by fouber** [comment]
```html
<link href="/static_root/css/a.css" rel="stylesheet">
```
在以``/``开头，表示项目根目录

**Comment by mpr0xy** [comment]
@fouber  谢谢
我知道。关键是我的static_root其实是个虚拟路径。在真实的文件目录里static_root不再根目录。

最后我重新配置了django的路由，解决了问题。
