### ISSUE TITLE
csssprites可以设置哪些图片合并在一起吗

### ISSUE THREAD

**Issue by huangfeng02** [fex-team/fis#367]
csssprites可以设置哪些图片合并在一起吗
比如  a.png,b.png合并成ab.png
  c.png,d.png合并成cd.png 
如果所有图片都合成一个图片不好管理 也太多了 我一般是按功能模块合并的

**Comment by xiangshouding** [comment]
- 现在的 spriter 以 css 文件为单位进行合并，每一个 css 文件合并出若干张图片。
- 当需要进行分类合并时，适当拆分 css 文件，或者打包合并规则就可

**Comment by huangfeng02** [comment]
“每一个 css 文件合并出若干张图片” 这个怎么搞的 ？现在不是一个css文件里所有图片都是合并成一个图片？

**Comment by xiangshouding** [comment]
这个是无法进行配置的，程序会自动按照repeat-x，repeat-y等等信息进行合并，合并出_x, _y, _z等的一些图片，并不是只有一张图片。

另外，如果加入了某一些配置来适应产出多张图片，我认为这样虽然可能更灵活，但是增加了使用复杂度。
