### ISSUE TITLE
请教fisp打包CSS时，如何把不同模块中的css打包成一个

### ISSUE THREAD

**Issue by trainGitHub** [fex-team/fis#370]
例如 common 模块有这些css
common:static/css/common.scss
common:static/css/grid.scss

home 模块有这些css
home:static/css/index.scss
home:static/css/temp.scss

页面在home模块中引用了common中的css和home中的css
{%require name="common:static/css/grid.scss"%}
{%require name="common:static/css/common.scss"%}
{%require name="home:static/index/index.scss"%}
{%require name="home:static/index/temp.scss"%}

fis-conf.js配置如下
fis.config.set('pack', {
    'pkg/aio.css' : '**.scss'
});

这样的配置只会把 home 模块下的 index.scss 和 temp.scss 打包成 aio.css。但是不能把common模块里的css一起打包进aio.css。 

js也有类似问题，请教这如何解决？

**Comment by fouber** [comment]
为何要打包？

**Comment by trainGitHub** [comment]
为减少请求，想把CSS都打包成一个。

**Comment by fouber** [comment]
@trainGitHub 

光想到了请求，没想过跨页面间的缓存复用么？公共资源本来就是多页面共享的，独立成url性能更好。况且现在PC端浏览器95%以上是6个或以上并发连接的，多个资源并行下载对PC来说才是更好的优化策略
