### ISSUE TITLE
少年们！怎么让html中img标签引用的图片得到sprites处理, THX！

### ISSUE THREAD

**Issue by csulyl** [fex-team/fis#371]

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis-spriter-csssprites 看 README

**Comment by fouber** [comment]
@csulyl 

我们先不考虑fis怎么处理，你觉得几个img引用的图片得到sprite，它最终的编译结果是怎样的呢？

**Comment by fouber** [comment]
https://m.youtube.com/

可以用移动设备UA看一下这个页面，youtube怎么处理image的，不过这个已经不属于编译构建的处理范畴了，而是一种运行时的合并服务处理的
