### ISSUE TITLE
fis server start 只能显式指定node

### ISSUE THREAD

**Issue by forfuns** [fex-team/fis#372]
必须使用 fis server start --type node ，其他默认或指定都没有作用
还有的是，运行完服务后，打开却不是当前项目（https://github.com/hefangshi/fis-quickstart-demo.git）的内容，而是express4的目录，里面只有server.js和server.log两个文件。

请问是我的环境有问题吗？

win7 64bit
node v0.10.26

**Comment by xiangshouding** [comment]
没启动成功吧？

**Comment by forfuns** [comment]
@xiangshouding  什么意思？？？可以启动成功，但运行的结果好像和介绍的不一样
而且还有一个问题，就是fis server stop和restart都没效果，必须使用fis server clean后才可以继续start

**Comment by forfuns** [comment]
@xiangshouding 我就是用这种方法重启的，但是依旧没效果！

**Comment by zymiboxpay** [comment]
@xiangshouding 谢谢！你帮大忙了
