### ISSUE TITLE
请问如何在当前位置插入<script></script>,默认会把script移动到页面底部，我用的pure解决方案

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#378]

**Comment by hefangshi** [comment]
<script data-fixed="true" src="xxx.js"></script>

**Comment by fancyboynet** [comment]
找到方法了，用<script data-fixed='true'></script>

**Comment by fancyboynet** [comment]
找到方法了，添加自定义属性data-fixed='true'

**Comment by hefangshi** [comment]
抱歉，似乎当时我的回复没有显示出来。你找到的就是正解。

**Comment by fouber** [comment]
@hefangshi 

在github上写回复，如果是代码形式的，尤其是html，记得加上 **```html** 这样的包裹才能正确显示，否则会被当做一段html内容解析，因为markdown也支持直接写合法的html标签。

**Comment by sapjax** [comment]
<script>alert(1)</script>

**Comment by fouber** [comment]
@sapjax 

当然不会让你写了。。。不过不能预测到底是markdown没解析还是github设置了规则去掉了markdown解析后的不合法标签。最终前端没有看到script标签这是肯定的，否则就是一个xss啦

**Comment by hefangshi** [comment]
@fouber 哦对。。忘了这茬了。。
