### ISSUE TITLE
战士们！请教个问题,代码检查插件lint的配置,Thx！

### ISSUE THREAD

**Issue by csulyl** [fex-team/fis#380]
要在fis中启用lint插件是不是如下步骤：
  1. npm install -g jshint
  2. fis-conf.js 配置 fis.config.set('modules.lint.js', 'jshint');
  3. fis release -l

**Comment by xiangshouding** [comment]
NO，需要包装成 FIS 插件的 jshint，参见 https://www.npmjs.com/package/fis-lint-jshint

**Comment by csulyl** [comment]
good job!
