### ISSUE TITLE
fis_debug 后有sourcemap的路径错误

### ISSUE THREAD

**Issue by xuyongtao** [fex-team/fis#382]
配置为：fis.config.set('settings.optimizer.uglify-js.sourceMap', true);
错误截图：
![image](https://cloud.githubusercontent.com/assets/7931332/6592396/9a8eec24-c808-11e4-8e1d-b37bc4b001f2.png)

**Comment by xiangshouding** [comment]
`fis_debug` 只是把 合并的包 打散， 方便定位问题，而且这个功能是可以附带上线，只要能定位文件，基本上问题就很容易能发现了。而 `sourceMap` 同样有这个功效，只是其产出的 `.map` 把其弄上线就有些多余了。

所以，这块当初设计的时候没有细致考虑，因为够用。不过其显然是个问题，在下一代 fis3 中，会得到解决。
