### ISSUE TITLE
请教，linux下如何在没网络的情况下安装FIS，thx！

### ISSUE THREAD

**Issue by csulyl** [fex-team/fis#389]
我是这么做的：
1. 首先我在有网络的机器上下载了node-v0.12.0-linux-x64.tar.gz  ，上传至linux环境，然后解压开，指定  
    了nodejs的环境变量，至此 nodejs安装成功
2. 我在有网络的机器上从github下载了fis后上传至上一步linux环境中nodejs的node_modules目录下，
    fis -v失败。。。

**Comment by ekousp** [comment]
你需要解决的问题是离线安装 npm 包：https://github.com/arei/npmbox

**Comment by xiangshouding** [comment]
[?]

2015-03-17 11:25 GMT+08:00 litianzhao <notifications@github.com>:

**Comment by xiangshouding** [comment]
http://pan.baidu.com/s/1mg9SN00   已经做好了一个 npmbox 文件，在参考 @ekousp 提供的 https://github.com/arei/npmbox 来做安装。
