### ISSUE TITLE
因为公司图片都统一放在图床上，如果css中图片引用地址使用绝对路径，release -p无法sprite，请问怎么解决这个问题？

### ISSUE THREAD

**Issue by zhujz** [fex-team/fis#398]

**Comment by xiangshouding** [comment]
- 保证图片要在本地，这样才能读到图片
- 保证写的语句（图片路径）要能被 FIS 解析并找到这个文件；一般是相对于 css 相对路径或者是相对于项目根目录的绝对路径。

可能你是说无法满足上面的两条条件的情况下如何合并是吧？

**Comment by zhujz** [comment]
是的，用的图片都是放在线上的，与css文件不在同一域名下，无法用相对路径引用图片。
而且我试过了，把图片放到本地进行打包发布csssprite是成功的，但是图片终归还是要放到图床上去的，我能想到的解决办法也只有：release后把图片放到图床上，然后改压缩好的css中的图片地址（看起来好笨= -）。
另：“libpng warning: iCCP: known incorrect sRGB profile”
release时出现这个警告是怎么回事，好像没什么影响，但查到的解释看不太懂。

**Comment by xiangshouding** [comment]
嗯，FIS 本来就是这么运作的呀。你的做法是对的。不过不需要你手动去改地址，可以设置 domains 来解决问题，具体看文档。

warning 没事儿，就让它报去吧。

**Comment by zhujz** [comment]
好的，谢啦~
