### ISSUE TITLE
某个目录下的文件不需要MD5戳，或不需要压缩，fis-conf.js里分别怎么写 

### ISSUE THREAD

**Issue by pannysp** [fex-team/fis#402]
1、某个目录下的js文件不需要压缩和MD5戳。
2、某个目录下所有文件（js,css,png）不需要MD5戳，fis-conf.js里分别怎么写 ？

**Comment by pannysp** [comment]
我自己试出来了，呵呵。

fis.config.set('roadmap.path', [
    // 模板文件不需合并及MD5
    {
        reg : 'tpl/build/**.js',
        useHash : false,
        useOptimizer: false
    },

    // modules文件夹下所有文件不需要MD5戳
    {
        reg : 'js/modules/**',
        useHash : false
    }
]);

**Comment by xiangshouding** [comment]
:+1:
