### ISSUE TITLE
使用fis-postpackager-simple自动打包零碎文件之后css背景图没有合并

### ISSUE THREAD

**Issue by painty** [fex-team/fis#403]
fis-postpackager-simple插件设置为将页面中独立的资源引用自动合并为打包资源之后，css里面的图片sprite没有合并；`path`里面对css文件手动设置`useSprite:true`，得到的却是以css文件为单位的sprite合并。
那么问题来了，如果想要自动打包并且希望自动合并起来的css文件的所有背景图也自动合并起来怎么办？（因为自动打包发生在sprite处理之后所以没有自动合并？）

**Comment by hefangshi** [comment]
恩~并没有做这样的支持，希望将多个CSS的引用图片打包的话，需要自己手动设置pack。simple会自动进行打包资源的引用替换。

**Comment by painty** [comment]
1.html需要a.css+b.css；2.html需要b.css+c.css，手动设置pack，b.css只能进入先定义的pack文件中，目前我是遇到这样的困惑。

**Comment by painty** [comment]
对于手动打包的用途，我想是为生成基础的公共包吧，这样缓存效果好；不过我们公司就是强制规定一个页面只能一个样式文件 ╮(╯_╰)╭

**Comment by hefangshi** [comment]
是的，手动设置PACK是无法重复打包的，这个问题可以主动去沟通一下，答案已经在你心中了；）

另外可有一些trick手段来避开这种限制，你可以利用FIS的资源嵌入功能手动将多个CSS嵌入一个CSS来达到你想要的功能。

**Comment by fwon** [comment]
@painty 之前也遇到这个问题，__inline 应该没法解决，因为雪碧图css生成是在postpackager阶段的，在文件process阶段内嵌资源并不是最终的CSS，所以在deploy的时候做这个处理可能会比较好。 所以自己封装了这个工具 [fis3-deploy-combo](https://github.com/fwon/fis3-deploy-combo)
