### ISSUE TITLE
fis每次release都是针对整个项目，多人同时开发一个项目时该如何配合？

### ISSUE THREAD

**Issue by striver-x** [fex-team/fis#406]
或者能否分享下你们是怎么干的？ :smile:

**Comment by hefangshi** [comment]
对于大型前端项目，我们一般会将一个站点按照功能进行划分，比如用户中心、首页、二级页等等，每一个功能区域都是一个独立的FIS项目，在多人协作时，每人只负责一个项目，通用的内容则由一个common模块管理。简单来说就是通过物理上将项目做隔离来解决多人协作时的冲突问题。

**Comment by striver-x** [comment]
OK，明白了，谢谢！
