### ISSUE TITLE
fis release -d ./output

### ISSUE THREAD

**Issue by zhujz** [fex-team/fis#407]
在fis-quick-demo下执行fis release -d ./output，之后在apache打开*/*/output/index.html，文件都加载不出来，路径变成了/pkg，直接变成了域名后的路径。要怎样配置才能正常使用fis release -d ./*，之前的配置为：
fis.config.set('pack', {
    'pkg/lib.js': [
        '/lib/mod.js',
        '/modules/underscore/**.js',
        '/modules/backbone/**.js',
        '/modules/jquery/**.js',
        '/modules/vendor/**.js',
        '/modules/common/**.js'
    ]
});
看不太懂demo里的这个配置信息。。求解救

**Comment by xiangshouding** [comment]
- 如果在 apache 下查看，把 output 那层目录拿掉就可以了。把所有的产出都 copy 到 Apache 的根目录下。
- 如果还有疑问继续回帖

**Comment by zhujz** [comment]
如果把所有的产出都 copy 到 Apache 的根目录下也只是为了查看，上线后是不是还要调整路径才能正常访问？我想把产出的页面中引用的js路径改为相对路径，而不是url的pathname，这样不论放在哪里还是单独拿出来都能正常查看，配置信息该如何修改？
我不明白上面一段配置信息中'pack'，'pkg/lib.js'，'/lib/mod.js'等的结构含义

**Comment by xiangshouding** [comment]
**由于工程需要，必须转成 `/` 开头的一些 URL。**

至于你说的每次都 copy，这个动作是通过**部署规范**来约定的。比如我线上目录是什么，然后配置产出目录正好能对上线上目录即可。

对于配置中

- `pack` 是合并资源到某一个文件里面的意思，相应官网文档有介绍。
- `pkg/lib.js` 可以认为是匹配资源备份到了**源码文件** `pkg/lib.js` 里
- `/lib/mod.js` 意思是相对于项目根目录（源码）的路径

**Comment by zhujz** [comment]
好，谢谢你的时间，我再研究下~
