### ISSUE TITLE
fis-pure无法使用--tpye node启动吗

### ISSUE THREAD

**Issue by changexbc** [fex-team/fis#408]
E:\fis-demo\fis-pure-demo-master>pure server start --type node
starting fis-server .. at port [8080]

 [NOTIC] browse http://127.0.0.1:8080/

启动了 但是一直等待 http://127.0.0.1:8080/，换端口号也没用，请教各位如何解决

**Comment by xiangshouding** [comment]
```
pure server clean
```
后重试

**Comment by changexbc** [comment]
@xiangshouding 以尝试 没有用  是否一定要装php和java环境？

**Comment by xiangshouding** [comment]
不需要，可能有 bug 吧。

**Comment by changexbc** [comment]
@xiangshouding 请问怎么解决，我已经重装过fis和fis-pure了

**Comment by xiangshouding** [comment]
![ff](https://cloud.githubusercontent.com/assets/631195/6781635/0a0d1b70-d1aa-11e4-94c7-5649e9a8b2a5.png)

我这边执行正常。

这样，实在不行就用 java 的吧。后续把对 express 的依赖干掉。这样不下载 npm 包会稳定一些。

**Comment by changexbc** [comment]
不知道是不是windows的node版本有这个问题

**Comment by changexbc** [comment]
@xiangshouding 装了java发现用java是可以的，不知道是不是windows的node有问题，不过奇怪的是fis-quickstart-demo中使用fis server start --type node是可以的，fis-pure-demo中使用pure server start --type node却不可以

**Comment by xiangshouding** [comment]
嗯，赞，我复现后修复

**Comment by hefangshi** [comment]
fis-pure使用的是1.8.5版本的FIS，你工作正常的FIS版本是多少？

**Comment by changexbc** [comment]
@hefangshi 我是最新版本的fis  v1.9.10

**Comment by hefangshi** [comment]
你把pure重新安装一下再试试看。

**Comment by xiangshouding** [comment]
#413

**Comment by 532604872** [comment]
我这边是fis-quickstart-demo中使用fis server start --type node是可以的，fis-pure-demo中使用pure server start --type node却不可以。我想是不是需要配置另一个ip地址，比如127.0.2：8080

**Comment by hefangshi** [comment]
启动失败的报错信息需要提供一下

**Comment by 532604872** [comment]
谢谢@hefangshi 帮助解答
提示信息：
D:\demo\fis-pure-demo>pure server start
checking java support : java not support!
 [WARNI] Error: spawn java ENOENT
To start the node server willstarting fis-server .. fail

 [ERROR] Address already in use:8080

D:\demo\fis-pure-demo>pure server start --type node
starting fis-server .. fail

 [ERROR] Address already in use:8080
顺便请教一下：（如何配置多个生成项目，如：两个相同的项目，我想拥有两个域名：127.0.0.1：8080和127.0.0.2：8080等）。

**Comment by hefangshi** [comment]
错误原因是 `[ERROR] Address already in use:8080`

你可以

```
pure server start --type node --port 8081
```

**Comment by 532604872** [comment]
非常感谢@hefangshi 帮助解答
再请问教一下：
我想改变域名：127.0.0.1：8080变成127.0.0.2：8080，该如何？
