### ISSUE TITLE
fis-pure require(zepto)错误

### ISSUE THREAD

**Issue by changexbc** [fex-team/fis#409]
```javascript         
var $ = require('zepto')
console.log($)

var word = $('.fis-test').text()
alert(word)
```
输出：
```
Object {}
Uncaught TypeError: object is not a function
```
换成jquery正常，zepto试过用fis install下载还是一样的问题

**Comment by xwenliang** [comment]
试试 var $ = require('Zepto');

**Comment by changexbc** [comment]
zepto只是文件名字啊，对象已经返回了，只是个空的对象。

**Comment by hefangshi** [comment]
zepto没有module.exports，可以自己修改zepto源代码添加一下module.exports = window.Zepto;

**Comment by 2betop** [comment]
重新安装一次就好了。 `fis install zepto`

**Comment by hefangshi** [comment]
我把fis-pure也做了一次升级，安装最新的fis-pure后，就可以pure install zepto了。

**Comment by changexbc** [comment]
原来这样，非常感谢各位！
