### ISSUE TITLE
fis 压缩图片问题

### ISSUE THREAD

**Issue by 5star2014** [fex-team/fis#411]
fis release -o  此命令会压缩图片吗？
测试图片大小未改变。

**Comment by xiangshouding** [comment]
只会对 png 图片做压缩

**Comment by 5star2014** [comment]
OK 测试后，发现 PNG-24 的会压缩， PNG-8 的不会。

**Comment by fouber** [comment]
@5star2014 

fis有两种图片压缩器：

1. pngcrush（默认）：将压缩png24，png8的冗余信息也会压缩
1. pngquant（需要配置）：压缩所有png图片为png8，就是png24会有些损失，这个压缩率更高一些。

开启pngquant的方法：

```js
fis.config.set('settings.optimizer.png-compressor.type', 'pngquant');
```

**Comment by 5star2014** [comment]
@fouber  非常谢谢，这下明白了。
