### ISSUE TITLE
http://oak.baidu.com/下二级域名下的网页都无法打开

### ISSUE THREAD

**Issue by apexji** [fex-team/fis#416]
http://oak.baidu.com/下二级域名下的网页都无法打开，无法浏览。可能是域名解析有问题。希望能尽快解决，正常浏览。谢谢。

**Comment by hefangshi** [comment]
并不是域名解析，应该是github.io最近墙比较高导致的，目前看来在逐步恢复中。

**Comment by xiangshouding** [comment]
以后文档之类都会放到 GitHub wiki，所以应该会减少由于 `.io` 域名封锁所导致的访问问题。

**Comment by apexji** [comment]
fis的常用帮助文件及重要技术资料尽可能放在国内。否则太不方便。

**Comment by xiangshouding** [comment]
@apexji 哟西，就这么办；

**Comment by xiangshouding** [comment]
This issue was moved to fis-dev/fis-doc#4
