### ISSUE TITLE
Cannot find module `components/jquery/jquery.js`

### ISSUE THREAD

**Issue by LiudaiC** [fex-team/fis#424]
执行fis install jquery bootstrap以后，在fis-quickstart-demo中已经有components/jquery/jquery.js存在了，但是添加上下面的代码后：

```
require('bootstrap/button');
var $ = require('jquery');


$('.btn').click(function() {
    alert('Magic');
});
```
报错：
Cannot find module `components/jquery/jquery.js`
这是什么原因呢

**Comment by 2betop** [comment]
那段 roadmap.path 加了吗？我记得 fis install 的时候会提示你！

**Comment by LiudaiC** [comment]
@2betop 加了，就是这一段吧：
fis.config.set('roadmap.path',[{
     reg: /^\/components\/.*\.js$/i,
     isMod: true,
     jswrapper: {
         type: 'amd'
     }
 }]);

**Comment by 2betop** [comment]
fis-quickstart-demo 没有用 `autoload`  插件，那个要用什么，自己得手动引用什么，你还是去 [fis-commponents-demo](https://github.com/fex-team/fis-components-demo) 中去修改，去尝试吧！

**Comment by LiudaiC** [comment]
谢谢。@2betop ，我换成 fis-commponents-demo了，但是server start的时候居然还是以前quickstart的页面，可以我已经把quickstart删了，这个是fis什么地方有缓存吗

**Comment by xiangshouding** [comment]
首先，你执行

```bash
fis server clean
```

接口清除本地测试环境的 `www` 下的内容。

其次，可能需要给你介绍一下 本地测试环境 和 线上环境 以及说明为什么还需要一条命令去清理 www 目录下的**老代码**；

![1](https://cloud.githubusercontent.com/assets/631195/7111857/ad9d0d5c-e1f6-11e4-9477-a9ae1ac1de0d.png)

如上图，有两次 release；

- 直接 release 不加 `-d` 参数

  当不带 `-d` 参数指定必要的产出目录或者是 deploy 配置的情况下，默认是被发布到了本地的一个测试环境，当发不到测试环境后，整个代码的产物已经跟 fis 编译没有啥关系了，这个测试环境(1)就像是完全独立的一个 Web 服务。为了表征这种独立性，我在产出的方向线上画了一个横杠(3)；那么发布后的代码是跟源码以及 fis 编译脱离关系了，**对于 fis 来说发布后的产物到了什么地方其是不关心的**。所以假设你上一次发布了一些代码到测试服务器的 www 目录下，如果你主动不去删除，这些代码会一直存在在你的磁盘中，它的位置你可以执行 `fis server open` 打开。为了方便，我们实现了 `fis server clean` 这样一个命令来方便这种清理工作。

- release 添加 `-d` 产出到目录 `./output` 下

  上面说到对于 fis 来说产出到什么地方发布后已经不关心了，就如同加了 -d 参数产出到了一个 ./output 目录下，output 目录下的产出物会被拷贝(2)到任意的地方去使用。同理我们就得出产出后对于编译发布流程是不会关心产出代码去了什么地方的。

以上两条说明了下 fis 发布这个流程中的一些细节，希望你可以从中可以对 fis 了解更深入一些。
