### ISSUE TITLE
fis能应用到angularjs项目吗？

### ISSUE THREAD

**Issue by chenbeitingting** [fex-team/fis#427]
fis能应用到angularjs项目吗？

**Comment by xiangshouding** [comment]
可以；

**Comment by chenbeitingting** [comment]
有类似完整项目的源码吗？可以分享出来吗？@xiangshouding

**Comment by fouber** [comment]
@chenbeitingting 

这个问题就好像在问“fis能不能用jquery”一样，fis只是工具，在fis之上用什么，完全是自己发挥的，不需要示例啊，如果有示例，那也不是fis项目，只是用fis作为工具的angular项目而已。

其实你也可以用一个angular项目直接用fis去发布预览，完全能看到效果
