### ISSUE TITLE
fis release -m 不能替换HTML中的图片引用地址。

### ISSUE THREAD

**Issue by JailBreakC** [fex-team/fis#428]
fis release -m 之后脚本和CSS引用地址替换了但是图片引用地址都没变。

**Comment by xiangshouding** [comment]
路径是否写错了？

**Comment by fouber** [comment]
@JailBreakC 

### 一定是相对路径写错了！！！

**Comment by JailBreakC** [comment]
我知道为什么了，我用的angular。 html是模板文件，所以路径是不对的。。。

发自我的 iPhone
