### ISSUE TITLE
我的laraverl项目上无法应用FIS，可以方法解法?

### ISSUE THREAD

**Issue by Liu-Young** [fex-team/fis#429]
无法应用FIS的原因主要是因为在模板中引用css和script是这样写的
```html
    <link rel="stylesheet" href="{{ cdn('css/shop.css') }}">
    <link rel="stylesheet" href="{{ cdn('css/jquery.jqzoom.css') }}">
    <link rel="stylesheet" href="{{ cdn('css/jquery.nouislider.css') }}">

    <script src="{{ cdn('js/jquery-1.8.2.min.js') }}"></script>
    <script src="{{ cdn('js/jquery.ddslick.js') }}"></script>
    <script src="{{ cdn('js/jquery.jqzoom-core.js') }}"></script>
```
`{{ cdn('css/shop.css') }}`中，`cdn`是一个函数，在运行的时候会被替换成正确的地址。如下图
![image](https://cloud.githubusercontent.com/assets/8478230/7063515/0b3ffa34-deda-11e4-848a-0e0d9e0fe2a9.png)
![image](https://cloud.githubusercontent.com/assets/8478230/7063556/51e3a68e-deda-11e4-8d92-a1e0719459a6.png)
当然在FIS有可以实现`cdn`函数的功能，但是我希望可FIS可以这样处理，`{{ cdn('css/shop.css') }}`可以替换成`"{{ cdn('css/shop_fb0f186.css') }}"`。

**Comment by xiangshouding** [comment]
后续会把**标准化**插件化，到时候你自己就能写插件在编译层面搞定这个事情；

不过，一般 cdn 被替换上去是一个不错的选择；

不过可以在运行期去搞定你这个事情；

- 代码编写的时候，资源 URI 写成

    ```php
   <link  href="{{ cdn("<ID>") }}" ... >
    ```
- 实现 cdn 这个函数，根据传入的 id 去查 `map.json` 获得带 cdn 的 url 返回。
- 搞定
