### ISSUE TITLE
同时开启多个服务器？

### ISSUE THREAD

**Issue by richard-chen-1985** [fex-team/fis#430]
可能我同时支援多个组的项目的前端开发，我可以指定document的root目录，但是不能同时开启多个服务器，因为有时候我正在开发一个项目，但是另一个项目组的人想看我机器上他们的项目效果，我只能把目前正在开发的项目停掉，感觉有点不方便

**Comment by hefangshi** [comment]
可以考虑换个思路来解决这个问题，将自己开发的前端代码发布到其他项目组的测试机上，这样其他项目组浏览项目也更方便，你自己也不需要考虑同时启动多个服务器。

**Comment by richard-chen-1985** [comment]
嗯，确实这样也能解决问题

**Comment by sapjax** [comment]
可以指定不同的port
`fis server start -p 3000`

**Comment by hefangshi** [comment]
@sapjax 只能同时存在一个。。

**Comment by xiangshouding** [comment]
其实，有各种玩法，如果非要开启多个 server 也是可以的。

比如，我可以通过很简单的方法自定义两个命令。
- A

    ```js
    // file a.js
    var fis = require('fis');
    fis.cli.name = 'A';

    fis.cli.run(process.argv);
    ```
- B

    ```js
    // file b.js
    var fis = require('fis');

    fis.cli.name = 'B';

    fis.cli.run(process.argv);
    ```    

这样 A 和 B 就有了 FIS 的所有能力，这个就相当于简单的做了一次解决方案的封装。

A 和 B 执行逻辑放到 a.js 和 b.js 中，当这两条命令搞定一个。我就可以轻松的通过 node 直接去执行它俩。

```bash
node ./a.js server start -p 8001
```

```bash
node ./b.js server start -p 8002
```

OK，我可以启动俩 FIS 服务了，因为 A 和 B 只是对 FIS 的简单封装，所以它俩跟 FIS 表现出的能力是一样的。

这样做了以后 A 和 B 有完全独立的执行空间，包括 DOCUMENT_WWW、缓存、Server 信息等。

到了这里，这个事情大概基本上完成了。

完全分开以后，就不能再用 ` fis release ... ` 去发布一个项目了，因为你已经通过 A 和 B 隔离出了两个 FIS 。

所以需要发布时用如下方式进行发布；

```bash
node ./a.js release -r <fis-project> # 发布到 8001 监听的 WWW 目录下
```

```bash
node ./b.js release -r <fis-project> # 发布到 8002 监听的 WWW 目录下
```

其他一切对于对应项目的操作都得使用上面介绍到的命令。

接下来，你就需要做的是简化命令，那么如何简化命令呢，你可以通过软连，软链一个非常便于输入的命令到 `/usr/bin` （*nix） 或者是制作一个 BAT 文件（Windows），这个过程就不赘述了。

当然，FIS 的限定是有意义的，因为同时去开发不同团队项目的可能性不是很大，那么限制一个**解决方案**一个启动 Server 是有意义的。

**Comment by richard-chen-1985** [comment]
@xiangshouding 不错，我对FIS的了解还不够深刻

**Comment by dajbd** [comment]
我需要多项目使用FIS~~~开发不同团队项目的可能性不是很大？其实蛮普遍的~~~别的工具，好像都是支持多项目的。多server启动，还有方案可以这样：fis release -d ../dist -w   发布后，再结合http-server 服务器，做到多服务器，但是这样不能完全模拟FIS服务器的能力。

**Comment by RachelRen** [comment]
@xiangshouding 这个A和B是对应的项目名称吗？ 还有这些a.js和b.js放在什么目录下的？

**Comment by hitao123** [comment]
@xiangshouding  希望在下一个版本能支持开启多个服务

**Comment by fancyboynet** [comment]
多个服务还是有需求的
