### ISSUE TITLE
js __inline 源码报错，编译后正常

### ISSUE THREAD

**Issue by whd311** [fex-team/fis#433]
__inline is not defined，
是不是少了什么配置呢？

**Comment by xiangshouding** [comment]
`__inline` 是一个编译函数，必须通过编译才能得到正确运行

**Comment by whd311** [comment]
那我的开发版本，就一直让它报错下去？

**Comment by xiangshouding** [comment]
@whd311 不管是开发还是不开发，FIS都需要经过编译才能使用。

**Comment by whd311** [comment]
@xiangshouding ，唉，大概懂了。因为之前我只用了其中的资源压缩和代码合并功能，所以，开发版本就只有两个，一个开发版本，一个编译后的压缩版本。要在js里面嵌入js的话，就得再多一个，编译后未压缩的版本，对吗？
