### ISSUE TITLE
require 报错

### ISSUE THREAD

**Issue by lys623** [fex-team/fis#434]
define(function(require, exports, module) {
    var currentView = null
    var pageOptions = null
    exports.load = function (curtype) {
        switch (curtype) {
            case 'note':
                pageOptions = require('./' + curtype+'/'+curtype+'.js');
                break;
        }
        if (currentView) {
            currentView.$destroy(true)
        }
        currentView = new Vue(pageOptions)
            .$mount()
            .$appendTo($('#rightbarB')[0])
    }
})
一个tab切换时去加载，结果报错，该怎么写才不报错呢？fis amd demo
![image](https://cloud.githubusercontent.com/assets/4364314/7142065/33f0a17c-e308-11e4-8385-cd5cc4f8dd15.png)

**Comment by xiangshouding** [comment]
- 如果是 AMD 请参考 [fex-team/fis-amd-demo](/fex-team/fis-amd-demo)。
