### ISSUE TITLE
如何把配置文件的domain值输出到js ？

### ISSUE THREAD

**Issue by mutongwu** [fex-team/fis#435]
配置文件有个: domain: "http://ss.a.com" 

然后，在js里面，通过 var a = __uri("a.css") 
可以得到 
var a = "http://ss.a.com/a.css"
那么，如果，我只需要得到 domain的值。应该如何写呢？
var domain = __uri("???")

**Comment by xiangshouding** [comment]
不知道你的需求是什么？

我想你是像实现；

```js

var lists = ['a.js', 'b.js', 'c.js'];

lists.forEach(function (file) {
  load(domain + file);
});
```

这样的功能吗？

**Comment by mutongwu** [comment]
不是。我的意思是，如何把静态资源的domain，写到html/JS里面，从而，有些资源，我可以手动拼接文件的地址。例如：


var domainUrl = __uri("domain") // 希望这里得到 配置的值：" http://ss.a.com "

var specialPic = domainUrl + "some/path/a.jpg";

**Comment by xiangshouding** [comment]
我想我说的跟你是一致的，那么问题来了。

当你 
```js
var specialPic = domainUrl + "some/path/a.jpg";
```
的时候，FIS 编译完加完 md5 戳后，你这块这个 `a.jpg` 是加不上的；那么你不得不写成这样

```js
var specialPic = domainUrl + __uri('some/path/a.jpg');
```
那么。。

说到这块估计你发觉了，不管怎么样都是需要 `__uri` 的；

**Comment by mutongwu** [comment]
嗯。是的。
但是又有奇葩的是，有些image，它的名称就是 id。
譬如：我从接口拿到一个imageList:["a","b"]

然后，我要显示这些图片，这些个图片的地址是：
var specialPic = domainUrl + "path/noMd5/" + imageList[0] + ".jpg"; // 是不是很蛋疼？ - -！

所以，最终得到： www.a.com/paht/noMd5/a.jpg !

**Comment by xiangshouding** [comment]
`__uri` 是个编译函数，那么参数必须是一个字符串字面量

```js
var imgList = [
  __uri('a.jpg'),
  __uri('b.jpg')
];

var sP = imgList[0]; 
```

**Comment by mutongwu** [comment]
可是，这个 imgList 是我ajax读取回来的哦。其中的潜规则就是： 

imgList:["a","b"] -----------> 前端拼接为：["www.a.com/paht/noMd5/a.jpg " , www.a.com/paht/noMd5/b.jpg !]

**Comment by xiangshouding** [comment]
哦，这样啊；
