### ISSUE TITLE
FIS 内置 server 如何写 rewrite

### ISSUE THREAD

**Issue by BelinChung** [fex-team/fis#436]
通过 fis server start 启动的内置服务器
我需要设置一个简单的 rewrite 规则，将所有的请求分发回 index.html 
请问该在哪里配置 server.conf 呢？谢谢！

**Comment by hefangshi** [comment]
如果是启动的node的server

直接在项目根目录建立一个server.conf

可以参考

https://github.com/fex-team/yog-devtools/blob/master/lib/rewrite.js#L7-L10
