### ISSUE TITLE
命令行里的类似3d的字符画是什么工具生成的吗?

### ISSUE THREAD

**Issue by GilbertSun** [fex-team/fis#437]
![image](https://cloud.githubusercontent.com/assets/1615364/7176281/886e3e7e-e44f-11e4-83e7-f8b25304a2f6.png)

请问一下这个东西是用什么工具生成的吗？方便的话能告诉一下吗 -:)

**Comment by xiangshouding** [comment]
http://patorjk.com/software/taag/#p=display&f=Graffiti&t=fis
