### ISSUE TITLE
怎么编译百度模板，如何传入模板数据？

### ISSUE THREAD

**Issue by heysb** [fex-team/fis#440]
安装了插件fis-parser-bdtmpl，开启了插件
```
parser:{ 
   tpl:['bdtmpl']
}
```
.tpl文件使用 BaiduTemplate 语法，接下来要怎么传入模板数据？？

**Comment by xiangshouding** [comment]
```js
var tplFunc = __inline('./a.tmpl');
var data = {
  "title": "Foooooooooo"
};
tplFunc(data);
```

**Comment by heysb** [comment]
这段代码要放在什么位置呢？

**Comment by xiangshouding** [comment]
基本工作原理是，本地把前端模板编译成 `function` 然后运行时直接用就可以了。

比如

```
/a.html
/js/a.js
/js/a.tmpl
```

a.tmpl

```tpl
<div> <{=title}></div>
```

a.js

```js
var tplFunc = __inline('./a.tmpl');
var data = {
  "title": "Foooooooooo"
};
console.log(tplFunc(data));
```

a.html
```html
<script src="./js/a.js"></script>
```

**Comment by heysb** [comment]
按照你的做法，编译后的结果是js动态出的，这样不利于SEO，我需要的是把a.tmpl编译后的结构嵌到a.html里一整个产出

**Comment by xiangshouding** [comment]
@heysb 那你的数据怎么来，编译的时无法知道你的数据啊。。这种情况直接用后端渲染的方式吧。

**Comment by heysb** [comment]
我希望数据读取本地一个json文件，编译的时候就直接生成html结构

**Comment by xiangshouding** [comment]
@heysb 哦，那你这种就是 **字符串** 替换了，FIS暂时没有这样的功能，你可以自己实现一个插件搞定。而且压根也不需要用模板语言；因为语言是需要动态执行的；

**Comment by heysb** [comment]
@xiangshouding 好滴，谢谢大神！
