### ISSUE TITLE
用内置css sprite插件，怎么才能不release旧的图片

### ISSUE THREAD

**Issue by babyzone2004** [fex-team/fis#442]
用sprite合并背景图后，原图已经没有用处，我不想release到发布目录，怎么配置？
如下的配置会出错：
[ERROR] unreleasable file [E:/sprite-test/img/subject.sprite.png] in [/common.css]
```
css:
.nav .nav-subject{
  background-image: url(img/subject.sprite.png?__sprite);
}
.nav .nav-new{
  background-image: url(img/new.sprite.png?__sprite);
}

fis-config.js:

fis.config.set('roadmap.path', [
  {
    reg : '**.css',
    useSprite: true
  },
  {
    reg : '**.sprite.png',
    release : false
  }
]);
```

**Comment by Bul-Kathos** [comment]
这和我的问题类似，打包后的js文件也是一样，旧的文件不需要输出，但是配置release false的话报一样的错误

**Comment by xiangshouding** [comment]
@Bul-Kathos @babyzone2004 产出后的文件。。少看两眼就不纠结这些文件了。之所以这样，也是为了完全性考虑；

**Comment by Bul-Kathos** [comment]
还是有问题吧?  这些文件完全无用 在发布生产环境的时候总不能一起带着就发布了

**Comment by babyzone2004** [comment]
css sprite插件应该提供不保留源文件的配置功能才完美~~

**Comment by xiangshouding** [comment]
@babyzone2004 @Bul-Kathos 

假设有一个图片 A.png 被合并了，那么怎么保证文件没有在其他地方用过呢？如果我做得精确一些，我就得知道每一个文件是否被用过，这个对于纯前端的项目是合适的，但是对于后端模板的项目，就不好办了，因为可能加载的图片是通过动态数据传入的，在静态编译的时候根本就不知道某个图片真的是否被使用；

诚然，你们的这种洁好无可厚非，你们可能觉着在已经被合并的资源不应该被产出，因为文件多了不少，可能有些上线系统还对文件多少变化等还有限制；不过所有的产出图片文件名都是有 md5 戳的，并不会对你的执行系统造成什么危害；

但由于上面说到的原因，暂时无法如此干或者默认提供这样**不合适**的功能；

**Comment by babyzone2004** [comment]
@xiangshouding 所以我才说希望可以提供配置，我理解你的意思，其实这些文件扔到服务器产生不了多少影响，但纯前端项目是有这种需求，并不能说不合适，例如hybrid应用内置的静态文件，当然不希望有无关的文件。 deploy 选项可以过滤一部分，但个人觉得不是很好的解决方案。

**Comment by xiangshouding** [comment]
🐈 √

**Comment by heysb** [comment]
我是这样来解决的，如果是要合并的图片，文件名都带同一个前缀，比如`-spt-`，发布的时候过滤掉这些文件
```
deploy : {
    dest: [
        {
            to: '../dest',
            exclude : [/-spt-(.*).png/i]
        }
    ]
}
```

**Comment by xiangshouding** [comment]
@heysb
