### ISSUE TITLE
fisp amd 

### ISSUE THREAD

**Issue by luzuoquan** [fex-team/fis#446]
js模块加载用的是require.js 在底部也添加了require.jsExtRegExp = /^\/|:\/\/|\?/; 但是在还是会报如下错误：
![image](https://cloud.githubusercontent.com/assets/5476455/7268708/ce591bb2-e8fe-11e4-9af4-c1685d225bb0.png)
fis-conf.js的配置是这样的
![image](https://cloud.githubusercontent.com/assets/5476455/7268750/37ca3a2c-e8ff-11e4-906a-d16cd2d0ecdd.png)
感觉require 还是把admin:static/XXX当作url发出请求了。

**Comment by luzuoquan** [comment]
好吧，项目构建的时候 ，有点混搭，重新看了下demo ，解决了。没有把require.js 当作框架加载进去。。。

**Comment by xiangshouding** [comment]
@luzuoquan 混搭也是一种生活啊；

**Comment by luzuoquan** [comment]
@xiangshouding  哈哈，尽情折腾。。。
