### ISSUE TITLE
源码是用grunt，fis能否"grunt taskName"？

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis#449]
源码是用grunt的。
gruntfile.js里头定义了很多task。我想着，能否直接用grunt现成的任务。  
就是，譬如，我fis release之后，有没有什么"postRelease",里头添加一个grunt插件，然后grunt插件运行gruntfile.js里头定义的任务，譬如"afterRelease"?

**Comment by fouber** [comment]
fis的构建，没有生成中间文件，而且构建过程中把压缩、校验、编译都做完了，grunt结合的话，应该只需要一个cli的task，调用一下fis就完事了吧。。。
