### ISSUE TITLE
fis autoprefixer

### ISSUE THREAD

**Issue by xpurer** [fex-team/fis#450]
fis 有类似 https://github.com/postcss/autoprefixer 这样的插件吗？

**Comment by zhongguofenghao** [comment]
为啥我安装autoprefixer插件会出错。安装命令cnpm install -g fis-postprocessor-autoprefixer，报 [ERROR] unable to load plugin [fis-postprocessor-autoprefixer]

**Comment by xiangshouding** [comment]
#420
