### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by babyzhu** [fex-team/fis#451]
我的页面是gb2312 配置已经写了 fis.config.set('project.charset', 'gbk'); ，fis server start 浏览的时候 是乱码  。但是压缩出来的页面又是正常的。然后我就把is.config.set('project.charset', 'gbk');这句删掉。这时用fis server start 浏览的时候 是正常的。但是压缩出来的页面是乱码。怎么回事啊！！

**Comment by fouber** [comment]
@babyzhu 

html中写了``<meta charset="gbk">``了么？
