### ISSUE TITLE
资源定位能力的问题

### ISSUE THREAD

**Issue by heysb** [fex-team/fis#452]
内置资源定位能力可以分析`img`标签的`src`属性，但使用某些`lazyload`插件时，真实图片路径存放在`data-orgrnal`属性里，如何让这类属性同样拥有资源定位的能力

**Comment by lrn744809337** [comment]
我也碰到这个问题，暂时的解法是 用模板data-orgrnal=<%=XXX%> 然后外部json={XXX:__uri()}

**Comment by xiangshouding** [comment]
@lrn744809337 改成 `data-src`

**Comment by heysb** [comment]
@xiangshouding `data-src`可以解决问题，有什么规律么，还是`data-src`是写死的，如果想自定义一个属性呢

**Comment by xiangshouding** [comment]
@heysb 写死的；暂时无法支持自定义

**Comment by heysb** [comment]
@xiangshouding 了解
