### ISSUE TITLE
一个简单的项目，用less，配置文件如何写？

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis#453]
我编写一个简单项目，目录下就3个文件: fis-conf.js,index.html, index.less。  
我fis-conf.js如下：  
```js
    fis.config.merge({
      modules: {
      parser: {
        less : 'less'
      }
    },
     roadmap : {
      ext : {
        less : 'css'
      }
    }
    });  
```
然后我fis release --cwL,less文件根本没被编译成css啊？同时我已安装fis-parser-less

**Comment by xiangshouding** [comment]
你怎么确定没有被编译的？

**Comment by fouber** [comment]
@PetersonLian 

你应该还是在看源码less有没有被编译成css吧？其实fis不会改动源码文件，而是通过 ``fis relase -d xxx`` 命令，在xxx目录生成编译后的文件，如果你要确认less是否编译成功，应该用这种方式确认。

**Comment by PetersonLian** [comment]
@xiangshouding 是否编译，我的标准是，“是否有css生成”。因为index里头，包含进来的stylesheet是直接取当前目录下的css。例如`<link rel="stylesheet" href="index.css">`。当初就直接看到当前目录没有生成css，就直接来提问了。未试过，直接编写`<link rel="stylesheet" href="index.css">`,其实是有效果的。抱歉。回去试试    
@fouber 如果我没有指定目的地(即未-d)，会生成吗？

**Comment by PetersonLian** [comment]
已测。fis不会有中间文件生成。直接写成`<link rel="stylesheet" href="index.css">`，而源文件是less，是可用的。虽然不会有显式的css文件产生。  
如果要产生文件，应该是采用fouber同学的方法（带上-d参数）（未测）。

**Comment by fouber** [comment]
@PetersonLian 

没有指定-d时，-d的值是``C:\Documents and Settings\{用户名}\Application Data\.fis-tmp\www``，fis release总会有一个发布路径的。
