### ISSUE TITLE
配置roadmap.path中的$&或者$1是何意？如果生成文件需要同匹配到的文件同名则如何写？

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis#454]
如题所述。目前对于配置一块不是很熟悉。    
个人的需求就是less/目录下的文件，都在css/下生成相应对应的css文件。   
目前个人写得如下：    

      roadmap : {
      ext : {
        less : 'css'
      },
      path : [{
        reg : 'less/**.less',
        release : 'css/'
      }]
    }

可以贴个相关文档地址。  个人暂未找到。    
万谢！

**Comment by fouber** [comment]
@PetersonLian 

$1、$2、$3、...、$9 是正则匹配的分组索引，而$&代表了匹配到的整个内容。这是正则的知识，并不是fis特有的，相关阅读可以去看一下js的正则表达式。

release要求是一个完整的路径，所以，你写成 ``release: 'css/'``是不对的，发布后的文件都成了 css 这个名字了，正确的配置应该是 ``release: 'css/$&'``，表示 ``css/`` 后面连接的是reg匹配到的完整路径内容。

比如你有一个工程文件路径是： ``less/a/a.less`` ，而你的reg配置是 ``less/**.less``，那么这个文件被你的reg匹配之后，会 $& 就指代了匹配到的部分，也就是 ``less/a/a.less`` ，然后你的release配置是： ``css/$&`` ，那么这个less/a/a.less文件的最终发布路径将是： ``css/less/a/a.less``

可能你的本意是希望less目录下的文件发布到css目录下，那么你的配置应该是：

```js
...
roadmap: {
    path: [
        {
            reg: /^\/less\/(.*\.less)$/i,
            release: 'css/$1'
        }
    ]
}
...
```

我用正则设置reg，正则中使用括号就可以建立一个分组匹配，这里我把less之后的匹配用括号括起来了，比如工程文件路径还是是： ``less/a/a.less`` ，用正则 ``/^\/less\/(.*\.less)$/i`` 去匹配，得到 ``$&`` 是 ``less/a/a.less``，``$1`` 就是 ``a/a.less`` 了，然后你的release配置是： ``css/$1`` ，那么这个less/a/a.less文件的最终发布路径将是： ``css/a/a.less``

**Comment by hefangshi** [comment]
http://fis.baidu.com/docs/advance/roadmap.html#产出目录

**Comment by PetersonLian** [comment]
@fouber @hefangshi 谢谢
