### ISSUE TITLE
fis release -w 时配置里面的include失效

### ISSUE THREAD

**Issue by GilbertSun** [fex-team/fis#455]
当执行`fis release -w`的时候fis-conf 里的include和exclude是失效的

因为watch的时候触发编译是通过`chokidar`对文件的监控开触发的，所以会带来下面的问题

1. 所以首次触发编译时，项目根目录下的所有文件都会触发`add`行为，这时候，在`chokidar`的ignore里只检测了`project.exclude`和`project.watch.exclude`并没有检测`project.include`，因此会让不属于include规则里的文件也进入了fis处理的流程，表现出来的和文档说明中先进行include检查并在此基础上进行exclude检查不一致

2. 后续对文件的修改进行监控的时候，`chokidar`给`ignore`函数里传入的`path`参数由首次编译时的相对路径变为了文件系统下的绝对路径, 比如原先是`asset/js/a.js`变成了`/tmp/project/asset/js/a.js`,这时候exclude的检测也失效了，因为那些检测条件都是以项目目录为根目录来写的

```javascript
var reg = fis.util.glob('asset/js/**.js'); // => /^\/?asset\/js\/.*\.js$/i
reg.test('asset/js/a.js'); // => true;
reg.test('/tmp/project/asset/js/a.js); // => false;
```

我尝试修复这个问题的时候，发现这并不是一个简单的问题，因为`chokidar`在首次触发编译的时候不仅会传入文件还会传入文件路径上的文件夹

```javascript
// fis-conf里面的include为['asset/js/**.js']

/**
fis-command-release release.js 51行左右
path 会分别传入 asset,asset/js,asset/js/a.js, 只有`asset/js/a.js`符合规则，前面两个不符合，但是当前面的文件夹标记为ignore后，最后对于文件的检测是不触发的
*/
if (fis.config.get('project.include')){
    ignored = ignored ||
        !fis.util.filter(path, fis.config.get('project.watch.include'));
}
```

这个时候`chokidar`会先检测js这个文件夹，这时候并不能匹配上include，也就导致后面检测a.js这个文件的行为不会发生

然而这个问题修复后，可能还会有这样的问题，某个less文件只是用于import，因此我把它加入进了exclude规则里，不希望他进入release流程，但是对他的修改意味着import它的文件是会变得，这些文件需要重新编译

**Comment by hefangshi** [comment]
这里的确存在一个过度引入，目前考虑的解决办法是取消 `project.exclude` 和 `project.include` 对监听文件的影响，只保留 `project.watch.exclude` 。很遗憾，可能依然无法特别满足你的需求。

这样做的主要原因是在监听流程中获取文件夹结构是一个比较耗时的过程，特别是目录层级较多的时候，而就像你描述的，`chokidar` 本身的接口也不支持 include，因为一旦要实现include，就必须要求即使设置了exclude，也要扫描全部文件夹，这样做的结果就是设置了exclude与不设置exclude对最终的监听提升并没有质的提升。

但是简单的不监听 `project.exclude` 的确不是一个好选择，会导致你说的希望监听的include文件没有正确的被处理。所以就像前文所说，权衡利弊的解决方案就是不实现watch的include功能。

另外也不是特别建议使用 `project.include`，除非是比较极端的情况，否则设置了 `project.include` 后会对编译速度产生较大影响。

**Comment by xiangshouding** [comment]
fex-team/fis-command-release@76c5233b1c3888b4e3329ea9d1a4f8a9d5f6671d
fex-team/fis-command-release@eba48813fd81b28b4a82758828fddc31033af0dd

基本思路，一上来第一次不依赖于 chokidar 插件进行全部 add 触发编译而是直接触发编译( project.include 和 project.exclude 起效) 后进行文件更改时会触发 ignored 通过 project.include  和 project.exclude 过滤；

**Comment by xiangshouding** [comment]
修复

**Comment by GilbertSun** [comment]
感谢，请发布一下1.9.26
