### ISSUE TITLE
fis如何自定义amd包装

### ISSUE THREAD

**Issue by aj4g** [fex-team/fis#458]
我的目录结构：
![目录结构](http://git.oschina.net/uploads/images/2015/0429/121451_776b1ae7_331826.jpeg)

components下面的underscore被包装成了：
`define('components/underscore/underscore.js', function(require, exports, module)`

widgets/common/celiing2/view.coffee被包装成了：
`define('source/widgets/common/ceiling2/view.coffee', function(require, exports, module)`

我想自定义包装路径如何做呢？
比如components下面的第三方库是通用的，想变成：
`define('underscore', function(require, exports, module)`

比如widgets目录下的是各种组件，没必要加上`source`，后面的`view.coffee`也多余，想变成：
`define('widgets/common/ceiling2', function(require, exports, module)`

请问如何做？

**Comment by Bul-Kathos** [comment]
@xiangshouding @fouber 有好办法吗？

**Comment by xiangshouding** [comment]
有啊，可以参考https://github.com/fex-team/fis-postprocessor-amd

**Comment by luzuoquan** [comment]
你想自定义moduleId 这样不好，amd规范不建议这样。

**Comment by xiangshouding** [comment]
@luzuoquan :kiss:

**Comment by xiangshouding** [comment]
@luzuoquan 

其实加 moduleId 是为了合并的需要。那么我们对 AMD 可以通过以下方式使用；

1. 用户开发，设定组件目录，下面的所有组件都不可自己写 `define`，由工具编译添加。
2. 如果对于需要分享出去的组件，可以写没有 moduleId 的 `define`
3. 使用第三方 AMD 组件，只要运行时 loader 支持就行

- 为什么需要加 moduleId ？

    合并的需要

- 为什么有 1 这样的一个开发方式而不是要求用户去写？

    要满足合并的需要，还是要加 moduleId 的，那么对于已经添加 define 的组件，编译工具需要 AST 分析，耗时大概是正则的 6-7 倍，这是一件很蛋碎的事情。

- 如果没有第 3 条，那么实现一个简单的 loader 就可以了，只需要把异步组件的静态资源映射表输出到页面，供 loader 查询。这样的好处是，整个 loader 很简短 ，大概 200 行内就能搞定了，不再需要加载一个偌大的 2k 左右的包到页面上。

所以，开发自己项目就用 commonjs 规范，后包装成 AMD 还是 UMD 还是 XMD 就由项目本身去做取舍吧。

**Comment by luzuoquan** [comment]
@xiangshouding  学习了, thk。那个AST分析是指什么

**Comment by xiangshouding** [comment]
@luzuoquan 

![snip20150430_24](https://cloud.githubusercontent.com/assets/631195/7406614/af32acb8-ef38-11e4-82a1-4b2d79fcca5f.png)

**Comment by aj4g** [comment]
@luzuoquan @xiangshouding 
规范这件事我觉得各项目实际需求不同吧
我这个项目把所有js都打到一个包里了，页面是由各种组件组合而成，根据组件里定义的data-xxxpath来决定加载哪个js模块

看到@xiangshouding回答之前稍微改了下jswrapper，变成这样了：
``` javascript
fis.config.merge({
    settings : {
        postprocessor : {
            'nef-wrapper' : {
                pathToId: {
                    cutPrefix: /^(components\/|source\/)/i,
                    cutSuffix: /\/([^/]*)$/i
                },
                type : 'amd'
            }
        }
    }
});
```

http://git.oschina.net/aj4g/fis-postprocessor-nef-wrapper
