### ISSUE TITLE
fis release --watch 可以指定排除目录跟文件吗

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#460]
我的初衷其实是想用**fis跟compass结合**，因为项目的样式是用compass写的，苦于一直没找到合适的方式，所以就想还是用compass来编译监听.scss文件变化生成css,用fis来完成其他的工作。
另外我计划把release的目录(output)也放在工程根目录下，这样便于多个工程的独立性，这样其实也没必要去监听output目录下的文件变化。

**Comment by xiangshouding** [comment]
@fancyboynet compass 结合啊，看这里 https://www.npmjs.com/package/fis-parser-compass

这个插件一装就能玩了。

**Comment by fancyboynet** [comment]
@xiangshouding 谢谢，不过看issues好像不是很稳定啊，靠谱么。。。

**Comment by xiangshouding** [comment]
你试试，不靠谱再讨论讨论。

**Comment by fancyboynet** [comment]
嗯，不过装不起来。。。报错了。。。
