### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by maoguiyou** [fex-team/fis#461]
[ERROR] optimizer.uglify-js: Unexpected character '#' [D:/Tpl/bug/node_modu
fis/node_modules/fis-command-install/node_modules/findup/bin/findup.js:1:0]

**Comment by xiangshouding** [comment]
为什么你要把 fis 安装到自己的项目目录下?

可以用这个方法排除掉对 node_modules 的扫描

```js
fis.config.set('project.exclude', 'node_modules/**');
```

**Comment by maoguiyou** [comment]
谢谢，这个已经解决了
