### ISSUE TITLE
[FAQ]/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by lyongde** [fex-team/fis#462]
Windows8.1环境下，使用Git Bash，nodejs安装在d:/nodejs下，项目存放路径d:/nodejs/project。
在d:/node下fiis -v正常，但是到d:/node/project fis -v 会出现/bin/env: node: No such file or directory。
Git Bash下，echo $PATH，环境变量已经指向/d/nodejs/node_modules:/d/nodejs/node_modules/fis/bin

**Comment by xiangshouding** [comment]
@lyongde 解决了还是咋滴？
