### ISSUE TITLE
fis server start 打开的是本机ip开头的页面

### ISSUE THREAD

**Issue by huixisheng** [fex-team/fis#468]
运行

    fis server start 

在浏览器打开的能否是 `192.168.*.*` 开头的页面。这样方便局域网的手机上调试页面。
跟代码发现是直接写成:
>   _.open('http://127.0.0.1' + (opt.port == 80 ? '/' : ':' + opt.port + '/'), function(){
     process.exit();
 });

另外是否可以对每个页面添加一个二维码。或者以上都可以添加命令行配置达到效果

**Comment by xiangshouding** [comment]
@huixisheng 

这个只是打开浏览器的意思；你依然可以用你自己的 IP 去访问页面，不影响；

**Comment by fouber** [comment]
@huixisheng 

工具给添加二维码。。。这不是会污染页面结构么

**Comment by huixisheng** [comment]
@xiangshouding 确实可以改成的自己的ip去访问，就是现在在做手机网页直接复制浏览器打开的链接发给手机就好。而不是要先改`127.0.0.1`-> 自己ip  

@xiangshouding  @fouber 二维码这个需求，如果发现有点不合理，不是大众需求。如果自己确实需要，可以写个插件支持。

谢谢楼上
