### ISSUE TITLE
产出文件的问题，求帮忙

### ISSUE THREAD

**Issue by hxqbeyond** [fex-team/fis#469]
假设我有个文件a.js
希望产出a.js、a.min.js，即同时产出两个文件，有什么方法可以做到吗./
由于roadmap里面相同配置会以最后的为准，所以这样写是无效的。
![image](https://cloud.githubusercontent.com/assets/10892272/7531640/a8ab6d32-f58f-11e4-9590-038093cdf721.png)

**Comment by xiangshouding** [comment]
fis 处理后都可以认为是压缩的（上线情况下），而这个过程是通过是否加 `-o` 参数来区别的，开发是不加 `-o` 而发布上线加。
