### ISSUE TITLE
为什么输出后，资源的路径变错了？

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis#473]
原本是这样的：href="css/normalize.css"
输出后是这样的：href="/css/normalize.css"
居然在css前面加多一个/，导致链接的资源全部都不是相对路径，，这样是大BUG么？要怎么解决啊！

**Comment by xiangshouding** [comment]
这不是个 Bug；

可能你无法接受这一点，因为为啥编译完了以后双击文件浏览器打开无法访问了，简直就是晴天霹雳。

不过为什么会是这样，让我详细给你道来；

其实你想，总有那么一些人说 FIS 难用啊什么的，如果就如你想的提供些许压缩功能那么就没必要把一个东西做得如此繁杂，对是繁杂；

FIS 是成体系的前端工程构建工具，把么对于一个前端工程除了人文工程的模块划分、组件拆分以外，多多少少还需要为各种运行时性能着想。

那么首当其冲的就是要合并静态资源，因为从各种实践检验来看，合并资源是让整个页面加载快起来的一种途径；

那么就单单这个合并上，举个栗子

```
/css/a.css
/css/b/b.css
/css/img/1.png
```
```css
/*a.css*/
.img {
  background-image: url('./img/1.png');
}
```

假设我把 a.css, b.css 合并如文件 pkg.css

```
/pkg.css
/css/a.css
/css/b/b.css
/css/img/1.png
```

注意，合并的文件没有放到 `css` 目录下，而是**挪到**了上一层目录，这时候假设 url 没有发生变化的时候（不更改），发现找不到了，因为跟 `pkg.css` 同目录下没有一个 **img** 目录；

当然你会说，把合并的资源放到 `/css` 目录下不就行了？但是，这样岂不是开发人员时时需要关心资源的按放目录路径以及被合并文件的路径；这个事情很容易出现错误；

那么解决办法就是相对于一个目录来计算路径，而 FIS 就是选择了 `/` 来做参考，在开发时它指代的是相对于 FIS 项目的 ROOT，当发布到线上以后它指代的是 Web Server 的 **document_root**。

那么可能你会疑问工具都给我改了，我如何调试？

FIS 自带一个 server 来做这个事情；

执行以下命令，发布到自带 server 的 root 目录下；

```
fis release
```

用 `http://127.0.0.1:8080/some.html` 访问你要调试的页面；
> 服务启动时可能设置其他端口号，此处启动时监听 8080 端口。

以上是合并促使我们必须要去做 URL 变更，还有其他一些地方要求必须改变 URL 相对于统一的一个目录，就不详述了~

**Comment by ioriandy4** [comment]
可以在输出的时候给个参数，可以控制用相对路径吗？由用户自己选择，有这样的参数吗？

**Comment by xiangshouding** [comment]
@ioriandy4 暂时没有，后续计划提供一个；

**Comment by ioriandy4** [comment]
fis.config.merge({
    roadmap : {
        path :{
            useStandard:false
        }

    }
});

我用这个配置，关不掉绝对路径，请问怎么通过配置关掉呢，谢谢

**Comment by xiangshouding** [comment]
```js
fis.config.set('roadmap.path', [{
  reg: '**',
  useStandard: false
}]);
```

**Comment by ioriandy4** [comment]
加入了这个，资源可以合并压缩，但是html里面的链接路径却不可以自动变换链接到合并后的资源了，请问怎么配置呢？

**Comment by xiangshouding** [comment]
参考我上面回复的！

**Comment by xiangshouding** [comment]
#86
