### ISSUE TITLE
为什么fis卸载不掉

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis#475]
我卸载了nodejs，然后把安装目录清空了，把原来C盘的fis-tmp也删了，重新安装nodejs，输入fis server start，居然还是可以执行，，，请问fis怎么卸载呢？想重新装一次啊。

**Comment by xiangshouding** [comment]
重新装只需要

```
npm install -g fis
```

执行就行了

**Comment by xiangshouding** [comment]
卸载的时候需要把 NPM 相关的删掉；大概在你的磁盘的 %appdata% 目录下，我好久没用 windows 了，记不大清楚了。
