### ISSUE TITLE
希望fis能够加入几条类似于C语言的预编译指令

### ISSUE THREAD

**Issue by lixi520** [fex-team/fis#477]
例如__lineno 扩展为当前行号。
__file__ 扩展为当前问精明
__methodname__扩展为方法名，若无方法名，生成随机字符串。

**Comment by hefangshi** [comment]
这类需求你可以自己通过实现preprocessor插件轻松实现。

**Comment by lixi520** [comment]
hello, 插件已经实现，可以试用一下哦：
https://github.com/lixi520/fis-preprocessor-c-style-macro

**Comment by hefangshi** [comment]
:+1: 写的非常赞！厉害！
