### ISSUE TITLE
为什么用fis release -w -l  ，修改文件后浏览器不会自动刷新

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis#478]
为什么用fis release -w -l  ，修改文件后浏览器不会自动刷新，增量编译是编译了，，但是没有自动刷新，换了谷歌浏览器，还是这样，，，是不是还要装什么插件？？

**Comment by ioriandy4** [comment]
经查阅，是浏览器无法注入livereload.js，FAQ的方法都试过了，不行，不知道怎么解决

**Comment by fouber** [comment]
@ioriandy4 

是写错命令了，自动刷新的参数是 ``-L`` 你写成了 ``-l``，大小写有区别的
