### ISSUE TITLE
发布到服务器的时候，没有发布文件夹？

### ISSUE THREAD

**Issue by lys623** [fex-team/fis#484]
发布到服务器的时候，为什么只发送了static下一级的js文件，服务器也接受到了这个js，而下一级的文件夹没有上传？

            {
                //将static目录上传到/home/fis/www/webroot下
                //上传文件路径为/home/fis/www/webroot/static/xxxx
                receiver : 'http://www.example.com/path/to/receiver.php',
                from : '/static',
                to : '/home/fis/www/webroot'
            },

receiver.php为https://github.com/fex-team/fis-command-release/blob/master/tools/receiver.php

**Comment by xiangshouding** [comment]
```
fis release -d output
```
看看 output 里面产出的结果和预期是否相符，后再判断是否是上传的问题；

**Comment by lys623** [comment]
噢，这个估计是产出问题。又发现个问题，上传过程中某个文件上传失败是什么原因？
![image](https://cloud.githubusercontent.com/assets/4364314/7609991/8601241e-f9ab-11e4-92ac-d4cce7a5538f.png)

**Comment by xiangshouding** [comment]
报 **500** 错误，看看你服务器的  error.log ，看那块报错了？

**Comment by lys623** [comment]
2015/05/13 22:01:18 [crit] 25018#0: *1411 open() "/var/lib/nginx/tmp/client_body/0000000035" failed (13: Permission denied),报了这个错

**Comment by xiangshouding** [comment]
@lys623 权限问题，运行 php 的程序的用户名和组是否能读取 /var/lib/nginx/tmp 需要看一下具体是否在同一个组里以及权限是否有；这块可以用 ls -l 来看看这个文件的权限，然后再查看 nginx 配置文件看看是以哪个用户执行的 php 脚本。

**Comment by lys623** [comment]
噢，完了，这块不熟，估计都乱了

**Comment by lys623** [comment]
为什么某些可以上传，某些上传不了

**Comment by lys623** [comment]
执行：
进到/var/lib目录下查看nginx目录的权限：
drwx------  3 apache  apache  4096 Apr  4 00:30 nginx

执行命令：
chmod -R 775 nginx

ok了，谢了
