### ISSUE TITLE
插件开发可以支持一下异步Promise吗？

### ISSUE THREAD

**Issue by WuChu** [fex-team/fis#486]
插件开发可以支持一下异步Promise吗？
现在很多IO操作都是异步写法, Like this ...

	var browserify = require('browserify');
	var Promise = require('q').Promise;

	module.exports = function(content, file, conf) {
		return new Promise(function(resolve, reject, notify) {
			var b = browserify(file);
			b.bundle(function(err, buf) {
				if (err) {
					reject(err);
				}
				resolve(buf.toString());
			});
		});
	};

**Comment by xiangshouding** [comment]
FIS 插件不支持异步的写法，必须是同步的；所以不支持这种写法

**Comment by WuChu** [comment]
browserify这种模块貌似只能异步，集成是个问题，有没有其它的替代方案？难道只能改fis源码了......

**Comment by WuChu** [comment]
算了，为了把Browserify集成进Fis，特意把NodeJs升级到0.12，然后起了一个同步子进程来进行这个TASK。。。你们后续真该考虑支持一下异步编程的方案。

**Comment by xiangshouding** [comment]
@WuChu 感谢你的支持，异步这块的支持正在讨论，有结果会在后续版本中体现。

**Comment by WuChu** [comment]
期待ing...

**Comment by fouber** [comment]
@WuChu 

工程化构建工具的设计比较难像流程工具那样设计成异步的形式，异步处理的前提是task之间是独立的操作序列，这在工程构建工具中使用起来非常别扭。

举个例子，fis的内嵌功能：

```js
var img = __inline('a.png');
var css = __inline('a.css');
var scss = __inline('a.scss');
var tpl = __inline('a.html');
```

* __inline一个图片的过程是：
    1. 读取图片内容
    2. 压缩图片
    3. base64嵌入
* __inline一个css的过程：
    1. 读取css内容
    2. 压缩css
    3. 把压缩后的css内容转成js字符串嵌入
* __inline一个scss的过程：
    1. 读取scss内容
    2. 调用sass插件编译成css
    3. 压缩css
    4. 把压缩后的css内容转成js字符串嵌入
* __inline一个html的过程与css类似，但要口出html中的script、style标签中的js、css内容做对应的js、css处理。

以上例子暗示了inline过程是one-task的，就是当你处理一个js的时候，遇到内嵌，要停止在当前处理的位置，完整编译要内嵌的文件之后得到内容再插入，这是一个“递归编译”的过程，所以fis在一次编译中就完成了对所有文件的处理，不像流程构建工具（grunt/gulp）那样是分task的

**Comment by WuChu** [comment]
是的，遇到递归式的细节处理，如果使用nodejs的回调处理就会像代码的“诅咒金字塔”一样，一层嵌入一层；
但是整体抽象感觉fis是有流程可言的，比如我们在某个预处理阶段，不做任何引用或者内联（要做也是暴露出接口），而是对每个独立的文件做预处理，待预处理完阶段成之后，针对预处理完成的产出，进行fis自己的parse产出结果，这两者实际感觉是可以分离的。个人感觉preprocessor就是这么一个非递归式的，仅仅只针对文件个体做操作的阶段。

**Comment by hefangshi** [comment]
@WuChu 可以参考一下http://fex.baidu.com/blog/2015/01/fis-muffin/

**Comment by WuChu** [comment]
@hefangshi 
这个做法比较巧妙：https://github.com/zyeeda/fis-muffin/blob/master/muffin.js#-194-197
单页面应用的话会比较好，但是多页面的话，可能要自己重新封装fis了。

**Comment by hefangshi** [comment]
@WuChu 这个和单页面应该还是多页面应用没太大的关系。

**Comment by WuChu** [comment]
@hefangshi 
我指的fis-muffin

**Comment by hefangshi** [comment]
@WuChu 没有细看fis-muffin，不过你是如何判断的只能支持单页面？直觉上认为不需要。

**Comment by WuChu** [comment]
fis-muffin 应该是_app.js单入口的配置

	module.exports = {
	    settings: {
	        browserify: {
	            main: 'index.coffee',  // 入口文件
	            output: '_app.js',  // browserify 输出文件，不建议修改
	            transform: 'coffee-reactify', // browserify 插件，可支持数组
	            extension: '.coffee' // browserify 所要处理的文件
	        }
	    }
	}

fis-muffin  直接拿来做我这边的项目迁移不太好，不过它的源码值得借鉴一下

**Comment by hefangshi** [comment]
看这里就应该了解了，不过看起来似乎很容易改造成支持多页面的。

**Comment by WuChu** [comment]
是的，但是我想写成插件集成到fis，而不是封装fis ......
