### ISSUE TITLE
使用 prue不能合并CSS资源，会出错

### ISSUE THREAD

**Issue by ioriandy4** [fex-team/fis#490]
使用 prue release -pd ./dist ,可以合并js，但是不能合并CSS资源，会出错，在conf.js,已经配置了
···js
fis.config.set('modules.postpackager', 'simple');
fis.config.set('settings.postpackager.simple.autoCombine', true);
```
但是合并后CSS在HTML里面不见了。。。。

**Comment by hefangshi** [comment]
提到fis-pure的issue里面吧
