### ISSUE TITLE
pure release -op发布后的文件夹中多出来一个map_d1546d7.js的js文件

### ISSUE THREAD

**Issue by penglijuan** [fex-team/fis#491]
pure release -op发布后的文件夹中多出来一个map_d1546d7.js的js文件，
而且在页面里面自动添加了引用
![qq 20150515162134](https://cloud.githubusercontent.com/assets/12264876/7649337/9e39b874-fb1e-11e4-8dba-0ec3e2debea0.png)
![qq 20150515162222](https://cloud.githubusercontent.com/assets/12264876/7649338/a2f7abe6-fb1e-11e4-80c3-2aa25f5df88e.png)

但是用官网的fis-pure-demo发布之后 没有这个map.js文件的产生

**Comment by xiangshouding** [comment]
嗯，这是一张异步资源映射表，当

```js
require.async('x');
```

接口调用的时候，找到 `x` 的具体 url；
