### ISSUE TITLE
ext的设置对parser和html中url的转换都无效。

### ISSUE THREAD

**Issue by snadn** [fex-team/fis#492]
设置 `ext : {jsx: 'js'}` 和 `modules: {parser: { js: 'babelcore'} }` 后。.jsx文件并不会调用babelcore进行parser，需添加`modules: {parser: { jsx: 'babelcore'} }` 后才有效。
同时html中url写成.js的引用也无法应用到文件，需写成.jsx的才行。

希望能够支持上面的用法。

**Comment by xiangshouding** [comment]
fis 里面的配置都是围绕源码路径的，使用也是，需要写源码后缀，而不是将要产出后的后缀。

so，你为啥有这个需求？

**Comment by snadn** [comment]
因为我期望未经fis编译的项目也是可以访问的！而编译仅仅是优化！

**Comment by xiangshouding** [comment]
从这么几个方面来考虑

- 编译本身是否影响到你？
- 你做的这些优化用其他工具搞定会是一个什么样子？

fis 的适用场景必须要做编译的，而编译本身对于开发几乎是没有多大影响的，因为可以开启 watch 监控文件变化进行编译；

开发是也做编译的另外一个好处是，开发 & 上线是经过几乎同样的步骤，这样也减少了由于环境不一致导致的诸多问题；

**Comment by snadn** [comment]
watch 监控 的延时还是比较大的。而通过ext来做适当的增强我认为也是说得过去的。
