### ISSUE TITLE
fis-parse-sass安装报错

### ISSUE THREAD

**Issue by littleweb** [fex-team/fis#495]
CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cpp: In function ‘Sass_Import** sass_importer2(const char*, const char*, void*)’:
../src/binding.cpp:27: warning: null argument where non-null required (argument 1)
../src/binding.cpp:28: warning: null argument where non-null required (argument 1)
../src/binding.cpp: In function ‘void GetStats(v8::Handle<v8::Object>, Sass_Context*)’:
../src/binding.cpp:95: error: ‘nullptr’ was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/rong/node_modules/fis-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-5-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/rong/node_modules/fis-sass
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
Build failed
npm WARN optional dep failed, continuing fsevents@0.3.6

系统环境：
python2.7
node-gpy9

**Comment by xiangshouding** [comment]
Linux 下环境比较复杂，可能需要通过源码编译安装，具体请移步 [fex-team/fis-parser-sass](/fex-team/fis-parser-sass)
