### ISSUE TITLE
关于jsp项目资源<base path="<%=basePath %>">静态资源起止路径fis不能定位

### ISSUE THREAD

**Issue by badman200** [fex-team/fis#496]
jsp头部设置了base path="<%=basePath %>"
项目引用是绝对路径 有什么的解决方法啊，求大神告知

**Comment by fouber** [comment]
用了fis之后，fis自动处理所有资源定位，不需要这种定位方式

**Comment by badman200** [comment]
只能用相对路径吗

**Comment by fouber** [comment]
@badman200 

使用相对路径开发，然后fis会帮你转成绝对路径，所有资源定位都转成绝对路径。

如果fis自动转的绝对路径跟你们的项目访问路径不一致，可以通过配置fis调整文件的发布路径或者文件的url属性实现url统一，这样就match你们的架构了

**Comment by badman200** [comment]
相对于项目根目录的绝对路径可以解析吗

**Comment by fouber** [comment]
@badman200 

经fis构建之后，相对路径都会变成绝对路径

**Comment by badman200** [comment]
可以加你QQ聊下吗 你加我也行785643439
