### ISSUE TITLE
尝试在windows环境下，离线安装fis不成功

### ISSUE THREAD

**Issue by libofei2004** [fex-team/fis#497]
由于环境限制，最终要安装fis的环境无法连外网，所以必须离线安装。
我尝试在windows 7下离线安装fis：
先安装了nodejs，
然后按https://github.com/fex-team/fis/issues/395 的说明，下载的fis@1.9.8.npmbox包，
然后按https://github.com/arei/npmbox 的安装说明，生成了npmbox.npmbox ，解压生成 .npmbox.cache，
再执行这个命令
npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --shrinkwrap false npmbox
执行完后有如下提示：
![1](https://cloud.githubusercontent.com/assets/10001548/7682654/3ae44074-fdac-11e4-801a-387ceb66739b.PNG)
然后我运行npmunbox fis@1.9.8，得到这样的提示，应该是有错误
![a](https://cloud.githubusercontent.com/assets/10001548/7683188/f4d2d34e-fdaf-11e4-994c-3a7898fa02bd.png)
尝试运行fis -v也找不到命令。
 错在哪里，还望赐教！

**Comment by fouber** [comment]
@libofei2004 

1. 找一台可以联网的，跟你这个windows一样系统版本，一样CPU位数的机器，在这台机器上安装fis：

    ```bash
    npm install -g fis
    ```

1. 在这台机器上执行命令：

    ```bash
    npm config get prefix
    ````

    这个命令会显示npm install -g的安装路径，一般是：

    ```bash
    C:\Documents and Settings\{你的用户名}\Application Data\npm
    ```

1. 打开这个目录，复制里面的 ``fis.cmd`` 文件和同级的 ``node_modules/fis`` 目录到你的U盘
1. 来到你这个不能联网的windows电脑上
1. 在这台电脑上执行命令：

    ```bash
    npm config get prefix
    ```
    看看这台电脑上，npm install -g 会安装到哪里
1. 复制上一步骤的路径，打开
1. 把你U盘里的 ``fis.cmd`` 文件拷贝到这个目录下，把你的 ``node_modules/fis`` 目录也拷贝过来，跟你在之前那个电脑上安装的路径和位置关系一样一样的
1. 执行 fis -v，看看能不能找到fis命令，如果不能，就把上上步复制的这个路径添加到系统的环境变量PATH中，然后重启电脑


其实npm安装无非就是这么一个过程，只是它用的是程序下载，上面这些步骤是人肉拷贝，一点也不难吧。。。

**Comment by libofei2004** [comment]
多谢，我试试。现在由于没法保证安装fis的系统版本和最终部署的完全一致，只能先试试看了。


在 2015-05-18 23:37:35，"张云龙" <notifications@github.com> 写道：


@libofei2004

找一台可以联网的，跟你这个windows一样系统版本，一样CPU位数的机器，在这台机器上安装fis：

npm install -g fis

在这台机器上执行命令：

npm config get prefix

这个命令会显示npm install -g的安装路径，一般是：

C:\Documents and Settings\{你的用户名}\Application Data\npm

打开这个目录，复制里面的 fis.cmd 文件和同级的 node_modules/fis 目录到你的U盘

来到你这个不能联网的windows电脑上

在这台电脑上执行命令：

npm config get prefix

看看这台电脑上，npm install -g 会安装到哪里

复制上一步骤的路径，打开
把你U盘里的 fis.cmd 文件拷贝到这个目录下，把你的 node_modules/fis 目录也拷贝过来，跟你在之前那个电脑上安装的路径和位置关系一样一样的
执行 fis -v，看看能不能找到fis命令，如果不能，就把上上步复制的这个路径添加到系统的环境变量PATH中，然后重启电脑

其实npm安装无非就是这么一个过程，只是它用的是程序下载，上面这些步骤是人肉拷贝，一点也不难吧。。。
