### ISSUE TITLE
有没有直接在当前文件夹生成默认fis-conf.js的命令？

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#498]
场景：想在某个文件夹比如一个temp目录下运行某个页面看效果，不需要任何其他demo项目的文件，只希望可以用上fis强大的本地开发环境

**Comment by fancyboynet** [comment]
其实用fis server是好的，不过在用fis release的时候会提醒没有fis-conf.js的配置文件，所以才有这个疑问，如果可以有个命令生成一个默认的最简单的配置文件，是不是更好点呢？

**Comment by xiangshouding** [comment]
创建一个空文件就 OK 了，名字叫 fis-conf.js

**Comment by fancyboynet** [comment]
嗯，我现在就是这样做的，只是如果fis-conf.js对配置有要求，自己加个命令是不是更好点，另外，既然空的fis-conf.js也可以release，那为什么还需要这个文件？

**Comment by xiangshouding** [comment]
创建一个空文件的成本远远比学一条命令的成本低，而且报的是 warn 完全可以不关心；

之所以提示一个 warn 是因为引入更多扩展功能；

**Comment by fancyboynet** [comment]
对哦，没注意看是warn...多谢解答
