### ISSUE TITLE
如何在CSS中合并图片之后再inline到html

### ISSUE THREAD

**Issue by masterkong** [fex-team/fis#502]
想先把css中的__sprite的图片先进行合并，再把相应的css文件__inline到html中，请问要如何做？目前尝试发现好像只能是先inline再sprite。

**Comment by xiangshouding** [comment]
[CssSprites 配置](/fex-team/fis-spriter-csssprites#配置) 第三条，这样配置；

```js
fis.config.set('roadmap.path', [{
    reg: /\/static\/.*\.css$/i, //某一个想合并图片的文件
    //配置useSprite表示reg匹配到的css需要进行图片合并
    useSprite: true
}].concat(fis.config.get('roadmap.path', [])));
```
编译加 `-p`

**Comment by masterkong** [comment]
@xiangshouding 可能我意思没有表达清楚。
1.有一个index.html想inline一个css
<link rel="stylesheet" type="text/css" href="css/style.css?__inline" />
2.  style.css中又有图片需要合并
.category .item a.icon2 { background-image:url("img/1.jpg?__sprite"); }
.category .item a.icon3 { background-image:url("img/2.jpg?__sprite"); }

想要的处理顺序是先完成第2个，再完成第1个。

现在的处理顺序先完成第1个，再完成第2个，发现index.html中inline的是原来的style.css，并不是合并图片后生成的syle.css。
fis-config.js的内容:
fis.config.set('roadmap.path', [{
    reg:  'css/style.css',    
    useSprite: true
}].concat(fis.config.get('roadmap.path', [])));

另外也是想知道fis对于"inline内容嵌入"有办法控制在整个工程release中的处理顺序吗？
谢谢！

**Comment by woshi82** [comment]
我也遇到了想同的问题，

> 1、在head标签里面`<link rel="stylesheet" type="text/css" href="./xx.scss?__inline">`

> 2、scss中图片用了`?__sprite`

>3、 产出之后 `background: url(public/images/1.jpg?__sprite);`，并不是预想的`background: url(public/images/xx_z.png);`

问题：   inline操作到底是在哪个阶段呀，感觉特别不好控制
