### ISSUE TITLE
在html中引用工程目录外的js文件，会出现<script src="undefined"></script>

### ISSUE THREAD

**Issue by richard-chen-1985** [fex-team/fis#503]
因为我和同事用不同的工具，我使用FIS做网页构建，同事用bower做依赖管理，于是在FIS工程目录外会有一个bower_components目录，需要我在html里面引用，于是有了<code>
&lt;script src="../bower_components/xxx"&gt;&lt;/script&gt;
</code>的引用，当我fis release过后，这段代码居然变成了<code>
&lt;script src="undefined"&gt;&lt;/script&gt;</code>，相反，没有经过bower install的组件引用确没做任何更改。

当然去引用FIS工程外部的文件属于特殊情况，但我希望的是不要替换成<code>&lt;script src="undefined"&gt;&lt;/script&gt;</code>，这样的话，我输出的代码，同事就没办法用，所以，如果能解决这个需求，我将万分感谢。

**Comment by xiangshouding** [comment]
已复现，标记为 bug
