### ISSUE TITLE
fis有没有sourcemap的插件？

### ISSUE THREAD

**Issue by livisky** [fex-team/fis#511]
请问fis有没有支持js sourcemap的插件？没有的话，该怎么配置才能支持？

**Comment by livisky** [comment]
fis.config.set('settings.optimizer.uglify-js', {
    mangle: {
        except: 'exports, module, require, define'
    },
    output : {
        sourceMap:true
    }
});
我配置成这样，压缩时老是提示：
[ERROR] optimizer.uglify-js: `sourceMap` is not a supported option [E:/fis+sea2/node_modules/fis-postpackager-seajs/index.js]

请教这样配置对吗

**Comment by livisky** [comment]
怎么没人回答了，唉！

**Comment by xiangshouding** [comment]
应该现在的 uglifyjs 的插件是没有派生出 resourceMap 的

其实为啥你觉着这么重要的一个功能 FIS 里面居然没有，FIS 那么多人开发难道没有这个需求吗？

我想你心里面有这样的疑惑，其实是这样的，因为在 FIS 里面很方便切换压缩状态和非压缩状态，很方便切换合并状态和非合并状态；整个过程我不需要太大的力气就能方便的调试；

**Comment by livisky** [comment]
很多时候fis只作为压缩用的，配置好目录，然后压缩发布到开发目录，等开发完成再上传到线上。然后php那边引用的是js压缩的目录，这时候想要调试就难了。建议fis还是能以大众、包容的思维做大做强，发现出了问题，百度一搜很少有资料或教程。只有来这问您。fis一整套闭环的开发发布模式不一定适合别的公司，如能灵活配置多种方案，那就好了。一条命令就能快速压缩和发布确实挺赞。

**Comment by xiangshouding** [comment]
@livisky 我上面说了，这个插件并没有提供 resourceMap 的产出功能，但不代表不能用插件让它产出，所以这个跟 fis 本身以及大公司小公司只压缩还是什么没啥关系；

另外说到包容，试问什么是包容？难道我什么东西都提供好了让你用就叫包容吗，fis 本身已经开源，并且有插件扩展机制，如果不满足大可以实现一个插件搞定需求；那么这个跟包容有啥关系。

我上面只是提到我们为什么不要 resourceMap 的原因而已，为啥就激起了你的气愤？是我用得不对还是回答的生硬？

**Comment by livisky** [comment]
老兄，我没有气愤的。我只是说了一些看法，可能说的不对。

我还是想把fis用起来，到各个项目中，并且长久用下去。

目前我还有两个问题没有解决。如能指点解决方案，感激不尽。想写插件，有心无力。

1、sourcemap问题

2、模块目录下的js全部合并压缩问题。（business目录下的各个模块里的js代码能合并压缩成一个文件）

src/js/business
                       ---cart下有
                                  --------cart.js
                                  --------cart_coupon.js
                                  --------checkout.js
                      ----lottery下有
                                  --------main.js
                                  --------renderTurnTable.js

**Comment by xiangshouding** [comment]
嗯，那么这个讨论过程可以继续了；

#### sourceMap
sourceMap 这块需要修改 fis-optimizer-uglify-js 来实现，optimizer 阶段是单文件编译阶段，所以如果书写插件派生别的文件需要一些 hack 的方法；当然也未尝不可以（特殊情况下）弄一个压缩的插件，在 postpackager 阶段做这个事情，关于插件扩展点请看 https://github.com/fex-team/fis/wiki/%E6%8F%92%E4%BB%B6%E6%89%A9%E5%B1%95%E7%82%B9%E5%88%97%E8%A1%A8 有详细的例子

那么可能问题要回归到插件如何写，这个事情其实也不是特别难，文档有写，有些人说文档写得太简单，确实简单，就像插件写起来也很简单一样；

```js
fis.config.set('modules.postpackager', [
    function (ret, conf, settings, opt) {
        // ret.map  map.json 内容对象
        // ret.src  源码列表
        // ret.ids  ids 对应文件列表
        // ret.pkg 合并的信息
        console.log(ret.map);
    }
]); 
```
你可以把上面这段代码放到 `fis-conf.js` 里面即可；

##### 关于这个合并

```js
fis.config.set('pack', {
  'cart.js': ['cart/**.js'],
  'lottery.js': ['lottery/**.js']
});
```

当 release 加 `-p` 参数后，会在你写的插件的 `ret.pkg` 里面拿到合并文件的 File 对象 ([fis.file](/fex-team/fis-kernel/blob/master/lib/file.js))，然后这时候你可以对它做压缩或者其他什么操作（包括生成 sourceMap ）。

**Comment by livisky** [comment]
大神，我看https://github.com/fex-team/fis-optimizer-uglify-js/blob/master/index.js
这个文件中有对sourceMap的配置的代码，这个插件配置一下不能用吗？

module.exports = function(content, file, conf){
    conf.fromString = true;

    if (conf.sourceMap) {
        var mapping = fis.file.wrap(file.dirname + '/' + file.filename + '.map');
        conf.outSourceMap = file.filename + '.org' + file.rExt;
    }

    var ret = UglifyJS.minify(content, conf);

    if (conf.sourceMap) {
        mapping.useDomain = true;
        mapping.useHash = true;

        var mapData = JSON.parse(ret.map);

        mapData.sources = [mapData.file];
        mapData.sourcesContent = [content];

        var newData = {
            version: mapData.version,
            file: mapData.file,
            sources: mapData.sources,
            sourcesContent: mapData.sourcesContent,
            names: mapData.names,
            mappings: mapData.mappings
        };

        mapping.setContent(JSON.stringify(newData));

        file.extras = file.extras || {};
        file.extras.derived = file.extras.derived || [];
        file.extras.derived.push(mapping);

        ret.code += '\n//# sourceMappingURL=' + mapping.getUrl(fis.compile.settings.hash, fis.compile.settings.domain); + '\n';
    }


    return ret.code;
};



你给的提示，我只能做到这一步。。。

fis.config.set('modules.postpackager', [
    function (ret, conf, settings, opt) {
        // ret.map  map.json 内容对象
        // ret.src  源码列表
        // ret.ids  ids 对应文件列表
        // ret.pkg 合并的信息
        //console.log(ret.src);
        fis.util.map(ret.src, function(subpath, file) {
                 if (file.isJsLike) {
                    var content = file.getContent();
                    if(/js\/business\//.test(file.getId())){
                        var content = file.getContent();
                        content += '//@ sourceMappingURL='+file.getId()+'.js.map';
                        file.setContent(content);
                    }
                }
        });        
    }
]);

**Comment by xiangshouding** [comment]
用起来估计比较蹉跎。。。你可以配置试试，不过不要报太大期望；

**Comment by livisky** [comment]
这不是你们fex-team官方的插件么。。。我还以为是你写的，没人用过吗

**Comment by xiangshouding** [comment]
@livisky 人员比较多，产出惊人，没办法一个个都过一遍，让你受委屈了，请你喝一杯咖啡 :coffee:

**Comment by livisky** [comment]
真好喝！:watermelon::smile:

**Comment by livisky** [comment]
好的！什么时候能内嵌好呢，通知一下小弟。这样配置可以吗

fis.config.set('settings.optimizer.uglify-js', {
    mangle: {
        except: 'exports, module, require, define'
    },
    output : {
        sourceMap:true
    }
});

**Comment by xiangshouding** [comment]
嗯？我是说最好内嵌一下，现在是可以正常 work 的；

```js
fis.config.set('settings.optimizer.uglify-js', {
    mangle: {
        except: 'exports, module, require, define'
    },
    sourceMap:true
});
```

会产出 .map 文件，不过这个文件还得传给服务器端，麻烦，还是内嵌好；

**Comment by livisky** [comment]
老兄，这个插件sourcemap不能用了，生成的map无效，另外不能配置生成目录，得更新过了。

我把这插件下载下来，放到项目所在的node_modules文件里，然后改了下fis-optimizer-uglify-js里index.js的代码，
运行fis release -op
为何没有效果呢？

**Comment by xiangshouding** [comment]
所以，我给你提供一个能跑的；**只适用于你当前之想打包的场景**，请不要滥用；

**我已经更新了我的回复，你好好看看**

```js
var UglifyJS = require('uglify-js');

fis.config.set('roadmap.path', [{
    reg: '**.js',
    useOptimizer: false // 关闭单文件压缩
}])

fis.config.set('modules.postpackager', [
    function (ret, conf, settings, opt) {
        // ret.map  map.json 内容对象
        // ret.src  源码列表
        // ret.ids  ids 对应文件列表
        fis.util.map(ret.pkg, function (subpath, file) {
            if (file.isJsLike) {
                var opt = {};
                var content = file.getContent();
                opt.fromString = true;
                opt.outSourceMap = file.filename + '.org' + file.rExt;

                var ret = UglifyJS.minify(content, opt);
                var mapData = JSON.parse(ret.map);
                mapData.sources = [mapData.file];
                mapData.sourcesContent = [content];
                var newData = {
                    version: mapData.version,
                    file: mapData.file,
                    sources: mapData.sources,
                    sourcesContent: mapData.sourcesContent,
                    names: mapData.names,
                    mappings: mapData.mappings
                };
                ret.code += '\n//# sourceMappingURL=data:application/json;base64,' + fis.util.base64(JSON.stringify(newData));
                file.setContent(ret.code);
                console.log(ret.code);
            }
        })
    }
]);
```
**记得** `npm install uglify-js`

**Comment by livisky** [comment]
老兄，搞定了！感谢！

fis.util.map(ret.pkg, function (subpath, file) {})这里的ret.pkg应该是ret.src吧？

sourcemap内嵌的话，是少产生一个文件，但是本身文件变大了好多。看来还是得单独分开产生一个map文件。

**Comment by xiangshouding** [comment]
@livisky 哦，也是，那你就产出到文件里面就可以了，代码随便改~

**Comment by livisky** [comment]
老兄， 指定地方创建一个文件怎么创建啊，fis插件里怎么写？
