### ISSUE TITLE
提示找不到安装的插件 [ERROR] unable to load plugin [fis-postpackager-simple]

### ISSUE THREAD

**Issue by algate** [fex-team/fis#513]
fis安装fis-postpackager-simple插件，npm install -g fis-postpackager-simple，提示应该是成功了，
但是对文件编译压缩的时候还是报错unable to load plugin [fis-postpackager-simple，大家看看怎么解决；已经重装node，重新配置环境，php等问题依旧。

**Comment by maoguiyou** [comment]
你是不是还没有在配置文件开启插件啊  fis.config.set('modules.postpackager', 'simple');

**Comment by xiangshouding** [comment]
```bash
npm prefix -g
```

得到的路径假设为 NPM_ROOT 

加这个环境变量

```
export NODE_PATH=NPM_ROOT/lib/node_modules
```

Windows 用添加方式咨询下 Baidu
