### ISSUE TITLE
使用simple插件，加了fis.config.set('modules.postpackager', 'simple');后，打开页面报 Uncaught Error: Cannot find module `script/index`

### ISSUE THREAD

**Issue by fyy3312560** [fex-team/fis#515]
我在fis-conf.js文件中加上fis.config.set('modules.postpackager', 'simple');后，使用mod模块化，用pure release编译后，启动服务器，打开页面会报 Uncaught Error: Cannot find module `script/index`，无法使用require(`script/index`)了，然后将fis.config.set('modules.postpackager', 'simple');注释掉后，又可以用require(`script/index`)加载了

**Comment by xiangshouding** [comment]
```
require('script/index')
```
这个是 AMD 的？

**Comment by fyy3312560** [comment]
就是fis自己的模块化，用的pure

**Comment by xiangshouding** [comment]
@hefangshi 具体看看

**Comment by fyy3312560** [comment]
我就是看了下fis-quickstart-demo和fis-pure-demo这两个demo，各自都可以正常运行，但是在fis-pure-demo这个demo中加了fis.config.set('modules.postpackager', 'simple');这句后就会报Uncaught Error: Cannot find module `app/main`

**Comment by hefangshi** [comment]
fis-pure 里面自带了 simple 插件，不需要手动添加，所以删掉这句话直接使用即可。

https://github.com/fex-team/fis-pure/blob/master/pure.js#L17

另外因为 fis-pure 在 `postpackager` 阶段同时需要 `autoload` 和 `simple` 两个插件，你的配置将 `autoload` 删掉了，自然无法正常运行。
