### ISSUE TITLE
如何确定文件依赖关系

### ISSUE THREAD

**Issue by yeyeye0525** [fex-team/fis#525]
某次发布，只更改了bg.png一个文件，git只把这个文件抽出给我，我如何才能抽取那些对它存在引用的html或者js或者css文件呢

**Comment by xiangshouding** [comment]
你的原始需求是什么？

**Comment by yeyeye0525** [comment]
我们每次发布的时候只会对修改的文件进行打包，更新。
就如我只修改了一张背景图bg.png,然后生成对应的bg-f117c333.png，不过我css文件并没有修改，
所有没有被打包，故url还是指向bg.png，有没有什么方法可以同时把对bg.png有依赖的文件都确定出来。
或者说说你们平时的发布流程是怎样的，谢谢啦

**Comment by xiangshouding** [comment]
在 fis 里面，如果你的一个 css 用了某个图片，这个图片发生变化的时候，其 css 也会发生变化，因为引用这个图片的 url 里面带的 md5 串发生变化了。

所以，编译的结果里面应该会包含新 md5 的 css 文件；
