### ISSUE TITLE
1.9.x的watch问题

### ISSUE THREAD

**Issue by atian25** [fex-team/fis#530]
**复现步骤：**
1. 在自己的插件里面，根据某种逻辑，动态的设置file的release为false
2. 执行`fis release -w`， 观察第一次输出的`ret.ids`
3. 随便修改一个文件，观察watch后的第二次输出
4. 会发现，在1.9.25里面，两次输出不一样， 而1.9.3和以前的版本，输出是一样的。

怀疑在最近的fis升级中，watch的逻辑变更了。

**测试代码如下：**
```
fis.config.merge({
  roadmap: {
    path: [
      {
        reg: '**.css',
        id: '$&',
        isCssLike: true,
        release: '/css/$&'
      }
    ]
  },
  modules: {
	 postpackager: [framework]
  } 
});

function framework (ret, conf, settings, opt){
  console.log(Object.keys(ret.ids));
  fis.util.map(ret.src, function (subpath, file) {
    if(file.isCssLike){
      file.release = false;
    }
  });
}
```
**输出截图：**
1.9.25版本，如下图，两次输出`ret.ids`不一致，css都没了
![image](https://cloud.githubusercontent.com/assets/227713/8053808/88413b58-0ec6-11e5-945f-f68545952fdd.png)

1.9.3版本， 如下图， 两次输出`ret.ids`一致
![image](https://cloud.githubusercontent.com/assets/227713/8053861/df8fc7c6-0ec6-11e5-829c-e3418ff39436.png)

**Comment by hefangshi** [comment]
这里的逻辑是有调整，这个问题已经知晓并有调整了，明天会发一个新版处理这个问题。

**Comment by xiangshouding** [comment]
@atian25 升级最新试试

**Comment by atian25** [comment]
npm上最新是1.9.26, 这个不是前几天的版本吗?

**Comment by xiangshouding** [comment]
@atian25 我说的就是 1.9.26

**Comment by atian25** [comment]
不行

**Comment by xiangshouding** [comment]
现在 watch 过滤了 release 为 false 的文件进入编译流程。

**Comment by atian25** [comment]
所以这个是个特性而不是bug？我需要换种写法？

**Comment by atian25** [comment]
这里分两种情况，一种是一开始的fis-conf就是release为false，一种是在每次release过程中修改为release。watch的roadmap列表如果只考虑原始值应该就能避免我这问题。

**Comment by xiangshouding** [comment]
你要实现内嵌不产出是吧？

**Comment by atian25** [comment]
我的使用场景有两个，
1.构建过程用到生态模块的compoment.json递归分析依赖，发布时不发布。
2.构建时把css包装成js以便能缓存到ls,原css不发布。

不发布的选择是因为我是hybrid app本地页，要控制包大小。

当然，我也可以考虑仅在deploy时过滤，就是麻烦了点。

主要看你们认为这是feature还是bug。

**Comment by atian25** [comment]
一个文件，需要进入构建流程但不发布，目前fis只有一个release属性，所以不得已要动态修改

**Comment by xiangshouding** [comment]
@asoiso 应该区分是 conf 里面配置的还是后期动态更改的，这个算是没有考虑到的情况，感谢反馈；其实出现此问题根本性的原因是为了提升 watch 的性能，做了源码的缓存，用得是内存缓存，而缓存对象是一个个 File 对象，**导致 watch 两次编译相互影响了**，我把这块缓存改为只缓存文件路径，而不是 File 对象应该就能满足此种情况。

**Comment by xiangshouding** [comment]
+ fis@1.9.27

**Comment by atian25** [comment]
fixed
