### ISSUE TITLE
请问fis文档用什么框架还是自己写的？

### ISSUE THREAD

**Issue by meolu** [fex-team/fis#541]
[文档](http://fis.baidu.com/docs/beginning/getting-started.html)看着像doxmate又不太像，请教下是基于什么开源框架还是自己写的，能否开源？

**Comment by xiangshouding** [comment]
github.com/fex-team/fis-site

**Comment by meolu** [comment]
嗯，赞！
会有适合自己配置写文档的开源版本不？要不然得要自己在doxmate的基础上添加编辑、新建页面这些功能，需要些时间。不知道有没有合适的推荐？

**Comment by meolu** [comment]
对了，内部常用的那个文档系统有没有开源版本？

**Comment by xiangshouding** [comment]
@meolu ADoc ？不开源，现在都上 agroup 了。
