### ISSUE TITLE
__uri is not defined

### ISSUE THREAD

**Issue by go-to-win** [fex-team/fis#542]
我在js中都使用了__uri去定位资源，这带来一个问题：
在线上发布的时候会执行fis release去替换__url，
但是在本地开发环境中，使用eclipse启动服务器后，因为没有执行fis release去编译，导致浏览器执行时报错：__uri is not defined。
对于本地开发调试有什么好的解决办法吗？

**Comment by xiangshouding** [comment]
FIS 必须要求做编译

**Comment by go-to-win** [comment]
那我就是要先在自己的Windows机器上用fis编译下,然后再跑？

**Comment by xiangshouding** [comment]
可能你感觉惊讶的是这么麻烦怎么用是吧？其实真如你想的那么麻烦，那还会有人用。

- `fis release --watch --live` 可以监听代码变化即时编译
- `fis server ` 可以开启本地测试服务器方便本地做开发
- `fis release -d remote` 可以方便的把本地开发代码 push 到远端服务器

![image](https://cloud.githubusercontent.com/assets/631195/8207205/44e7bdec-1532-11e5-889d-b55e061bec5d.png)

**Comment by libofei2004** [comment]
但这样确实不太方便，fis能否增加一个功能，自定义一个在js中的静态资源列表，凡是代码引用了列表中的文件，一律按fis规则替换，这样就不影响原生代码的执行。
