### ISSUE TITLE
能否给一个调试服务器自定义监听IP的功能？

### ISSUE THREAD

**Issue by leochristian** [fex-team/fis#552]
最近因为在玩docker，发现fis的server服务不支持监听到0.0.0.0，而只能使用默认的127.0.0.1，不太方便啊……希望参考hexo的server服务，提供一个`fis server start -i / --ip 0.0.0.0`的功能，谢谢！

**Comment by xiangshouding** [comment]
```
fis server start --type php
```

need php, java

试试

**Comment by leochristian** [comment]
不太想装这些环境呢，觉得fis是给前端用的工具，却要求装php、java，好奇怪……之前听别人评论说fis没coolie好用，一个是需要多次监听构建，第二个就是环境依赖问题。建议还是增加个这样的功能吧，或者默认监听到0.0.0.0上去，不过我相信还是会有人需要只监听127的地址的……

**Comment by xiangshouding** [comment]
@leochristian 我只是想让你尝试一下。我不清楚什么地方触恼了你。

**Comment by nwind** [comment]
可以在 node 版中加上这个配置试试
