### ISSUE TITLE
fis如何将图片上传的阿里云或七牛？

### ISSUE THREAD

**Issue by Janking** [fex-team/fis#557]
fis文档中好像没有提到这一点，还是我没找着？

**Comment by hefangshi** [comment]
https://github.com/suiqirui1987/fis-deploy-aliyun

**Comment by Janking** [comment]
@hefangshi  谢谢！要是有七牛的就好了！看了一下你的源码，不知道能不能模仿写个七牛的。

**Comment by hefangshi** [comment]
其实原理都是一样的，就是简单的文件上传，其余工作FIS都帮你封装好了。另外这个代码不是我写的，也是社区贡献的。有兴趣的话你可以写一个qiniu的。

**Comment by fouber** [comment]
@Janking 

我甚至连插件都没写，这是我的项目结构：

![image](https://cloud.githubusercontent.com/assets/536297/8304423/3d3adfca-19d8-11e5-943d-3e59e1ce6639.png)

猜猜我的 ``.qiniu-build.sh`` 怎么写的？

```bash
output=/temp/story-output  # 设置一个发布用的临时目录
fis release -Doumpd ${output}     # 利用fis把代码构建过去
qrsync ${HOME}/.story-conf.json   # 用准备好的七牛配置发布
rm -rf ${output}                  # 删除掉临时目录
```

你大概能想到我的那个七牛配置里写的什么吧：

```json
{
    "src": "/temp/story-output",
    "dest": "qiniu:access_key=***&secret_key=***&bucket=story&key_prefix=story/",
    "deletable": 0,
    "debug_level": 1
}
```

每次要发布，执行一下：

```bash
./.qiniu-build.sh
```

搞定。

其实原理就那么一点点：
1. fis release -Doumpd {临时目录}
1. cd {临时目录}
1. qrsync
1. rm -rf {临时目录}
然后把以上步骤写成一个build.sh或者build.bat，很麻烦么。。。

**Comment by Janking** [comment]
@fouber  so cool ! 对于刚开始学shell的我竟然看得懂! 3Q!
