### ISSUE TITLE
fis-parser-sass在 centos6.5 下安装报错了，请问是什么问题呢？ 其他插件安装没问题。 

### ISSUE THREAD

**Issue by hhhome** [fex-team/fis#560]
其他环境都已经装好了！环境是node v0-12.5 npm v2.11.2 
 不知道会不会是gcc版本的问题，现在在更新！
gcc 更新到4.8.4还是用不了。求解救。
> fis-sass@3.1.3 install /usr/local/lib/node_modules/fis-parser-sass/node_modules/fis-sass
> node build.js

Downloading http://fisstatic.duapp.com/addons/fis-sass/3.1.0/linux-x64/0.12.0/binding.node ...
Received 518K...
Received 1065K...
Received 1582K...
Received 1753K total.
Test failed!
child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/fis-parser-sass/node_modules/fis-sass/.node-gyp"

make: Entering directory `/usr/local/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cpp: In function ?.ass_Import** sass_importer2(const char*, const char*, void*)?.
../src/binding.cpp:27: warning: null argument where non-null required (argument 1)
../src/binding.cpp:28: warning: null argument where non-null required (argument 1)
../src/binding.cpp: In function ?.oid GetStats(v8::Handle<v8::Object>, Sass_Context*)?.
../src/binding.cpp:95: error: ?.ullptr?.was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/fis-parser-sass/node_modules/fis-sass/build'
gyp ERR! build error

**Comment by qiaosang** [comment]
碰到了，不知道怎么解决，求大神

**Comment by hhhome** [comment]
@qiaosang fis-parser-sass 已停止更新，请移步至：https://github.com/fex-team/fis-parser-node-sass
