### ISSUE TITLE
现在项目使用seajs,基本每个页面都会use一些模块,怎么使用fis将这些模块合并

### ISSUE THREAD

**Issue by lucifercha** [fex-team/fis#562]
现在项目使用seajs,基本每个页面都会use一些模块,怎么使用fis将这些模块合并

**Comment by YDSS** [comment]
@lucifercha 你的意思是要把这些 use 的模块合成一个？

**Comment by lucifercha** [comment]
@YDSS 是啊 就是这个意思

**Comment by xiangshouding** [comment]
我先不说 seajs 下怎么搞，我先说一下 FIS 的 mod.js 是怎么搞的。

mod.js 解决合并问题主要靠 FIS 工具编译。FIS 编译的时候会产出一张资源映射表，叫 `map.json`

这张表里面记录了资源的文件类型、部署路径、依赖信息、合并信息。大概数据结构是这样的

```json
{
    "res": {
        "a.js": {
            "uri": "http://cdn.baidu.com/cdn/a_8538fd.js",
            "type": "js",
            "pkg": "p0",
            "deps": [
                "b.js"
            ]
        },
        "b.js": {
            "uri": "http://cdn.baidu.com/cdn/b_0844ff.js",
            "type": "js",
            "pkg": "p0"
        },
        "c.js": {
            "uri": "http://cdn.baidu.com/cdn/b_8844da.js",
            "type": "js",
            "pkg": "p0"
        }
    },
    "pkg": {
        "aio.js": {
            "uri": "http://cdn.baidu.com/cdn/aio_807654.js",
            "has": [
                "a.js",
                "b.js",
                "c.js"
            ]
        }
    }
}
```

那么恰好，mod.js 加载完后会把这张表注册给框架。

```js
require.resourceMap({
  'res': {...},
  'pkg': {...}
});
```

当程序执行

```js
require.async('a.js', function (a) {}); 
```

时，拿到第一个参数，在表里面找到对应的 uri（url），请求回来，并执行回调，如果有依赖就先加载依赖。

这样实现了异步加载、cdn、md5戳等等功能。

那么会转回 seajs 是否可以给其弄一个查表的功能呢？

依附于其配置 API

```js
seajs.config({
  paths: {
    "a.js": "aio_xxxxxx.js",
    "b.js": "aio_xxxxxx.js",
    "c.js": "aio_xxxxxx.js"
  }
});

seajs.use('a.js');
```
这么来请求合并呢？嗯，我还没有详细用过 seajs，如果有啥问题，一起讨论。

或者直接 hack 其接口加一个查表的功能。

**Comment by marilawang** [comment]
@xiangshouding  a.b.c 的依赖 deps 是在哪里定义的？

**Comment by xiangshouding** [comment]
参考 FIS 三种语言能力之 [声明依赖](https://github.com/fex-team/fis/wiki/%E5%A3%B0%E6%98%8E%E4%BE%9D%E8%B5%96)

**Comment by marilawang** [comment]
我试了一下，貌似 声明依赖 并不能在 pack 的时候自动引入？

**Comment by marilawang** [comment]
@xiangshouding 我试了一下，貌似 js的声明依赖 并不能在 pack 打包合并的时候自动引入？

**Comment by xiangshouding** [comment]
@marilawang 

FIS 默认带的 fis-packager-map 插件，合并并不会去根据依赖来合并，只根据你的配置。依赖来合有诸多不理想的地方。主要考虑到一些问题，参考

- https://github.com/fex-team/fis/issues/488#issuecomment-101989042

如果向合并依赖，可以参考插件

- [fis-packager-depscombine](https://www.npmjs.com/package/fis-packager-depscombine)

**Comment by marilawang** [comment]
@xiangshouding 嗯，可以了。

对于较复杂的单页应用来说，依赖打包还是比较重要的，因为不涉及多页面共享js的问题。而如果没有依赖打包的话，等于要自己确定所有js打包的顺序，就需要写一个大数组……

我觉得这个应该集合到 --pack 参数中，比如增加一个 --pack-with-deps 参数来指定 pack 是依赖 pack

供参考

**Comment by xiangshouding** [comment]
> 而如果没有依赖打包的话，等于要自己确定所有js打包的顺序，就需要写一个大数组……

默认打包插件是会根据文件的依赖调整顺序的，所以其实用通配符就可以了，前提是标明了依赖。

> 我觉得这个应该集合到 --pack 参数中，比如增加一个 --pack-with-deps 参数来指定 pack 是依赖 pack

一切打包插件的调用都应该用一个命令 `--pack`，而不同的只是其使用的打包插件，那么这块得靠配置了。
