### ISSUE TITLE
fis合并打包后如何线上调试

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/fis#570]
因为线上js资源是合并打包的，不好调试，是否有类似加个debug参数，页面变为非合并打包，类似开发时那样独立加载的，方便线上调试？

**Comment by xiangshouding** [comment]
@fancyboynet 嗯，我们是 PHP 来做静态资源管理的，所以设置了一个 URL 的参数，类似 `?fis_debug` 来让静态资源吐出的时候散列文件，如果被压缩的代码，我们再用代理工具代理一下。

不过定位到文件已经不需要再继续了，因为可能我们的模块都相对于比较小，逻辑清晰。

当然我们也可以在线上部署一份未压缩的版本，传个什么 URL 参数就能拿到为压缩版本，这样我就可以接着看为压缩版本的代码了。

**Comment by fancyboynet** [comment]
你是说fisp已经实现这个功能了是吗，如果用pure就没有线上调试的功能，需要自己开发？虽然模块已经很小，但是比如有时问题是返回数据（比如格式）出了问题，这时如果全是合并压缩的，应该不好调试吧，也不知道具体是哪个模块出的问题

**Comment by xiangshouding** [comment]
pure 应该没有类似的功能。如果需要只能做二次开发。

**Comment by fancyboynet** [comment]
那我知道了，谢谢解答
