### ISSUE TITLE
fis安装问题如图

### ISSUE THREAD

**Issue by chinajoy** [fex-team/fis#577]
![qq 20150630162841](https://cloud.githubusercontent.com/assets/8321598/8426824/517f70e6-1f45-11e5-8406-11e91670e264.png)

**Comment by xiangshouding** [comment]
看 FAQ #565

**Comment by hhhome** [comment]
是不是没有全局安装？

**Comment by yunhailu** [comment]
npm ERR! tar.unpack untar error /Users/MLS/.npm/fis/1.9.33/package.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "fis"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/fis
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/fis'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/fis']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/fis',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/fis',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MLS/npm-debug.log
