### ISSUE TITLE
fis图片合并时, background中即设置了图片，又设置了position，该如何配置？

### ISSUE THREAD

**Issue by sunhaikuo** [fex-team/fis#579]
原CSS写法:
background:url(img/pic_3.jpg) no-repeat center top

替换后:
background-position: -963px -1856px;

这样center top 这块就被去掉，页面的样式就不正常了，请问该如何处理？

**Comment by xiangshouding** [comment]
https://github.com/fex-team/fis-spriter-csssprites/issues/8
