### ISSUE TITLE
使用非模块化第三方插件时候 fis 设置不好使

### ISSUE THREAD

**Issue by 274793580** [fex-team/fis#587]
# fis配置

```js
fis.config.set('roadmap.path', [{
	reg: /^\/components\/(.*\.js)$/i,
	isMod: true,
	jswrapper: {
		type: 'amd'
	},
	release: '${statics}/components/$1'
}, {
	reg: /^\/components\/.*\.(?:less|md)$/i,
	release: false
}, {
	reg: 'doc/**.md',
	release: false
}, {
	reg: /^\/static\/thirdParty\/(.*\.js)$/i,
	isMod: false,
	release: '${statics}/thirdParty/$1'
}, {
	reg: /^\/static\/libs\/(.*\.js)$/i,
	isMod: true,
	release: '${statics}/libs/$1'
}].concat(fis.config.get('roadmap.path', [])));

```
# 结果

[WARNI] Got Error: The file has more than one anonymous define while parse [/static/thirdParty/onsenui/js/onsenui.js]
.
 [WARNI] Got Error: The file has more than one anonymous define while parse [/static/thirdParty/onsenui/js/onsenui.min.js]
.
 [WARNI] Got Error: The file has more than one anonymous define while parse [/static/thirdParty/onsenui/js/onsenui_all.js]
.
 [WARNI] Got Error: The file has more than one anonymous define while parse [/static/thirdParty/onsenui/js/onsenui_all.min.js]
... 13442ms

**Comment by 2betop** [comment]
你更新下fis3-hook-module 试试，感觉像是老版本的问题。

**Comment by 2betop** [comment]
执行 `fis3 inspect` 试试

**Comment by xiangshouding** [comment]
...请不要串了，这是 FIS 的仓库。

**Comment by 274793580** [comment]
我更新了fis3-hook-module ,如何执行fis3 inspect ？

**Comment by 2betop** [comment]
不要意思，我搞乱了，以为是 fis3
