### ISSUE TITLE
manifest文件无法解析，加了isHtmlLike:true也是一样

### ISSUE THREAD

**Issue by tinhour** [fex-team/fis#603]
fis-config.js中加了下面的设置，还是无法把mainfest当html文件把里面的js,css文件替换成带md5的文件名。

roadmap：{path:
 {
                //所有的mainfest文件
                reg : '**.manifest',
                isHtmlLike : true,
                release:"$&",
                url : '/bicloud$&',                
                useHash: true
            }
}      
           
cahce.maifest文件的部分内容
CACHE:
js/jquery.min.js
js/underscore/underscore.js
js/localForage/localforage.js
....

后来又加上了ext的配置也不起作用。
 roadmap : {        
         ext : {          
            //并且在parser之后的其他处理流程中被当做html文件处理
            manifest : 'html'
        }
是我配置不对还是框架不支持了？

**Comment by xiangshouding** [comment]
首先 manifest 被证明是有缺陷的，其次再回归到你这个问题。即便你设置成了**isHtmlLike**也依然无法像你预期的那样工作。

因为**资源定位**只对一些资源定位的标签起效。比如

```html
<img src=""></img>
<link href="">
```

所以，我感觉你可以换一种思路，通过 fis 插件来生成一个 manifest 。

其实这个插件并不难，可以参考插件开发文档 http://fis.baidu.com/docs/dev/plugin.html

你在 **打包阶段** 可以拿到所有项目中的文件，可以根据类型生成一张 manifest。具体你再研究研究。

**Comment by tinhour** [comment]
@xiangshouding  谢谢。我明白了。manifest是有缺陷，缓存下的html文件对ajax文件在线时也去找离线地址，不知道你是不是指的这个。

**Comment by tinhour** [comment]
mainfest生成组件写好了，供查询人员参考：
/* mainfest文件生成组件 */

'use strict';

function trimQuery(url) {
    if (url.indexOf("?") !== -1) {
        url = url.slice(0, url.indexOf("?"));
    }
    return url;
}

function getResourcePathMap(ret, conf, settings, opt) {
    var map = {};
    fis.util.map(ret.map.res, function (subpath, file) {
        map[trimQuery(file.uri)] = subpath;
    });
    fis.util.map(ret.pkg, function (subpath, file) {
        map[trimQuery(file.getUrl(opt.hash, opt.domain))] = file.getId();
    });
    return map;
}

function writeln(content){
    return content+"\r\n";
}

module.exports = function (ret, conf, settings, opt) {  
    if(!settings.manifestName) {
        console.log("mainfest need set settings.postpackager.manifest.manifestName value")
        return ;
    } 
    var pathMap = getResourcePathMap(ret, conf, settings, opt); 
    var maifestContent=writeln("CACHE MANIFEST");
    maifestContent+=writeln("#Generate @"+new Date());
    maifestContent+=writeln("NETWORK:\r\n*");
    maifestContent+=writeln("CACHE:");
    fis.util.map(pathMap,function(subpath,file){
        if(/.*(\.js|\.css|\.gif|\.png|\.jpg|\.jpeg)$/.test(subpath)){            
            maifestContent+=writeln(subpath);
        }        
    })
    fis.util.write(settings.manifestName, maifestContent, "utf8");
    console.log("\r\n=====>manifest generate finished!\r\n")
};

**Comment by 2betop** [comment]
最后一步不要直接写磁盘

**Comment by 2betop** [comment]
失误了，执行换个行，结果直接提交了


这样直接写磁盘的的话，会没法 deploy 出去。

建议新建 file 对象，然后加入到 ret.pkg 对象中。

**Comment by xiangshouding** [comment]
@2betop 楼上给示例啊，文字毕竟苍白

**Comment by tinhour** [comment]
@2betop ret对像有没有资料，结构说明的文档。发现bug了,同名的mainfest文件不能覆盖，只有另一个名才能保存。
应该是要像你说的那样操作。

**Comment by xiangshouding** [comment]
@tinhour `console.log` 大法好

**Comment by tinhour** [comment]
@xiangshouding console.log打出来一堆，结构不好看。

**Comment by 2betop** [comment]
node inspector 大法好

**Comment by xiangshouding** [comment]
```js
var ret = {
  src: {
    <subpath>: new File,
    <subpath>: new File
  },
  ids: {
    <id>: new File,
    <id>: new File
  },
  pkg: {
    <subpath>: new File
  }
}
```

大概结构

**Comment by tinhour** [comment]
@2betop @xiangshouding 建议新建 file 对象，然后加入到 ret.pkg 对象中。网络限制了npm不能用。inspector大法没法用，console.log出来，太长太长没法看。
主要是如何加入到pkg对象中？没有add方法。给个示例出来。
module.exports = function (ret, conf, settings, opt) {  
    if(!settings.manifestName) {
        console.log("mainfest need set settings.postpackager.manifest.manifestName value")
        return ;
    } 
    var pathMap = getResourcePathMap(ret, conf, settings, opt); 
    var maifestContent=writeln("CACHE MANIFEST");
    maifestContent+=writeln("#Generate @"+new Date());
    maifestContent+=writeln("NETWORK:\r\n*");
    maifestContent+=writeln("CACHE:");
    fis.util.map(pathMap,function(subpath,file){
        if(/.*(\.js|\.css|\.gif|\.png|\.jpg|\.jpeg)$/.test(subpath)){            
            maifestContent+=writeln(subpath);
        }        
    })
    //fis.util.write(settings.manifestName, maifestContent, "utf8");
    //var fs=require("fs");fs.writeFileSync(settings.manifestName, maifestContent)
    //建议新建 file 对象，然后加入到 ret.pkg 对象中。
    var file = fis.file.wrap(settings.manifestName);
    console.log("\r\n=====>file.exists() ========>\r\n",file.exists())
    file.setContent(maifestContent)
    file.useCache = false; // @NOTICE 
    //ret.pkg.add(file);//没有add方法
    console.log("\r\n=====>"+settings.manifestName+" generate finished!\r\n")
};

**Comment by tinhour** [comment]
没有范例就关了。

**Comment by tinhour** [comment]
/* fis maifest 文件生成组件 */

/*
 * fis-poster-manifest
 * https://github.com/tinhour
 * author:thinhour
 * 2015-7-21
 */

'use strict';

function trimQuery(url) {
    if (url.indexOf("?") !== -1) {
        url = url.slice(0, url.indexOf("?"));
    }
    return url;
}

function getResourcePathMap(ret, conf, settings, opt) {
    var map = {};
    fis.util.map(ret.map.res, function (subpath, file) {
        map[trimQuery(file.uri)] = subpath;
    });
    fis.util.map(ret.pkg, function (subpath, file) {
        map[trimQuery(file.getUrl(opt.hash, opt.domain))] = file.getId();
    });
    return map;
}

function writeln(content){
    return content+"\r\n";
}

module.exports = function (ret, conf, settings, opt) {  
    if(!settings.manifestName) {
        console.log("mainfest need set settings.postpackager.manifest.manifestName value")
        return ;
    } 
    var pathMap = getResourcePathMap(ret, conf, settings, opt); 
    var maifestContent=writeln("CACHE MANIFEST");
    maifestContent+=writeln("#Generate @"+new Date());
    maifestContent+=writeln("NETWORK:\r\n*");
    maifestContent+=writeln("CACHE:");
    fis.util.map(pathMap,function(subpath,file){
        if(/.*(\.js|\.css|\.gif|\.png|\.jpg|\.jpeg)$/.test(subpath)){            
            maifestContent+=writeln(subpath);
        }        
    })
    var fileExt="manifest";
    var subpath = settings.manifestName;
    var file = fis.file(fis.project.getProjectPath(), subpath);
    ret.pkg[file.subpath] = file;
    var content="CACHE MAINFEST\r\n";
    file.setContent(maifestContent);
    var id = "auto_mainfest";
    ret.map.pkg[id] = {
        uri: file.getUrl(opt.hash, opt.domain),
        type: fileExt
    };
    console.log("\r\n "+settings.manifestName+" generate finished!")
};
