### ISSUE TITLE
fis release -w之后，按什么键可以继续输入命令？

### ISSUE THREAD

**Issue by zhankenson** [fex-team/fis#604]
fis release -w之后，按什么键可以继续输入命令？我输入完这个监听文件状态之后，命令提示符那里无法输入任何东西

**Comment by xiangshouding** [comment]
- 重新打开一个 cmd 窗口即可
- 如果要停掉 `-w`，用快捷键<kbd>ctrl</kbd>+<kbd>c</kbd>
