### ISSUE TITLE
资源定位问题

### ISSUE THREAD

**Issue by mini188** [fex-team/fis#613]
对于同一个资源，有许多不同的目录写法，比如：
url('/img/lgoin_logo.png')
url('img/lgoin_logo.png')
还有一种是我们的用法
url('${imgServer}/img/lgoin_logo.png')

但是使用FIS时只能对第一种进行处理？这是为什么？不能模糊匹配吗？

**Comment by mini188** [comment]
没有人回复啊？
fis中能否在替换资源目录时保留相对目录呢？
现在Fis发布后写入的是绝对目录，举例：
原始：url('img/lgoin_logo.png')
发布：url('/css/img/lgoin_logo.png')
这样如果发布的站点放在一级目录是好的，但是在二级目录的时候就会定位失败

**Comment by 2betop** [comment]
1.资源查找不支持变量
2. 现在全部是绝对路径，主要是考虑到资源合并和 cdn 部署的功能实现

**Comment by mini188** [comment]
这样啊，明白了。

**Comment by lj7711622** [comment]
跟我们一样的情况 使用时 把 项目的${imgServer} 替换成 ../../
