### ISSUE TITLE
FIS3宣传视频收集，欢迎各个团队提供素材！！！

### ISSUE THREAD

**Issue by zhangtao07** [fex-team/fis#615]
HI 小伙伴们~

[FIS3](http://fex.baidu.com/fis3) 经过FIS团队不断打磨，在`易用性`和`扩展性`都有了明显的提升，github已开放，我们想准备一个小视频作为发布宣传。在此征集各个使用FIS/FIS3的团队，欢迎提供小视频(不是优衣库小视频哈~) 说明使用FIS感受，我们将在视频中注明你们公司/团队~

### 素材要求

 - 由各公司自行录制视频，请`简明扼要`的一句话说明`使用FIS的体验`，可以加上白板等其他道具辅助，时间尽量不超过`15s`
 - 如果使用过`FIS3` , 推荐针对FIS3给出评价
 - 注明公司或团队名称，将在视频中展现给你们宣传
 - 杜绝低俗、反动、暴力，投稿即授权我们可以剪辑使用素材制作FIS推广视频在非商业场合使用
 - 请提供视频下载地址(如百度云)或邮件发至鼎爷邮箱fansekey@gmail.com

**示例，仅供参考**

> 字幕将会给出团队名称，所以可以不用"我们是xx团队"开头

 - FIS让我们自信走上前端工程化之路！
 - 起初我是拒绝的，国产的有些令人担心，自从用了FIS3之后，什么grunt、gulp、webpack都抛到了一边，再也不用熬夜学这么多工具了，终于可以陪女朋友看电影了
 - FIS让我们在xx方面有了xx的提升
 - FIS业界良心，妈妈再也不用担心我前端开发了~
 - 用FIS3，走向前端架构师，迎娶白富美！

### 截止时间 
 
请尽量于本周五(07-24)前提供！！ 谢谢~

**Comment by looping84** [comment]
占个位置，这周五时间有点紧啊。能往后延不。

**Comment by zhangtao07** [comment]
哈哈，手机/相机拍个一句话就行了，文字素材我们会帮你们加上

**Comment by NuerSir** [comment]
顶一个，赞助个妹纸

**Comment by looping84** [comment]
视频要什么尺寸的
长宽比例是多少

**Comment by zhangtao07** [comment]
没有这么严格的要求，我们剪辑会调整尺寸，一般的手机相机应该都可以吧
