### ISSUE TITLE
编译时报错：Floating point exception

### ISSUE THREAD

**Issue by qjqw** [fex-team/fis#617]
命令：fis release -d ./output -om
报错：Ω ......Floating point exception (core dumped)

项目里有png图片的时候就会报这个，删掉png的图片就好了。求解

**Comment by xiangshouding** [comment]
这是一个很尴尬的 bug，我没有猜错的话你应该是用的是 ocean 的机器？

**Comment by qjqw** [comment]
是用的 ocean 的机器 ...
有解决办法么

**Comment by xiangshouding** [comment]
```bash
bash -c "$( curl http://fedev.baidu.com/~fis/install.sh -k )" && source ~/.bashrc
```

执行以上脚本后，就可以了。

**Comment by qjqw** [comment]
/home/work/.zshrc: line 7: autoload: command not found
/home/work/.zshrc: line 8: compinit: command not found
/home/work/.zshrc: line 11: setopt: command not found
/home/work/.zshrc: line 35: /home/work/.fis/build-tools/build-tools/silent-env.sh: No such file or directory
/home/work/.zshrc: line 36: /home/work/.fis/build-tools/build-tools/silent-env.sh: No such file or directory
/home/work/.zshrc: line 37: /home/work/.fis/build-tools/build-tools/silent-env.sh: No such file or directory
/home/work/.zshrc: line 38: /home/work/.fis/build-tools/build-tools/silent-env.sh: No such file or directory

一堆报错 ...

**Comment by luofei2011** [comment]
更新一下，最近ocean有批机器升级维护过。如果还出现这个问题，卸载掉用jumbo装的nodejs，去官网下载编译后的源码包能解决这个问题。
