### ISSUE TITLE
release后,JS也被加在html的head中。html声明依赖后如何不添加 JS？

### ISSUE THREAD

**Issue by xianglgd** [fex-team/fis#619]
如题，如何解决？
问题1：
我 modules 下 有个 app 文件夹，其中有 app.js， app.css。
外面index.html ，采用 require("app"); 编译后，会把 app.js放在 head中。
可是我想放在 body 底部呀 。怎么做呢？

问题2：
我在 HTML中声明一个 依赖 @require lib/mod.js。 编译后就把 JS 放入head 中。并且map.json 中也没此依赖关系列表。
我想要的是，声明依赖，编译后只是产生 map.json，不把JS添加入 head中。
如何做？

**Comment by xianglgd** [comment]
求回答，，，，，，，，，，

**Comment by hefangshi** [comment]
说明一下你使用的解决方案或者插件

**Comment by xianglgd** [comment]
用的是 fis-pure

**Comment by hefangshi** [comment]
在 fis-pure 开一个issue吧；）
