### ISSUE TITLE
invalid deploy destination options [dev]

### ISSUE THREAD

**Issue by wslmts** [fex-team/fis#622]
你好，
     完全按照yog2的文档一步步使用，但是在执行【yog2 release --dest dev】这一步时，提示【invalid deploy destination options [dev]】，并且访问不到内容，请问是什么原因？
     另外，还想问一下这个【dev】怎样配置？（从fis的文档处得知dev是内置的部署配置名），谢谢！

**Comment by xiangshouding** [comment]
```js
fis.config.set('deploy', {
  dev: {
    from: '/',
    to: '../output
  }
});
```
- fis release -d dev

**Comment by wslmts** [comment]
thank you!
