### ISSUE TITLE
请问FIS不支持gbk编码的静态文件合并压缩吗？

### ISSUE THREAD

**Issue by zhoushengmufc** [fex-team/fis#627]
请问FIS不支持gbk格式的静态文件合并压缩吗？如果有怎么实现呢？

**Comment by xiangshouding** [comment]
合并不合并跟编码没有啥关系，FIS 会合并你的资源按照你的规则，但默认情况下并不会替换到页面上。这个动作留给静态资源管理方案来处理。比如某些 FIS 的打包后处理（postpackager）插件处理。或者是用 fis-plus 这样的由后端 ResourceAPI 统一处理打包资源替换到页面的工作。

所以，你需要确定是没有产出合并资源亦或是没有给你替换到页面上。如果在正确的使用方法下没有产出合并后的资源那么说明 FIS 核心有 Bug，如果是产出了合并后的资源但是没有替换到页面（html）上去，就得考虑**静态资源管理**逻辑是否正常。需要根据你本身使用的方案去对症下药。

**Comment by zhoushengmufc** [comment]
感谢帮助，已经解决了
是我的使用方法不正确，我使用了：
fis.config.init({
    project : {
        charset : 'gb2312',
        md5Length : 7
    }
});
因为 init 默认有很多插件调用的配置被你干掉了
所以如果用GBK编码的朋友这样设置就OK了：
fis.config.set('project.charset', 'gb2312');
