### ISSUE TITLE
fis release -o 神奇消失了

### ISSUE THREAD

**Issue by SimplyY** [fex-team/fis#640]
![image](https://cloud.githubusercontent.com/assets/8455579/9149921/2da539b2-3df4-11e5-8c0e-a16838d06781.png)

然后各种看 commit log 也找不到替代方案。。还想 PR 的 qaq

**Comment by fouber** [comment]
fis3中压缩开关功能由media功能替代了。

原来fis2中压缩的做法是：``fis-conf.js中配置插件`` + ``fis release -o``
现在fis3中压缩的做法是：``fis-conf.js中配置某种media下的插件`` + ``fis3 release 那种media``

比如fis3配置：

```js
fis.media('prod').match('**.js', {
    optimizer: fis.plugin('uglify-js')
});
```

执行 ``fis3 release``：media没有生效，所以没有压缩；

执行 ``fis3 release prod``：media生效，开启了压缩。
