### ISSUE TITLE
[ERROR] unable to load plugin [fis-preprocessor-jswrapper]

### ISSUE THREAD

**Issue by letyougo** [fex-team/fis#642]
我试了 fis install [fis-preprocessor-jswrapper ,npm install fis-preprocessor-jswrappe都不能安装 fis2的官网上也没有安装插件的方法。到底怎么安装插件！蛋疼

**Comment by xiangshouding** [comment]
https://www.npmjs.com/package/fis-postprocessor-jswrapper

**Comment by xiangshouding** [comment]
#643
