### ISSUE TITLE
fis v1.9.32 uglify 依然会warning

### ISSUE THREAD

**Issue by atian25** [fex-team/fis#646]
![image](https://cloud.githubusercontent.com/assets/227713/9403110/6db7fafe-4816-11e5-92bb-2fe4597f2e0c.png)

![image](https://cloud.githubusercontent.com/assets/227713/9403113/7374bedc-4816-11e5-8219-88c42d47d3cb.png)

**Comment by xiangshouding** [comment]
粗心导致问题，已经发了 1.9.33 版本，升级应该就好了；

```
npm install -g fis@1.9.33
```

**Comment by 2betop** [comment]
非常抱歉，太大意了。
