### ISSUE TITLE
fis2自动拼合雪碧图，拼合前设置 background-size: 50%，编译后没有这样样式了，怎么办

### ISSUE THREAD

**Issue by shenfusheng** [fex-team/fis#651]
![image](https://cloud.githubusercontent.com/assets/9476838/9624717/d9d924b4-5181-11e5-9f4e-172a76c807f3.png)
![image](https://cloud.githubusercontent.com/assets/9476838/9624725/f081eb1a-5181-11e5-8b4d-03bf6462623f.png)

**Comment by xiangshouding** [comment]
不支持百分比这种，你可以设置具体的 px 值

![image](https://cloud.githubusercontent.com/assets/631195/9626839/e8dd3534-5192-11e5-9d2e-0a7c48a14e49.png)

https://github.com/fex-team/fis-spriter-csssprites

**Comment by shenfusheng** [comment]
谢谢，问题解决了，十分感谢

**Comment by xiangshouding** [comment]
不用客气
