### ISSUE TITLE
fis-plus如何使用fis.media()类似的功能

### ISSUE THREAD

**Issue by ShangXinbo** [fex-team/fis#666]
我现在使用fis2的fis-plus，遇到一个类似fis.media()的解决场景，想问如何在不同环境发布环境使用不同的配置文件进行发布呢？

**Comment by fouber** [comment]
@ShangXinbo 

在fis-conf.js中使用环境变量，比如：

```js
// fis-conf.js
fis.config.set('abc', process.env.USE_ABC);
```

然后构建的时候，加上这个变量就行了：

```base
USE_ABC=1 fisp release -d xxx
```

**Comment by ShangXinbo** [comment]
环境变量是什么东西，能详细指教一下么

**Comment by ShangXinbo** [comment]
@fouber  按你这样设置，‘abc’应该不是一个配置吖，比如我要设置以下的配置，如何使用环境变量,在测试环境使用在线上环境使用另一个配置呢？
fis.config.merge({
	namespace: 'home',
	roadmap: {
		path: [
		{
			reg: /^\/static\/(.*)/i,
			release: '/public/x_web/$1',
		}]
	}
})

**Comment by fouber** [comment]
@ShangXinbo 

```js
// fis-conf.js
if(process.env.PROD){
    fis.config.merge({
        namespace: 'home',
        roadmap: {
            path: [
            {
                reg: /^\/static\/(.*)/i,
                release: '/public/x_web/$1',
            }]
        }
    })
}
```

**Comment by ShangXinbo** [comment]
@fouber  OK 明白了，原来是node
