### ISSUE TITLE
fis-plus如何使用fis.media()类似的功能

### ISSUE THREAD

**Issue by shangxinbo** [fex-team/fis#667]
如何在不同环境使用不同的配置文件发布，或者说不同的配置项发布，比如我的静态文件，在测试环境发布在public文件目录下，在线上要发布到common文件目录下，如何配置

**Comment by zhangtao07** [comment]
请查看 fis-plus/fis 中 deploy [配置文档](http://fex-team.github.io/fis-site/docs/api/fis-conf.html#deploy)，deploy 可以设置多个目标
