### ISSUE TITLE
fis如何实现js代码在release之前自动处理依赖关系并构建成为一个js文件？

### ISSUE THREAD

**Issue by zqjflash** [fex-team/fis#668]
有三个文件app.js, dialog.js, validate.js在同级目录，其中app.js为入口，代码如下：
var dialog = require("./dialog");
var validate = require("./validate");
dialog.confirm();

想要的预期是在执行fis3 release时，app.js会自动组合成一个完整的可执行js文件（包含依赖关系），比如叫bundle.js

模板页面引入的为最终bundle.js

有类似像browserify或webpack那样处理js依赖与合并问题的插件吗？

**Comment by amriogit** [comment]
目前 `fis` 插件还不支持异步输出，所以 `browserify`，`webpack` 插件目前应该没有

我目前的做法是 `webpack` 和 `fis` 分开使用，`fis` 使用 `webpack` 构建后的文件，这就和平常使用 `fis` 没两样了。

注意： `webpack` 管理的文件不要给 `fis` 监听到，`fis` 只监听 `webpack` 构建后的文件，不然 `fis` 的 `watch` 会很积极的

PS：使用 `child_process.execSync`  把异步任务改同步？
