### ISSUE TITLE
fis3 release -w页面不停闪现出命令行然后消失

### ISSUE THREAD

**Issue by Alexis374** [fex-team/fis#670]
node版本4.1.1 win8

第一次运行 fis3 release -w（或fis3 release -wL）命令的时候会闪现一下，但当修改文件保存之后，输入fis3 release -w的命令行窗口一直出现 Ω .......................... 312ms [23:35:50.052] 这样的提示，另外还有一个命令窗口闪现，除非按ctrl+c停止

**Comment by zhangtao07** [comment]
是不是编译过程中又产生了什么文件递归触发了 watch? 信息不足不好判断
