### ISSUE TITLE
 node-pngcrush does not support your node v4.1.1

### ISSUE THREAD

**Issue by 532604872** [fex-team/fis#671]
D:\demo\fis-quickstart-demo>fis release -o

 Ω ...
 [WARNI] node-pngcrush does not support your node v4.1.1, report it to https://github.com/xiangshouding/node-pngcrush/issues
............................. 3094ms

**Comment by zhangtao07** [comment]
fis已升级支持 node 4.1.1，不是给了 issue 链接哈，重新安装fis 即可
