### ISSUE TITLE
多次安装fis3都出现同样的错误，找了很多方法也不行，系统 OS X EI  Capitan 版本10.11

### ISSUE THREAD

**Issue by dxhuii** [fex-team/fis#672]
命令行错误提示：

plaindeMacBook-Pro:~ plain$ sudo npm install -g fis3
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "fis3"
npm ERR! node v0.12.4
npm ERR! npm  v3.3.8
npm ERR! code E404

npm ERR! 404 version not found: fis3 : registry
npm ERR! 404 
npm ERR! 404 'registry' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/plain/npm-debug.log

错误日志：

plaindeMacBook-Pro:~ plain$ vim /Users/plain/npm-debug.log 

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'fis3' ]
2 info using npm@3.3.8
3 info using node@v0.12.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData fis3
8 silly fetchNamedPackageData fis3
9 silly mapToRegistry name fis3
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://npm.tuna.tsinghua.edu.cn/registry
12 silly mapToRegistry uri http://npm.tuna.tsinghua.edu.cn/registry/fis3
13 verbose request uri http://npm.tuna.tsinghua.edu.cn/registry/fis3
14 verbose request no auth needed
15 info attempt registry request try #1 at 15:03:34
16 verbose request id 557890fa1f821611
17 http request GET http://npm.tuna.tsinghua.edu.cn/registry/fis3
18 http 404 http://npm.tuna.tsinghua.edu.cn/registry/fis3
19 verbose headers { server: 'nginx/1.8.0',
19 verbose headers   date: 'Mon, 19 Oct 2015 07:03:35 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'content-length': '41',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-powered-by': 'Sinopia/1.4.0',
19 verbose headers   etag: 'W/"29-47b538b5"',
19 verbose headers   vary: 'Accept-Encoding',
19 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6juR' }
20 silly get cb [ 404,
20 silly get   { server: 'nginx/1.8.0',
20 silly get     date: 'Mon, 19 Oct 2015 07:03:35 GMT',
20 silly get     'content-type': 'application/json; charset=utf-8',
20 silly get     'content-length': '41',
20 silly get     connection: 'keep-alive',
20 silly get     'x-powered-by': 'Sinopia/1.4.0',
20 silly get     etag: 'W/"29-47b538b5"',
20 silly get     vary: 'Accept-Encoding',
20 silly get     'x-status-cat': 'http://flic.kr/p/aV6juR' } ]
21 silly fetchPackageMetaData Error: version not found: fis3 : registry
21 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
21 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
21 silly fetchPackageMetaData     at Request.emit (events.js:110:17)
21 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
21 silly fetchPackageMetaData     at Request.emit (events.js:129:20)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
21 silly fetchPackageMetaData     at IncomingMessage.emit (events.js:129:20)
21 silly fetchPackageMetaData     at _stream_readable.js:908:16
21 silly fetchPackageMetaData  error for fis3 { [Error: version not found: fis3 : registry] pkgid: 'registry', statusCode: 404, code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: version not found: fis3 : registry
27 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose statusCode 404
29 verbose pkgid registry
30 verbose cwd /Users/plain
31 error Darwin 15.0.0
32 error argv "node" "/usr/local/bin/npm" "install" "-g" "fis3"
33 error node v0.12.4
34 error npm  v3.3.8
35 error code E404
36 error 404 version not found: fis3 : registry
36 error 404
36 error 404 'registry' is not in the npm registry.
36 error 404 You should bug the author to publish it (or use the name yourself!)
36 error 404
36 error 404 Note that you can also install from a
36 error 404 tarball, folder, http url, or git url.
37 verbose exit [ 1, true ]

**Comment by xiangshouding** [comment]
```
npm install -g fis3 --registry=https://registry.npmjs.org
```

换成官方源，你使用的源应该很久没有更新了。

**Comment by dxhuii** [comment]
@xiangshouding  谢谢，已经安装成功了。应该是源的问题。
