### ISSUE TITLE
使用fis在linux会报 [ERROR] undefined is not a function

### ISSUE THREAD

**Issue by iamllitog** [fex-team/fis#673]
![image](https://cloud.githubusercontent.com/assets/6738756/10597315/27de1430-7720-11e5-8489-906e331bcb94.png)

**Comment by hefangshi** [comment]
添加执行参数 --verbose 后再贴一下输出

**Comment by iamllitog** [comment]
![image](https://cloud.githubusercontent.com/assets/6738756/10599141/dd57f9be-7731-11e5-8cab-42d1b736ed4e.png)

**Comment by xiangshouding** [comment]
目测你输入的命令行参数有问题

**Comment by iamllitog** [comment]
fis release -mwlp -d ../ --verbose

**Comment by iamllitog** [comment]
0.0用不用把fis-config贴出来
