### ISSUE TITLE
win10下面 -watch命令失效

### ISSUE THREAD

**Issue by ForeverPx** [fex-team/fis#674]
在win10下，node版本为4.x，使用 fis release -wld local 命令后，能正确生成代码，但是修改文件时，fis并没有监听文件的改变。但是相同的项目在mac下就没问题。
求大神解答。

**Comment by xwenliang** [comment]
看看修改文件时，浏览器端的socket有没有报错，接收到消息没有

**Comment by ForeverPx** [comment]
跟浏览器没关系吧，我是在命令行里面用watch命令去监听文件改变并重新压缩js

**Comment by xwenliang** [comment]
看错了，以为你说的是浏览器没有刷新。这样的问题还没碰到过..等待官方的回答
