### ISSUE TITLE
fis怎么使用绝对路径，我们生产环境比测试环境路径多一层   

### ISSUE THREAD

**Issue by wangsj00** [fex-team/fis#676]
比如在生产环境引入资源目录结构是这样： 
/common
     -css
     -js
     -images

然后测试环境引入资源目录结构是这样： 
/project
   /common
         -css
         -js
        -images

用fis在测试环境打包发布后  到了生产环境，页面中的css ， js等文件的路径引入多了一层,那我不可能一个页面一个页面的去改吧
所以我想怎么能用绝对路径  把生产跟测试的引入都写成绝对路径   fis新人求教

**Comment by xwenliang** [comment]
可以使用fis的deploy，测试环境写一个配置，生产环境另一个配置，
如：
```
fis.config.merge({
    ....//其他配置省略
    deploy: {
        test: [
            {
                from:  '开发目录',
                to: '测试环境目录'
            }
        ],
        online:[
            {
                from: '开发目录',
                to: '线上环境目录'
            }
        ]
    }
});
```
详细见：[部署配置](https://github.com/fex-team/fis/wiki/%E9%85%8D%E7%BD%AEAPI#deploy)

**Comment by wangsj00** [comment]
我直接复制使用您写的配置，只需改一下路径，能否成功？ 详细的部署配置有些看不明白，但是我们领导又必须要用FIS
