### ISSUE TITLE
fis 安装失败

### ISSUE THREAD

**Issue by babyzhu** [fex-team/fis#677]
本来安装好fis。然后我fis server open 看到www自带的本地服务器里面存了很多用fis合并过的文件，然后我就手痒，把www里面的文件都删了，然后发现fis release就一直不能编译了，然后我就想是不是我删错东西了，就重新安装下fis。结果一直出现厦门的问题。
C:\Users\user>npm install fis -g --registry=http://registry.npm.taobao.org/
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "d:\\Program Files\\nodejs\\\\node.exe" "d:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "fis" "-g" "--registry=http://re
gistry.npm.taobao.org/"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\fis\node_modules\fi
s-command-server\lib
npm ERR! code EBUSY
npm ERR! errno -4082

npm ERR! EBUSY, rmdir 'C:\Users\user\AppData\Roaming\npm\node_modules\fis\node_m
odules\fis-command-server\lib'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY, rmdir 'C:\Users\user\AppData\Roaming\n
pm\node_modules\fis\node_modules\fis-command-server\lib'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY, rmdir 'C:\Users\user\AppData\Roami
ng\npm\node_modules\fis\node_modules\fis-command-server\lib']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   path: 'C:\\Users\\user\\AppData\\Roaming\\npm\\nod
e_modules\\fis\\node_modules\\fis-command-server\\lib' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

**Comment by xiangshouding** [comment]
```
 ERR! EBUSY
```

意思是，目标文件夹被其他程序占用。

这个问题在windows下很常见啊。
