### ISSUE TITLE
 fis3 release -d ./test  每次发布都在下一级目录test/test/test

### ISSUE THREAD

**Issue by wangsj00** [fex-team/fis#678]
比如我进入demo目录
cd d:/demo 
然后发布项目 
 fis3 release -d ./test 
目录结构是 d:/demo/test
但是我修改东西再次用 fis3 release -d ./test  或者（fis3 release）发布后
它都发布到了test的目录下 d:/demo/test/test 
每 fis3 release 一次都在test下， d:/demo/test/test/test/test 
请问怎么能让他每次发布都在 d:/demo/  下，覆盖前一次发布的

**Comment by 2betop** [comment]
因为 fis 默认是把当先项目下面的所有文件都参与编译，然后产出到指定目录，因为你产出指定的就是当前目录，以至于下次编译的时候，上一次的产出参与了编译，以至于你的产出目录里面又多了一级。

解决办法

1. 产出目录改成 output， fis 中默认把这个目录从项目编译列表中排除了。
2. 在 fis-conf.js 中设置把 test 目录加入到 project.exclude 配置中。详情看：http://fex-team.github.io/fis-site/docs/api/fis-conf.html#project

**Comment by wangsj00** [comment]
多谢，成功了，原来只能用output
