### ISSUE TITLE
绝对路径的引用可以加MD5戳吗？

### ISSUE THREAD

**Issue by wangsj00** [fex-team/fis#680]
比如图1引用绝对路径${cdn_trade }/static/css/public.css编译之后就无法添加MD5戳，路径也不会有任何变化，而第图2是相对路径，编译后自然一切正常，
图1
![qq 20151103160205](https://cloud.githubusercontent.com/assets/13344121/10903487/203e1c0e-8245-11e5-8af5-05b623fbeea6.png)
图二
![qq 20151103160746](https://cloud.githubusercontent.com/assets/13344121/10903486/203cac5c-8245-11e5-9ab7-b788d4bc098c.png)
图二编译后

![20151103161201](https://cloud.githubusercontent.com/assets/13344121/10903593/5d5abeca-8246-11e5-9fe8-0583bd0384ff.png)

请问有办法给（图1）绝对路径添加MD5戳吗？

**Comment by zhangtao07** [comment]
如果路径中带有动态运行时变量，编译器肯定无法识别这些 url.正确的做法应该是添加 domain 属性来给路径添加 cdn_trade,请参考相应文档

**Comment by wangsj00** [comment]
@zhangtao07  谢谢已经成功解决
