### ISSUE TITLE
fis2 和 fis3 使用csssprites后css文件md5值不正确

### ISSUE THREAD

**Issue by jasonHuang2532** [fex-team/fis#682]
1.fis2中，配置文件的roadmap.path中配置 useSprite: true。开启后，能正常合并雪碧图，但发现使用雪碧图的样式文件的文件名md5和该文件时间md5值不一致；useSprite设置为false是，md5是计算正确的。看了下文档，雪碧图样式插入到样式文件应该在计算md5后进行，所以导致了这个问题。如下图，js的md5是计算正确的，而css则计算错误。
![qq 20151116210312](https://cloud.githubusercontent.com/assets/2619524/11182399/79d11266-8ca5-11e5-8dd3-88d9d44bfc7d.png)
2.在fis3里面，启用雪碧图的样式文件md5值仍然算不对
![d 76 zzd 6jf2al59r xs](https://cloud.githubusercontent.com/assets/2619524/11200690/fc3328c6-8d12-11e5-9886-e1db48e2aaca.jpg)

**Comment by hefangshi** [comment]
你说的原因的确是对的，但是md5并不一定要保证绝对正确，而是要保证这样的md5能够代表在当前文件的状态下保持唯一。

比如说如果出现了你修改了一张图片，但是最后产出的style.css的md5戳没有变化，那么就是严重的问题，但是如果只是对应不上，其实无伤大雅。
