### ISSUE TITLE
fis加md5功能bug

### ISSUE THREAD

**Issue by qianjunsteve** [fex-team/fis#685]
现有需求对html文件加useHash。
但是发现md5加入时机是对原文件，并不是对合并之后的文件状态进行判断。
导致一个问题：若我只修改js、css文件，autoload和simple之后，不会改变html的md5值。

**Comment by hefangshi** [comment]
参考 https://github.com/fex-team/fis/issues/682

**Comment by qianjunsteve** [comment]
我看了这个issue，但是也没有解决方案啊，岂不是每次都要在html中修改注释以改变页面的md5？
