### ISSUE TITLE
配置cnpm时报错，git clone undefined

### ISSUE THREAD

**Issue by LT5505** [fex-team/fis#686]
输入的命令为：npm install -g cnpm --registry=https://registry.npm.taobao.org
结果报错，之后的安装ionic什么也都不行啦
![ss rj39ny37eczro 4ro v0](https://cloud.githubusercontent.com/assets/6197224/11331846/ed1142dc-91fa-11e5-9193-bb555398615b.png)

**Comment by xiangshouding** [comment]
安装 fis 并不想要 git 环境，请排查下是否别的什么东西导致这个错误。

**Comment by Loyalsoldier** [comment]
那就试试安装 Git 呗

**Comment by LT5505** [comment]
我装了git，git没有问题
