### ISSUE TITLE
video标签的poster如何实现资源定位

### ISSUE THREAD

**Issue by win7killer** [fex-team/fis#688]
看到有对video的src做资源定位，但是poster却没有，有没有可以自己定义的接口之类的

**Comment by zhangtao07** [comment]
目前只对固定的一些标签和标记提供了资源定位功能，fis中有一个黑魔法定位标签不过并不建议使用(fis3中去除了)。
不过其实你也可以很简单的实现插件扩展，例如可以试试这个插件： https://www.npmjs.com/package/fis-postpackager-extras_uri
