### ISSUE TITLE
自动合并

### ISSUE THREAD

**Issue by xiaoshanqiu** [fex-team/fis#689]
最近在使用fis3工具时遇到个文件处理的问题
例子：
情景: 自动合并1个文件时 例如  
  postpackager: fis.plugin('loader', {
        allInOne: true
    })  
期望结果：某些文件（a.js  b.css c.png）在自动合并的时候不做任何处理（不自动合并）  

请教下大神，怎样配置才能实现此要求？

**Comment by 2betop** [comment]
有 ignore 参数，去 这查下： https://github.com/fex-team/fis3-postpackager-loader

**Comment by xiaoshanqiu** [comment]
谢啦!!☆⌒(*＾-゜)v
