### ISSUE TITLE
模块加载

### ISSUE THREAD

**Issue by xShanQiu** [fex-team/fis#690]
你好，我在使用fis3 release jsp模板的时候遇到个问题
例子： 
情景：模块使用了 mod.js ，页面使用 jsp ， 
使用fis3  release 之后 jsp 文件并没有把require的文件 生成script 标签在页面上，因此导致了 require找不到模块，换成html 文件就正常了。
附上fis 配置
fis.hook('commonjs');
fis.match('/modules/*_.js', {
    isMod: true
});
fis.match('::package', {
    spriter: fis.plugin('csssprites')
});
fis.match('_.css', {
    useSprite: true
});
fis.match('_.js', {
    optimizer: fis.plugin('uglify-js')
});
fis.match('_.css', {
    optimizer: fis.plugin('clean-css')
});
fis.match('_.png', {
    optimizer: fis.plugin('png-compressor')
});
fis.match('_', {
    release: 'LotteryGame/gdActive/$0'
});
fis.match('::package', {
    postpackager: fis.plugin('loader', {
        allInOne: false
    })
});
fis.match('_.less', {
    parser: fis.plugin('less'),
    rExt: '.css'
});
fis.media('debug').match('_.{js,css,png}', {
 useHash: false,
 useSprite: false,
 optimizer: null
 });

求解大神，使用jsp模板和mod.js时候是否要做特殊的配置。

**Comment by xiangshouding** [comment]
需要特殊配置，详细请看 https://github.com/fex-team/jello#html
