### ISSUE TITLE
在JS中定位html资源失败

### ISSUE THREAD

**Issue by cypmeen** [fex-team/fis#692]
function goLimit(){
        var logo = __uri('img/arrow.png');
        console.log("logo = " + logo);
        window.location.href= __uri('limit.html');

```
}
```

我使用__uri("img/arrow.png")资源时，编译出的结果还是img/arrow.png实际上我的图片名字已经是arrow_1554048.png了。为什么？

**Comment by xiangshouding** [comment]
因为你写的图片路径有问题啊，编译是找不到；

**Comment by cypmeen** [comment]
function goMoneyRepay(){
        window.location.href= __uri('/app/lending/money_repay.html');
    }
我最主要的目的是html资源的跳转到money_repay_b13e5be.html，/app/lending/money_repay.html'这个路径是我fis3编译前的路径，之前这个相对路径是能跑通的，官方文档只是叫我在相对路径加一个__uri(path)函数，编译后查看是没有加md5的名字，为什么？
