### ISSUE TITLE
请问deploy插件什么时候开放

### ISSUE THREAD

**Issue by ilife5** [fex-team/fis#693]
如 #62 中描述，打算开放 fis-deploy-rsync 的插件实现，请问现在是否有计划？

**Comment by zhangtao07** [comment]
fis2&3 早已开放，请查看相应的插件。 
 - fis2 : http://fex.baidu.com/fis-site/docs/api/fis-conf.html#deploy
 - fis3:  http://fis.baidu.com/fis3/docs/api/dev-plugin.html 查看 deploy 插件

**Comment by ilife5** [comment]
好的，谢谢，目前没有找到 fis-deploy-rsync 插件

@zhangtao07 请问是否已经有该插件，我没有找到。

**Comment by zhangtao07** [comment]
貌似是没有这个，请按照现有的类似插件撸一个~https://www.npmjs.com/package/fis-deploy-ftp
