### ISSUE TITLE
资源定位

### ISSUE THREAD

**Issue by Elaine87** [fex-team/fis#694]
两个模块，common, home；
在common的一个js文件中引用home文件的js：var $ = require('home:widget/lib/jquery/jquery.js'), 报错，说找不到资源Error：Uncatch [ModJs], 找不到 ('home:widget/lib/jquery/jquery.js')，但是在common.map.json中是有这个资源地址的，而且通过map中的url也能找到jquery.js,但是就是报错，请帮忙解答，只有js引用会出现问题，home中的vm是可以引用的

**Comment by 2betop** [comment]
后端是啥程序？

**Comment by Elaine87** [comment]
java

**Comment by 2betop** [comment]
home.vm 里面有没有加个 `#require('./home.vm')` 自我依赖的语句？

**Comment by Elaine87** [comment]
加了。
结构如下：
home
    .....
    jquery.js
      
common
   page
       index.vm
   widget
        init
           init.vm
           init-async.js

我在index.vm中通过#widget引入了init.vm
init-async.js从network 已经看到加载了，但是init-async.js 执行的时候报错，因为var $ = require('home:widget/lib/jquery/jquery.js')找不到资源。可是我在index.vm中通过#requre('home:widget/lib/jquery/jquery.js)这种方式就可以找到该资源。很奇怪的一个问题！！

**Comment by 2betop** [comment]
你把你代码提供一下？通过 github 仓库

**Comment by Elaine87** [comment]
ps:内部系统，代码不方便贴出来，不好意思
不过现在问题我暂时用不完美方案解决了
我把vm页面的js初始化由异步改成同步，把所有引用的home模块并且找不到的资源都在init-asyn.js里面初始化，就可以引用home里面的资源了
<prev><code>
#script()
    require.async("./init-async.js", function(init){
        init()
      })
	===> var init = require("./init-async.js");
	               init();
#end
</code></prev>
我不确定这是不是跟我使用了路由有关系
