### ISSUE TITLE
js文件添加md5戳编译后 在多个html头部包裹的jsMD5戳文件名既然不一样

### ISSUE THREAD

**Issue by cypmeen** [fex-team/fis#695]
<script src="../js/configuration_1424972.js"></script>

<script src="../js/configuration_7c7c8e6.js"></script>

实际configuration的名字是configuration_1424972.js
以下是此js的实现
//html资源整合
var res_home_html = __uri('../home.html');
var res_addition_html = __uri('../addition.html');
var res_buy_php_html = __uri('../buy_php.html');
var res_confirm_html = __uri('../confirm.html');
var res_credit_money_html = __uri('../credit_money.html');
var res_education_html = __uri('../education.html');
var res_eligibility_html = __uri('../eligibility.html');
var res_facebook_html = __uri('../facebook.html');
var res_history_html = __uri('../history.html');
var res_home_html = __uri('../home.html');
var res_lending_html = __uri('../lending.html');
var res_money_repay_html = __uri('../money_repay.html');
var res_remittance_html = __uri('../remittance.html');
var res_repay_list_html = __uri('../repay_list.html');
var res_repayment_record_html = __uri('../repayment_record.html');
var res_request_1_html = __uri('../request_1.html');
var res_request_2_html = __uri('../request_2.html');
var res_request_3_html = __uri('../request_3.html');
var res_request_4_html = __uri('../request_4.html');
真搞不懂为什么？

**Comment by cypmeen** [comment]
例如在home.html中<script src = "configuration_1424972.js"></script>
而在addtion.html中却是<script src = "configuration_7c7c8e6.js"></script>

**Comment by cypmeen** [comment]
在home.html中src为 configuration_1424972.js
而在addtion.htmlsrc为 configuration_7c7c8e6.js

**Comment by zhangtao07** [comment]
无法复现，请删除产出添加-c 重试
