### ISSUE TITLE
requirejs中paths的路径问题

### ISSUE THREAD

**Issue by atmfans** [fex-team/fis#696]
请教一下，在requirejs中，path配置路径是不需要加.js后缀的，这样即使用__uri()也不能匹配路径，请问有什么解决办法

**Comment by 2betop** [comment]
分两步走？

1. var target = __uri('xxxx.js');
2. require.config({paths: {xxx: target.replace(/\.js$/, '')}});

**Comment by hdyks8** [comment]
请问楼主最后是怎么解决的？ require的config里paths一定要这样去定义吗？ 这样每新增一个js文件不是都要修改一下这个文件，不是可以自动生成么？
