### ISSUE TITLE
fis3安装配置问题

### ISSUE THREAD

**Issue by kxbrand** [fex-team/fis#697]
电脑是win7 64位系统;java及php-cgi环境都已安装。
如果用`fis server start`，(fis2)可以打开浏览器，可以访问php及jsp页面。
![fis2](https://cloud.githubusercontent.com/assets/6490138/11649846/568d76c6-9dbe-11e5-80c3-8561531492d8.jpg)

但是用`fis3 server start`，可以打开浏览器，但是不能访问php及jsp页面。
![fis3](https://cloud.githubusercontent.com/assets/6490138/11649850/5cd3d91c-9dbe-11e5-9da5-cdd6a55d1b5e.jpg)

**Comment by zhangtao07** [comment]
fis3的问题建议在 fis3项目里提问。

你这个是因为 fis3默认开启的 nodejs 调试服务器，这样不需要安装 php-cgi和 java 也能调试纯前端的一些项目。如果需要开启 php 服务器执行 `fis3 server start --type smarty ` ( fis3 >= 3.2.6)

详细说明可见相关插件文档,如https://github.com/fex-team/fis3-smarty
