### ISSUE TITLE
用fis-deploy-tar 打包多出个map.json文件

### ISSUE THREAD

**Issue by shekobe** [fex-team/fis#699]
大家好，问下， 
我设置是这样的

fis.config.set('modules.deploy', ['default', 'tar'])
fis.config.set('settings.deploy.tar', {
    publish : {
        from : '/',
        to: '/',
        gzip: true,
        level: 0, //压缩质量 0-9，越大压缩比越高
        memLevel: 9, //压缩使用的内存量 1-9， 越大占用内存越多，执行速度越快
        file: './output.tar.gz'
    }
});

打包产出的时候，在output目录下多出个map.json文件，是哪里还需要设置吗

**Comment by hefangshi** [comment]
你是说最后的 output 目录内除了 tar 包，还会产出一个 map.json

还是说 tar 包内有 map.json

**Comment by shekobe** [comment]
之前用fis-deploy-tar插件， tar 包内有 map.json  ， 后面我用 fis3-deploy-tar插件打包就没问题了

**Comment by hefangshi** [comment]
这是因为fis2默认就会产出map.json，而fis3默认不会

这一点和打包插件无关。
