### ISSUE TITLE
我从git上拿过来的fis3-test-amd例子无法运行,fis.set是undefined

### ISSUE THREAD

**Issue by sabver** [fex-team/fis#700]
fis-conf.js的代码和fis3-test-amd上面的一模一样，然而当我执行指令的时候，出现以下错误：
![image](https://cloud.githubusercontent.com/assets/6829063/11709746/1287c9d4-9f55-11e5-898d-feb86d57e8b2.png)
从错误来看，应该是fis.set是undefined，另外我也打印过fis.plugin对象，它也是undefined，请问造成这种情况的原因是什么？
附上fis3的版本信息：
![image](https://cloud.githubusercontent.com/assets/6829063/11709793/68daf478-9f55-11e5-8ddf-c6d47e587536.png)
附上文件目录结构：
![image](https://cloud.githubusercontent.com/assets/6829063/11709810/8ed8ca56-9f55-11e5-8373-069b03c38c40.png)

**Comment by 2betop** [comment]
造成这个的原因是 fis 去跑 fis3 的项目，fis3 的项目要用 fis3 命令，不是 fis 命令
