### ISSUE TITLE
fis的静态资源部署问题？

### ISSUE THREAD

**Issue by zlxbuzz** [fex-team/fis#701]
目前有多个前端项目 ，每个项目都依赖自身项目的img,js,css目录下的文件。如何通过fis将所有项目的这些静态文件都放到一个公共的目录下，比如
img:
   项目1.png
   项目2.png
js ：
  项目1.js 
  项目2.js
??

**Comment by zhangtao07** [comment]
fis2可查看 roadmap [配置文档](http://fex.baidu.com/fis-site/docs/advance/roadmap.html)
fis3 查看 relase [配置](http://fis.baidu.com/fis3/docs/api/config-props.html#release)

**Comment by zlxbuzz** [comment]
你好 ，主要用的是fis2，我主要卡在代码的部署上，如何将静态资源放到公共的static里面，用deploy吗？是否会造成文件冲突等问题？？谢谢

**Comment by zhangtao07** [comment]
可以用deploy,例如 http-push、ftp、git 等方式，至于文件冲突一般静态资源都会设置md5，不同的文件生成的 md5值不会一样。另外部署的时候一般会通过 release设置产出规则。例如不同的项目放置在不同的子文件夹内。
