### ISSUE TITLE
为什么fis release之后，根目录下没有构建产出呢，指定目录也不行，好纠结

### ISSUE THREAD

**Issue by miemiewang** [fex-team/fis#704]

**Comment by fouber** [comment]
```
fis release -d [要产出的目录]
```

不加-d参数，就发布到fis的内置调试服务器目录下了

**Comment by miemiewang** [comment]
但是内置的目录下面也没有

**Comment by xwenliang** [comment]
fis server open 打开的目录里面也没有吗

**Comment by miemiewang** [comment]
对啊，我都崩溃了，可能操作有问题吧，但是不知道是什么

**Comment by fouber** [comment]
@miemiewang 

该不会是你的配置配的所有文件都release为false了吧？

**Comment by miemiewang** [comment]
没有动配置文件呀，唉我是小白，才开始用，哪位大神可以带我飞一下，感激涕零

**Comment by miemiewang** [comment]
没有动配置文件，怎么办呢

**Comment by xiangshouding** [comment]
配置文件拿上来看看 `fis-conf.js`

**Comment by miemiewang** [comment]
fis.config.set('settings.spriter.csssprites.margin', 20);

// 取消下面的注释开启simple插件，注意需要先进行插件安装 npm install -g fis-postpackager-simple
// fis.config.set('modules.postpackager', 'simple');

// 取消下面的注释设置打包规则
fis.config.set('pack', {
    '/pkg/lib.js': [
        'js/lib/jquery.js',
        'js/lib/underscore.js',
        'js/lib/backbone.js',
        'js/lib/backbone.localStorage.js',
    ]
    // 取消下面的注释设置CSS打包规则，CSS打包的同时会进行图片合并
    // '/pkg/aio.css': '**.css'
});

// 取消下面的注释可以开启simple对零散资源的自动合并
// fis.config.set('settings.postpackager.simple.autoCombine', true);

**Comment by miemiewang** [comment]
我主目录下的文件和那个姐姐讲的教程里显示的不一样，每次用fis server open打开都是那些文件

**Comment by miemiewang** [comment]
我好像懂了●▁●,谢谢解答
