### ISSUE TITLE
fis是如何require全局安装的插件的？

### ISSUE THREAD

**Issue by aj4g** [fex-team/fis#708]
比如我觉得现有的扩展点不够，
我要在编译开始前从某个url下载一些文件，
于是写一个node程序并在fis-config.js中直接调用，
如果这个node程序是用-g参数安装的，在fis-config.js中调用会报找不到

var downloader = require("fis-before-all");
downloader( ... );

请问fis加载插件的代码位置？

**Comment by zhangtao07** [comment]
这种做法不建议加入到编译流程中，直接加到 shell 脚本中即可，例如有个上线脚本，编译前先加载东西，然后再执行编译。现在的编译流程也不支持这种异步的操作

**Comment by aj4g** [comment]
如果用一个bat执行编译流程
@echo off
download "my-download-file-list-path"
fis release

download是node程序，发现download执行成功后bat文件直接退出了，貌似是node把当前线程停掉了

**Comment by zhangtao07** [comment]
请养成写Linux shell脚本的习惯，毕竟大部分服务器都是linux系统。bat 脚本在第三方程序前加call试试，具体可以搜索相关文档。

**Comment by benjamin-zuo** [comment]
一方面你可以开发基于fis的插件，发布到npm，然后安装就可以了。具体可以看看官方文档。
