### ISSUE TITLE
FIS3 sass安装出错

### ISSUE THREAD

**Issue by lichuan02** [fex-team/fis#709]
执行 npm install -g fis3-parser-node-sass

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.0/darwin-x64-node-4.0/binding.node

> node-sass@2.0.0 postinstall /usr/local/lib/node_modules/fis3-parser-node-sass/node_modules/node-sass
> node scripts/build.js

module.js:338
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/fis3-parser-node-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
Build failed

**Comment by zhangtao07** [comment]
插件名称是 fis-parser-node-sass，可以去fis首页搜索或者npm搜索
