### ISSUE TITLE
fis对同文件多项目共存的项目的打包优化策略应该如何？

### ISSUE THREAD

**Issue by Zjingwen** [fex-team/fis#712]
场景
* 所有项目都是在一个文件目录。有pc，webapp，cms。
* 现在要求对这3个项目进行分割管理，pc、cms端使用的是未模块化做法。webapp使用的是模块化做法。
问题
* 对3个项目进行不同的优化打包策略，能否实现用多个fis-conf.js文件，进行配置。
* 如果不能实现多个fis-conf.js文件的话，要如何分割管理策略。

**Comment by benjamin-zuo** [comment]
每个模块建个fis-conf.js,可对不同项目采用不同打包策略

**Comment by Zjingwen** [comment]
@benjamin-zuo 
直接在对应cms，pc，webapp目录下，新建不同的fis-conf.js文件？
每次fis release的时候，就进入相应目录执行命令？

**Comment by benjamin-zuo** [comment]
@Zjingwen 可以的，当项目分模块管理时，很常见的方式，比如可能会有common模块、module01、module02、...，现在fis还不支持一条命令可以同时编译多个模块。
