### ISSUE TITLE
packTo之后的css文件，带有／＊＊／的注释，压缩过后也存在，是否能去除。

### ISSUE THREAD

**Issue by Zjingwen** [fex-team/fis#713]
![image](https://cloud.githubusercontent.com/assets/8531277/12133047/8724c0a0-b45c-11e5-846d-8cc7e7733343.png)

**Comment by 2betop** [comment]
看这里面的配置项： https://github.com/fex-team/fis3-packager-map

**Comment by Zjingwen** [comment]
@2betop 
报错： [ERROR] reg.test is not a function
 代码：packager: fis.plugin('map',{
            useTrack : false,
            'public/mm/static/css/module.less':
            [/^\/public\/mm\/components\/(.*\.less)$/i],
        })
正则检查多次，没有错误。

**Comment by 2betop** [comment]
fis3 版本问题

**Comment by Zjingwen** [comment]
@2betop 
我现在的版本是3.3.0
是要降版本嘛？降至什么版本才可以？

**Comment by 2betop** [comment]
https://github.com/fex-team/fis3/releases/tag/3.3.1 这个版本之后才支持的这个功能。
