### ISSUE TITLE
关于压缩图片的问题

### ISSUE THREAD

**Issue by joy-yi0905** [fex-team/fis#714]
我尝试了用FIS压缩图片，都是png格式。但发现压缩完后，效果并不像使用 tingpng 那么明显，fis几乎好像没怎么处理图片压缩，

https://www.npmjs.com/package/fis 这上面说内置 png图片压缩插件，具有极高的性能

难道是我弄错了，请问这个正常吗？

**Comment by zhangtao07** [comment]
这里说的性能是执行性能(因为c编写)，不是压缩比，压缩比是可配置的。png 压缩插件使用的是业界出名的pngquant，关于跟tingpng的一些对比可以插件一些文章，例如这个http://pointlessramblings.com/posts/pngquant_vs_pngcrush_vs_optipng_vs_pngnq/
