### ISSUE TITLE
js中引用相对路径文件，文件路径中包含变量

### ISSUE THREAD

**Issue by liuhanqu** [fex-team/fis#717]
代码如下：
num = 1
img = new Image()
img.src = __uri("../img/wish-" + num +".jpg")

会出现错误
Uncaught ReferenceError: __uri is not defined

**Comment by 2betop** [comment]
这是编译指令，只支持字面量。不支持变量。

不过你可以这么写

```
var map = [
  __uri('../img/wish-0.jpg'),
  __url('../img/wish-1.jpg')
];

var num = 1;
var img.src = map[num];
```
