### ISSUE TITLE
FIS的hash签名和RequireJS、ModJS代码自动封装一起使用的问题

### ISSUE THREAD

**Issue by hdyks8** [fex-team/fis#720]
用FIS的Mod进行代码的自动包裹的时候，define的模块是未进行HASH签名的文件名生成的，与实际构建出来的文件名不一致，而RequireJS要求define的模块名和文件名要一致吧，这样导致在运行时找不到js文件。请问怎么破？

**Comment by 2betop** [comment]
是存在不一致的问题，但是如果有转换表就没事。比如：

```js
require.config({paths: {
  'module/a': 'module/a_3434343'
}})
```

以上这个表应该是自动生成的，你得检查下你那为何没有这个表。

**Comment by hdyks8** [comment]
这个文件是FIS构建的时候会产出的吗？以下是我的配置，谢谢
fis.match('*.{js,css,png}', {
	useHash: true
});
fis.match('*.{js,css,png}', {
	release: '$0'
});
fis.hook('commonjs');
fis.match('/modules/**.js', {
	isMod: true
});
fis.match('::package', {
	postpackager: fis.plugin('loader', {})
});

**Comment by hdyks8** [comment]
这个文件是FIS构建的时候会产出的吗？以下是我的配置，谢谢
fis.match('.{js,css,png}', {
useHash: true
});
fis.match('.{js,css,png}', {
release: '$0'
});
fis.hook('commonjs');
fis.match('/modules/**.js', {
isMod: true
});
fis.match('::package', {
postpackager: fis.plugin('loader', {})
});

发件人: liaoxuezhi [mailto:notifications@github.com]
发送时间: 2016年1月19日 11:33
收件人: fex-team/fis
抄送: 颜昊
主题: Re: [fis] FIS的hash签名和RequireJS、ModJS代码自动封装一起使用的问题 (#720)


是存在不一致的问题，但是如果有转换表就没事。比如：

require.config({paths: {

  'module/a': 'module/a_3434343'

}})

以上这个表应该是自动生成的，你得检查下你那为何没有这个表。

—
Reply to this email directly or view it on GitHub<https://github.com/fex-team/fis/issues/720#issuecomment-172728177>.




********************************************************************************************************************************
The information in this email is confidential and may be legally privileged. If you have received this email in error or are not the intended recipient, please immediately notify the sender and delete this message from your computer. Any use, distribution, or copying of this email other than by the intended recipient is strictly prohibited. All messages sent to and from us may be monitored to ensure compliance with internal policies and to protect our business. 
Emails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with us by email is taken to accept these risks. 

收发邮件者请注意：
本邮件含保密信息，若误收本邮件，请务必通知发送人并直接删去，不得使用、传播或复制本邮件。
进出邮件均受到本公司合规监控。邮件可能发生被截留、被修改、丢失、被破坏或包含计算机病毒等不安全情况。 
********************************************************************************************************************************

**Comment by 2betop** [comment]
你用的是什么模块化方案？如果你用的是 amd 方案，不知道你用的 require.js 是否起完整的文件名就是 `require.js`, 如果不是，你需要告诉 loader 生成的 resourceMap 是什么格式。注意看 loader  `resourceType ` 参数配置。另外，fis3-demo 里面有现有的栗子你可以参考参考

**Comment by hdyks8** [comment]
我是用的require.min.js, 文件名加密后变为require.min_0cb51c1.js
fis.match('::package', {
         postpackager: fis.plugin('loader', {
                   resourceType: 'amd',
                   useInlineMap: true
         })
});

生成的ResourceMap如下：
{
    "res": {
        "lib/require.js": {
            "uri": "/lib/require.js",
            "type": "js"
        },
        "main.js": {
            "uri": "/main.js",
            "type": "js"
        },
        "modules/index.js": {
            "uri": "/modules/index_e60f75f.js",
            "type": "js",
            "extras": {
                "moduleId": "modules/index"
            },
            "deps": [
                "modules/util.js"
            ]
        },
        "modules/util.js": {
            "uri": "/modules/util_1c08bd4.js",
            "type": "js",
            "extras": {
                "moduleId": "modules/util"
            }
        },
        "resMap.js": {
            "uri": "/resMap_8b006f5.js",
            "type": "js"
        }
    },
    "pkg": {}
}

发件人: liaoxuezhi [mailto:notifications@github.com]
发送时间: 2016年1月19日 14:54
收件人: fex-team/fis
抄送: 颜昊
主题: Re: [fis] FIS的hash签名和RequireJS、ModJS代码自动封装一起使用的问题 (#720)


你用的是什么模块化方案？如果你用的是 amd 方案，不知道你用的 require.js 是否起完整的文件名就是 require.js, 如果不是，你需要告诉 loader 生成的 resourceMap 是什么格式。注意看 loader resourceType 参数配置。另外，fis3-demo 里面有现有的栗子你可以参考参考

—
Reply to this email directly or view it on GitHub<https://github.com/fex-team/fis/issues/720#issuecomment-172758042>.




********************************************************************************************************************************
The information in this email is confidential and may be legally privileged. If you have received this email in error or are not the intended recipient, please immediately notify the sender and delete this message from your computer. Any use, distribution, or copying of this email other than by the intended recipient is strictly prohibited. All messages sent to and from us may be monitored to ensure compliance with internal policies and to protect our business. 
Emails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with us by email is taken to accept these risks. 

收发邮件者请注意：
本邮件含保密信息，若误收本邮件，请务必通知发送人并直接删去，不得使用、传播或复制本邮件。
进出邮件均受到本公司合规监控。邮件可能发生被截留、被修改、丢失、被破坏或包含计算机病毒等不安全情况。 
********************************************************************************************************************************
