### ISSUE TITLE
fis3资源定位时，url多一个/的问题

### ISSUE THREAD

**Issue by libofei2004** [fex-team/fis#721]
我引用资源的url调试情况下是<link rel='stylesheet' href='./../../css/color.css'/>
使用fis输出后
fis.match('*', {
  release: '/dist/$0',
  url:'/pack/dist/$0'
});
url变成了<link rel='stylesheet' href='/pack/dist//css/color.css'/>
，多了一道“/”，请问这是为什么？

**Comment by zhangtao07** [comment]
更详细点？哪里多了"/"，注意 FIS 产出默认是绝对路径

**Comment by libofei2004** [comment]
哦，链接没有给我显示出来啊，就是这样的路径src="./../../js/tongji.js"，
输出后变成了/pack/dist//js/tongji.js

**Comment by zhangtao07** [comment]
fis 中的路径都是从/开始的，所以 match 配置建议也从/开始写起，参见[文档](http://fis.baidu.com/fis3/docs/api/config-glob.html)

所以改成这样就行了：

```js
fis.match('/*', {
    release: '/dist/$0',
    url:'/pack/dist/$0'
});
```

实际使用中，一个*不能匹配多级目录，而且一般只有静态资源才需要重新指定 url 吧，所以一般用到是类似这样：

```js
fis.match('/(**.{css,js})', {
      release: '/dist/$1',
      url: '/pack/dist/$1'
})
```

更多 glob 分组匹配的说明和 fis 的扩展参考上面的文档

**Comment by libofei2004** [comment]
明白了，多谢！
