### ISSUE TITLE
fis是否可以全局替换字符串？

### ISSUE THREAD

**Issue by libofei2004** [fex-team/fis#723]
请问fis是否具备全局替换字符串的功能？即可以批量地将页面或js文件里标记过的字符串替换成指定的某个字符串？

**Comment by zhangtao07** [comment]
社区有不少replace插件，请去官网插件搜索，另外自己简单实现一个也快https://gist.github.com/zhangtao07/28d2db7e1816f6518eb0

**Comment by libofei2004** [comment]
谢谢
