### ISSUE TITLE
请教，如何自定义打包输出目录及文件名？

### ISSUE THREAD

**Issue by vrbvillor** [fex-team/fis#724]
各位大拿好，我之前用GRUNT，然后它总丢包，路径也乱七八糟的，经常是写完好使，打完包丢东西，然后我就转来用FIS了，但找了半天找不到如何定义打包后的输出目录及文件名，它总是生成PKG/页面名_aio.js，我用的是SEAJS，我在FIS的文档里边找了半天也没找到控制输出目录及文件名的方法，帮我找下，或回复写上方法吧，谢谢啦，^3^

加一句，我是想按文件打包没错，跟默认的打包方法一样，但是想自己设置目录跟文件名。而且生成的HTML文件中，所有的文件都以站点根目录为起始，也就是说fis过的文件一定要发布到站点根目录上吗？因为我使用fis3 release -d ./dist 之后，里边的代码都改成/pkg/xxxxxx了，而不是/dist/pkg/xxxx。

还有，如何给media设置多个名字？因为有的时候，我只改了less就只想编译css，但有的时候想全部编译css跟js，目前的文档上只写media能定一个名字，有没有可能使用这样：

``` javascript
fis.media("all js",{});
fis.media("all css",{});
```

然后编译的时候，可以使用 fis3 release js -d 只编译JS，也可以使用 fis3 release all -d 来编译全部文件？

**Comment by zhangtao07** [comment]
你确定找了半天？起步 demo 里面就讲了[资源定位](http://fis.baidu.com/fis3/docs/beginning/release.html#%E8%B5%84%E6%BA%90%E5%AE%9A%E4%BD%8D)，另外还有 fis-demo(顶部导航)里面有很多 demo

**Comment by vrbvillor** [comment]
我只看到release啊，packager的输出在哪里啊？

**Comment by vrbvillor** [comment]
我找到这个   https://github.com/fex-team/fis3-postpackager-loader#配置说明

配置项目`allInOne`下边的`js`里边只说明了有${filepath}，请问如何把它里边的`.html`去掉？我想只生成`xxxx.js`这种文件名。

**Comment by zhangtao07** [comment]
- [packTo](http://fis.baidu.com/fis3/docs/api/config-props.html#packTo)控制文件打包后产出在哪，其他请先了解下基本属性，loader 是纯前端项目中用来收集和替换页面静态资源的
 - 发布到本地和远端机器有多个插件支持,参考[这里](http://fis.baidu.com/fis3/docs/api/dev-plugin.html#Deploy%20%E6%8F%92%E4%BB%B6)，默认发布到本地调试服务器目录，可以指定。也可以直接-d 指定本地某个目录
 - media可以多个，不过编译开启 watch 本来就是按需编译，不需要也不建议通过 media的方式进行
