### ISSUE TITLE
js文件中 __uri资源定位失效

### ISSUE THREAD

**Issue by libofei2004** [fex-team/fis#726]
页面引入的js中有如下语句
var dprset = [
               __uri('./../../css/font1x.css'),  
               __uri('./../../css/font2x.css'),
               __uri('./../../css/font3x.css')
            ];
fis有已配置路径
fis.match('*', {
  release: '/dist/$0',
  url:'/dist$0'
});
但构建后，路径并没有被成功替换，变成了这样，这是为什么呢？
n=["./../../css/font1x.css","./../../css/font2x.css","./../../css/font3x.css"]

**Comment by hefangshi** [comment]
设置的路径在源代码中无法找到就会这样

**Comment by libofei2004** [comment]
这是因为fis无法知道该js文件被哪个页面引用吧？也就无法得知相对页面的路径。

**Comment by hefangshi** [comment]
不是这样的，说的是源代码的路径关系

**Comment by libofei2004** [comment]
你是指代码中的./../../css/font1x.css文件的实际位置吗

**Comment by xiangshouding** [comment]
@libofei2004 你先把你的文件层级给出来啊，不然很难判断路径应该是啥样子的。

**Comment by libofei2004** [comment]
目录结构是这样的debug/css/font1x.css，js为debug/js/font.js, 页面为debug/modules/dosomething/do.html这个样子。js里会动态地把dprset 里的css文件append到页面上。

**Comment by jiajianrong** [comment]
换成绝对路径试试？
最前面加 /
比如 /static/css/mod/a.css
