### ISSUE TITLE
demo can not work

### ISSUE THREAD

**Issue by DophinL** [fex-team/fis#727]
https://github.com/fex-team/fis-components-demo

I follow the steps,but still didn't work.

![image](https://cloud.githubusercontent.com/assets/8707316/12712144/0fd512e8-c901-11e5-8382-f2c635176fb5.png)
![image](https://cloud.githubusercontent.com/assets/8707316/12712162/43ad12c8-c901-11e5-8299-15c49b193376.png)

**Comment by hefangshi** [comment]
https://github.com/fex-team/fis3-demo/tree/master/components-mod-demo

**Comment by DophinL** [comment]
thank u!
