### ISSUE TITLE
使用fis，页面拆分为几个widget，widget下的css、js等是什么时候引入到页面并且改变版本号的

### ISSUE THREAD

**Issue by oAllenWu** [fex-team/fis#728]
![s5 w9 _7sdw_ l 6 r7 fax](https://cloud.githubusercontent.com/assets/9586345/13286288/5473362c-db3b-11e5-8960-5cdceedb2d0e.png)
比如我页面有包含这个widget，但是release之后，我看到page页面或者这个widget下tpl文件跟源码是一样的。请问一下，widget对应的静态资源文件是在什么时候引入的

**Comment by xiangshouding** [comment]
你应该是用的 [fis-plus](https://github.com/fex-team/fis-plus)

- 静态编译阶段只会根据必要的**标识符**来生成依赖关系，产出后  config 目录下的 json 文件可看到
- 线上运行的时候，模板层面的插件逻辑负责把这些依赖从 json 中分析出来，并返回给浏览器正确的资源信息

所以，从静态编译这块看不出个所以然来。
