### ISSUE TITLE
fis2有支持html里style="background-image: url()资源定位的插件吗

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/fis#729]
多谢
好多页面都写了inline css image url，蛋疼啊

木有的话就得自己写
顺便问下应该写在preprocessor还是postprocessor钩子里？有点拿不准

**Comment by jiajianrong** [comment]
能在编译（process）阶段做吗？
后端java，还有些非jello/fis标准的标签，比如#parse('/widget/common/header.vm')，也需要做资源定位啊

目前jello是不支持#parse标识：（

**Comment by jiajianrong** [comment]
@2betop

**Comment by xiangshouding** [comment]
尽量还是不要内嵌，不然失去了这些工具引入的意义。

不知道其他人是否写过类似的插件。

**Comment by jiajianrong** [comment]
@xiangshouding 

图片路径是后端给出的，没用img的原因是想用background-size:cover/contain，直接可以忽略图片大小
用img的话实现图片居中不好搞啊，用img的话目前只能想到加载后用js切

**Comment by jiajianrong** [comment]
background-size:cover/contain
加
background-position: center center;
可以忽略图片大小，类似http://www.dgtle.com/首页列表里的图片，直接把图片压缩并居中扔到div里

img src不用js的话实现不了啊

**Comment by zhangtao07** [comment]
在首页插件列表中搜索 uri 插件，社区有类似插件支持

**Comment by jiajianrong** [comment]
@zhangtao07 
具体是哪个？搜不到啊

**Comment by zhangtao07** [comment]
https://www.npmjs.com/package/fis-postpackager-extras_uri例如这个

**Comment by jiajianrong** [comment]
@zhangtao07 
感谢

这个仅对img有效吧？看源码是遍历所有img名称取命中的？万一两个img名称相同（或者名字一个包含另一个），但不在同一目录呢？


fis.util.map(ret.src, function(sub, f) {
                    if (sub.indexOf(target) > -1 && f.isImage()) {
                        url = f.getUrl(opt.md5, opt.domain);
                        (url && !setFlag) && (setFlag = true);
                        return true;
                    }
                });

**Comment by zhangtao07** [comment]
这个是社区插件，代码没有细看，你也看到没几行代码就实现了类似功能，你可以参考自己修改下撸个新插件出来~
