### ISSUE TITLE
fis安装后的包能像jdk一样拷到另外一个机器吗

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/fis#730]
内网机器连不上外面，不能npm install啊
多谢

**Comment by xiangshouding** [comment]
你可以找一台相同系统的机器拷贝一份，如果换了系统某些功能会失效，比如 图片压缩、图片合并 等等

**Comment by jiajianrong** [comment]
能问下失效的原理是啥吗？我好想办法workaround
多谢

**Comment by xiangshouding** [comment]
@jiajianrong 图片处理的代码是用 C++ 写的扩展

**Comment by jiajianrong** [comment]
多谢
