### ISSUE TITLE
fis release后执行fis server start还是TODO

### ISSUE THREAD

**Issue by bulldog478** [fex-team/fis#731]
www目录下已经是我自己的工程了，但是执行start server start后弹出的还是todo，这是为什么呢

**Comment by xiangshouding** [comment]
```
fis server clean #清除 www
fis release  #重新 release
```

虽然是你的项目，但入口文件如果不是你的项目也无法跑你的项目啊；

**Comment by bulldog478** [comment]
我清空了回收站就再执行fis server start就好了，额，不知道是不是只有我遇到了这个情况
