### ISSUE TITLE
使用默认的php版本receiver上传

### ISSUE THREAD

**Issue by aibaiejoy** [fex-team/fis#733]
![image](https://cloud.githubusercontent.com/assets/1289921/13589991/3c79e7f6-e517-11e5-881e-1a4202fd2fed.png)

fis.config.merge({
    deploy: {
        remote: {  
            receiver: 'http://xxx.xxx.xxx.xxx/hcy1.1/index.php',  // 接收服务的地址
            from: '/',
            //to: '/usr/local/apache-tomcat-7.0.63/webapps/hello' // 服务器上部署的的路径
            to:'tmp/test'
        }  
    }  
});

fis版本： v1.9.39
node版本：v4.2.2

**Comment by xiangshouding** [comment]
目标目录无权限

查看你的服务器运行账户是否对你的目标目录有写权限
