### ISSUE TITLE
fis3 安装失败

### ISSUE THREAD

**Issue by jiaxw** [fex-team/fis#734]
"Hello, World."
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "fis3"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12

npm ERR! shasum check failed for C:\Users\XUYUAN~1\AppData\Local\Temp\npm-6024-8a1451fc\registry.npmjs.org\images-\images-2.1.11.tgz
npm ERR! Expected: 57d5faa13b71b7fea0f5500d99e81382aa1663be
npm ERR! Actual:   be1d1c0b008eb792585714a572140450da78c1fa
npm ERR! From:     https://registry.npmjs.org/images/-/images-2.1.11.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by xiangshouding** [comment]
npm cache clean

后重试

**Comment by jiaxw** [comment]
重试时候出现下面的error:
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fis3"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

**Comment by xllee** [comment]
具体的报错信息我没看，但是前面我安装fis3用的node_v4.*
换用0.10.26 安装正常。npm版本：1.4.3
