### ISSUE TITLE
head标签引入的js文件，编译后，会被强制在dom加载后引入，但我不想这样，咋解决？

### ISSUE THREAD

**Issue by sailengce** [fex-team/fis#736]
我的HTML页面里，有的js我就需要dom加载前执行，但是编译后被强制弄到最后了，这个怎么办？

**Comment by zhangtao07** [comment]
如果你用的 fisp 等解决方案，直接使用原生 script 标签即可。如果使用FIS 纯前端的资源管理方案，如 pure, [simple 插件](https://github.com/hefangshi/fis-postpackager-simple)有data-fixed属性控制不被移动位置。

**Comment by menghan126** [comment]
<html lang="">
	<link rel="import" href="header.html?__inline">
	<script data-fixed='true' src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
	<body>
		<link rel="import" href="footer.html?__inline">
		<script src="src/js/base.js"></script>
		<script src="src/js/public.js"></script>
	</body>
</html>

这个插件我也安装了，这样写了，但是还是会被弄到下面去。

**Comment by menghan126** [comment]
`<html lang="">
	<link rel="import" href="header.html?__inline">
	<script data-fixed='true' src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
	<body>
		<link rel="import" href="footer.html?__inline">
		<script src="src/js/base.js"></script>
		<script src="src/js/public.js"></script>
	</body>
</html>`
这个插件我也安装了，这样写了，但是还是会被弄到下面去

**Comment by menghan126** [comment]
之前是在header.html文件写的，现在我提出来单独放在HTML文件里，也还是不行，data-position也用了，也不行。

**Comment by menghan126** [comment]
安装完这个插件之后，配置文件需要配置啥么？

**Comment by zhangtao07** [comment]
所有插件都需要配置，如果用了 pure 已经集成了，如果没用将插件配置进去，可以参考 pure 的解决方案[默认配置](https://github.com/fex-team/fis-pure/blob/master/pure.js)
