### ISSUE TITLE
fis2 解析 node_module 目录挂掉了

### ISSUE THREAD

**Issue by atian25** [fex-team/fis#737]
![image](https://cloud.githubusercontent.com/assets/227713/13840736/492b80b4-ec5f-11e5-88b1-5b5609c2c8f1.png)

fis2 这里遇到一个问题, node_module 目录下文件太多的时候, 会挂掉

`fis.config.set('project.exclude', ['node_modules/**', 'output/**', 'dist/**', 'fis-conf.js']);`

这个我之前看过, 只是不构建分析, 但是还是需要 read source,

fis3 里面貌似就解决了.  在 fis2 里面有没有临时解决方法?

**Comment by atian25** [comment]
cc @fouber @2betop @xiangshouding @hefangshi 求救~

**Comment by hefangshi** [comment]
不设置 `project.include`，只设置 `project.exclude` 应该就没问题了。

**Comment by atian25** [comment]
https://github.com/scrat-team/scrat/blob/master/configs/default.js
 没有设置include好像

**Comment by atian25** [comment]
preprocessor.component这个是fis内置的？

scrat只有一个tpl

https://github.com/scrat-team/scrat/blob/master/index.js#L99

**Comment by hefangshi** [comment]
是，是内置的，你可以屏蔽掉他试试看，这个是 fis-components的

**Comment by atian25** [comment]
@hefangshi 干掉后就快了, 有两个问题:

1. 干掉后会输出的 map.json 会缺少什么吗?
2. 这个组件能否允许设置下过滤, node_modules 里面我们不需要分析

**Comment by atian25** [comment]
https://github.com/fex-team/fis-preprocessor-components/blob/master/index.js#L25

应该是这里的递归导致的.

**Comment by hefangshi** [comment]
只要你们没有使用 fis-components，去掉这个插件就不会有影响。

据我所知你们的components目录应该是自己维护的，所以直接去掉没有问题。

**Comment by atian25** [comment]
1.9.37

**Comment by atian25** [comment]
@2betop 是在哪个版本修的?

**Comment by atian25** [comment]
刚试了 `fis@1.9.45` , `fis-preprocessor-components@1.0.19` 还是死了.

**Comment by 2betop** [comment]
死了是估计是项目里面的文件夹太多，直接关闭这个插件吧，没有副作用。

**Comment by atian25** [comment]
关掉这个没问题, 只是这个插件是否考虑优化下, 支持屏蔽掉某些目录, 譬如 node_modules

```
// fis.config.set('modules.preprocessor.js', '');
// fis.config.set('modules.preprocessor.css', '');
// fis.config.set('modules.preprocessor.html', '');
```

**Comment by okoala** [comment]
我把fis.util.find这个方法修改了下，就好了。不然项目中有node_modules还真要被fis components给搞死~囧~

**Comment by atian25** [comment]
你自己修补没用啊,  我是想了解 @2betop 有没有考虑合并到主干去优化

**Comment by atian25** [comment]
好吧, 被坑了.

https://github.com/scrat-team/scrat/blob/master/plugins/preprocessor/swig.js#L10

关闭这个插件后, 这样的写法, 就会有问题, 对应的 dep 没被转换.
如下想 require 的是 ./list/list.js
```javascript
{% script %}
   require('./list');
{% endscript %}
```

cc @fouber @2betop

**Comment by 2betop** [comment]
这中用法，貌似只有 fis3 中才支持的。

**Comment by atian25** [comment]
还没细看源码, 之前云龙写的, 不知道 `fis.compile.extJs` 跟 preprocessor-component 会起什么化学反应 -.-

**Comment by 2betop** [comment]
preprocessor-component 也没有这种用法的支持啊，你是不是记错了啊。

**Comment by atian25** [comment]
@2betop 我写了个最小示例:  https://github.com/atian25/fis-test-preprocessor-component

注释掉前的 map 如下:
```json
{
    "res": {
        "components/list/list.js": {
            "uri": "/public/c/list/list.js",
            "type": "js"
        },
        "components/list/list.tpl": {
            "uri": "views/c/list/list.tpl",
            "type": "tpl",
            "deps": [
                "components/list/list.js"
            ]
        }
    },
    "pkg": {}
}
```

注释后:
```json
{
    "res": {
        "components/list/list.js": {
            "uri": "/public/c/list/list.js",
            "type": "js"
        },
        "components/list/list.tpl": {
            "uri": "views/c/list/list.tpl",
            "type": "tpl",
            "deps": [
                "./list",
                "components/list/list.js"
            ]
        }
    },
    "pkg": {}
}
```

**Comment by atian25** [comment]
应该是这段逻辑: https://github.com/fex-team/fis-preprocessor-components/blob/master/index.js#L60

**Comment by atian25** [comment]
再试验了下, 其实跟 tpl 这块扩展没关系.

假设以下:
```
// index.js
require('./list');

// list.js
console.log('a')
```
如果 `fis.config.set('modules.preprocessor.js', '');` 之后, 编译出来的 index 的 dep 里面就是 `./list` 而不是对应的 id 了.

如果我没理解错, 这个关闭后, 全局的短名都挂了.
