### ISSUE TITLE
fis-parser-node-sass error

### ISSUE THREAD

**Issue by jamesliauw** [fex-team/fis#738]
[ERROR] load plugin [fis-parser-node-sass] error : The `libsass` binding was not found in /usr/local/lib/node_modules/scrat/node_modules/fis-parser-node-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

**Comment by xiangshouding** [comment]
大概就是让你重新装一次的意思

**Comment by zhangtao07** [comment]
建议通过 cnpm 安装，npm下载 aws 包被墙，很容易进入编译导致安装失败。

**Comment by Lutreer** [comment]
怎么解决的  重新安装成功了fis2还是不能用，fis3可以用

**Comment by 2betop** [comment]
难道你是安装在当前项目目录吗？fis2 只支持全局安装。
