### ISSUE TITLE
麻烦帮忙看看这个图片压缩插件为什么不能正常工作

### ISSUE THREAD

**Issue by Julienedies** [fex-team/fis#739]
插件地址：[https://github.com/Julienedies/fis-optimizer-img-min](https://github.com/Julienedies/fis-optimizer-img-min),
插件正常调用，打印日志显示有压缩，但是部署出去的图片还是保持原始大小。

**Comment by xiangshouding** [comment]
这个插件是 @Julienedies 提供的，请到这个项目的 issues 提问题；

**Comment by Julienedies** [comment]
额，囧，@xiangshouding，这个插件就是我写的。插件开发文档没找到与此相关的内容，所以想确定一下插件是否有不符合要求的地方。

**Comment by xiangshouding** [comment]
@Julienedies 哎呀，直接看问题，没对人啊。。抱歉

**Comment by Julienedies** [comment]
哪里，还要麻烦

**Comment by Julienedies** [comment]
@xiangshouding , 好像找到问题了，因为回调是异步的，所以```return content```的时候，content还没有被改变

**Comment by xiangshouding** [comment]
对，不支持
