### ISSUE TITLE
fisp server start 后，在127.0.0.1:8080中访问不到已发布的项目

### ISSUE THREAD

**Issue by wtgzczz** [fex-team/fis#740]
fisp server start 后，在127.0.0.1:8080中访问不到已发布的项目，还是发布之前的index空白页面。
这是什么情况喔

**Comment by zhangtao07** [comment]
没有 release？ fisp server open 打开本地调试服务器目录查看是否有文件，以及是否有配置转发规则，直接访问模板对应的路径试试
