### ISSUE TITLE
编译时下载的文件不会追加MD5后缀

### ISSUE THREAD

**Issue by aj4g** [fex-team/fis#741]
我写了一个插件用于文件下载，作用是在parser阶段解析一个json文件，将json中配置的文件下载到本地：[传送](https://github.com/aj4g/fis-parser-dependencies)

配置文件如下：

```
{
  "bundle": [
    {
      "from": "http://xxx.com/wendor.js",
      "to": "./server/output/assets/scripts/vendor.js",
      "overwrite": "true"
    }
  ]
}
```

vendor.js是公司提供的js库，然后在页面中，直接引用下载的文件位置：
<link rel="stylesheet" href="/assets/scripts/vendor.js">

但是问题来了：
**1. 这个文件名不会被加上MD5后缀。**
**2. 下载是异步的，所以fis的一些特性对vendor.js不起作用。**

@xiangshouding @zhangtao07 @hefangshi 这两个问题（主要是问题1）怎么破？

**Comment by zhangtao07** [comment]
编译过程中最好别去下载东西，建议将下载步骤在 shell 脚本编译前执行，例如使用[fis-component](https://github.com/fis-components)来管理第三方资源，支持github、npm、内部 gitlab等

**Comment by aj4g** [comment]
有没有可能在下载插件里直接给某个文件加MD5？ fis有接口可以调用吗？

**Comment by xiangshouding** [comment]
@aj4g 

只要涉及到网络 io 操作，按照 node 这尿性，肯定是需要异步的。异步了，FIS 里面就不行，FIS 是高度同步化的一个软件。

另外，可能有的时候获取远端的东西去那来编译感觉很 nice 方便的一个功能，但在实践过程中，几乎这种是无法长期弄下去了。

问题大概在一下几个方面：
- 远端默默的改了代码
- 依赖的其中一个组件的依赖发生了变化
- 一些不确定因素，比如依赖源的服务挂了

最终导致一些莫名其妙的问题。

所以我们不管是后端还是前端组件，在项目初期都会做一些版本固话操作。除非你非常信赖的一个服务，比如你自己搭建的。

**Comment by aj4g** [comment]
感谢回答

@xiangshouding 

前端项目千变万化，比如我们使用fis也仅仅使用某些特性，如果完全按照fis标准来做（比如fis-component）确实做不到，下载的资源是内部的，这部分代码不希望被改动所以单独拿出来挂在gitlab上提供下载，每次改动都会经过严格测试，不用担心。

所以如果fis有提供接口对一个文件+MD5，在下载完成后调用一下,对于我们来说应该是最简单的解决方案了。

**Comment by zhangtao07** [comment]
那你在编译前先下载 gitlab 的组件代码就行了
