### ISSUE TITLE
启动fis 服务器报错无法启动

### ISSUE THREAD

**Issue by dawang0123** [fex-team/fis#743]
我的8080端口被占用了
设置端口：fis sever start --port 8899
每次更改端口都出现错误提示：unable to load plugin [fis-command-sever]

如果直接启动fis服务就会报错：unable to load plugin  [fis-command-sever]

node.js npm 和fis都已经安装成功

fis的版本号是v1.9.46

**Comment by 2betop** [comment]
因为你把 server 拼错了
