### ISSUE TITLE
fis3结合requirejs使用时，怎么合并异步加载的js文件

### ISSUE THREAD

**Issue by yux357** [fex-team/fis#745]
使用 fis-postpackager-loader 如果设置includeAsyncs属性，依赖的js文件确实打包了，但是直接输入到页面的script标签中，变成了同步加载，如果不设置includeAsyncs属性，则js文件不会打包。

**Comment by 2betop** [comment]
用这个 https://github.com/fex-team/fis3-packager-deps-pack 去打包，loader 只打包同步依赖，打包本不是他的主要工作。
