### ISSUE TITLE
开启wL过一段时间之后报错

### ISSUE THREAD

**Issue by Capricair** [fex-team/fis#748]
![image](https://cloud.githubusercontent.com/assets/6244446/14346395/98d8d8d8-fce4-11e5-8df6-c118d135fb40.png)
经常遇到这个问题，报错后面就一直是这个错误，编译并不报错，重新运行就好了，wL貌似用WebSocket监听的，是不是因为没有实现心跳包，还有一个问题就是监听的时候，移动文件，改文件名，或某些操作会导致编译报错就死掉了，能不能编译的时候把错误catch掉，然后继续运行，因为开发的时候，语句没打完这种情况太多了，每次崩了又得重新运行很蛋疼

**Comment by nfjBill** [comment]
估计你模块依赖的功能实现了问题

**Comment by Capricair** [comment]
@nfjBill 我不太明白，能说的具体点吗，我开启监听之后只是进行编码，并没有做其他的事情，就会出现这样的情况，如果说是我正在编写的文件有错误导致的，那么文件保持原样重新启动应该还是会报错，但是重新启动就恢复正常了
