### ISSUE TITLE
fis进行远程部署，部分文件上传成功部分上传失败，导致fis进程退出部署失败

### ISSUE THREAD

**Issue by CaroseKYS** [fex-team/fis#757]
在用fis进行远程部署的时候有很多文件已经上传并且被服务器接收存储，但是总会碰到一些文件上传失败，导致进程退出，远程部署失败。配置信息和错误信息如下，求各位道友赐教了。
### 配置信息：

`remote: {
      receiver : 'http://localhost:1337/receiver',
      from : '/static',
      to : 'd:/static'
    }`
### 错误信息：

![image](https://cloud.githubusercontent.com/assets/8399936/15626115/ba401248-24ee-11e6-9e20-efd4b4a98c67.png)

**Comment by zhangtao07** [comment]
一般上传中途报错最直接的方式就是去云端服务器查看错误日志。常见的问题有需要关闭远端防火墙、提高远端服务器文件大小接收限制、查看文件部署文件夹权限等

**Comment by CaroseKYS** [comment]
@zhangtao07 多谢您。问题找到了，应该是中文文件名导致的。但是用fis做optimize的时候遇到大一些的文件就会卡死，怎么破？
