### ISSUE TITLE
html依赖js文件，应该怎么输出到html页面比较好啊？

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/fis#762]
想咨询一下html对js的依赖 在fis里有没有标准的处理流程？没有看到相关的东东

还是插件的编写者自己处理？
多谢

**Comment by jiajianrong** [comment]
补充一下背景哈

我想通过release时是否添加某个参数，动态的给html添加或删除一些js（包括内联js代码和外链js路径）
本来我想通过动态修改html的deps或requires来达到目的，但突然发现貌似fis对这块没有做任何处理

现在我不确定改修改依赖实现目的，还是直接在postpackager里给html添加内容好了

**Comment by hefangshi** [comment]
http://fis.baidu.com/fis3/docs/api/config-props.html#requires

配合media功能使用就可以根据不同的media加载不同的依赖。
