### ISSUE TITLE
fis开启监听，每次修改开发目录下的文件到目标文件的编译过程缓慢，有没有优化办法？

### ISSUE THREAD

**Issue by CaroseKYS** [fex-team/fis#763]
fis执行`fis release -wd dev`命令后进入监听状态，每次修改开发目录下的文件后，总要等10s左右才能将修改的文件发布到运行目录项，使得开发过程不可避免的进入等待，降低了开发速度。请问各位道友，有没有优化该过程的方式？

**Comment by hefangshi** [comment]
尝试使用一下最新的fis3，对这方面的功能有优化。
