### ISSUE TITLE
js中资源定位__uri中的值不能是变量么

### ISSUE THREAD

**Issue by xuecrown** [fex-team/fis#764]
比如我这样用imgs[i].src = __uri(imgs[i].getAttribute('data-img'))  控制台就会报Uncaught __uri is not defined的错

**Comment by 2betop** [comment]
只能支持字面量

**Comment by xiangshouding** [comment]
@xuecrown 

其实想想就是不支持的，__uri 是个编译函数，当 fis 处理这个文件时，它只是一个文本文件而已，跟其他的 .txt 等文本文件没有啥区别。这时候只是做一些替换操作，并不能做 js 文件执行时可以拿到上下文赋值那么可心。

但对于你的这个问题，你完全不需要困苦于 __uri  是否是一个编译时函数或者运行时函数。因为只要你的 data-img 是一个完整的可访问的链接即可。

你现在的问题是如何让 data-img 也能支持 FIS 的资源定位，来给你一个完整的可访问的线上 url。

由于 fis 是一套整体的解决方案，并不是一个替换工具，其自定义的属性支持在某个范围内，现在支持的自定义属性有 `data-src`，你可以尝试换成 `data-src` 来解决问题。
