### ISSUE TITLE
这种json格式的定义的png,jpeg,swf等资源，怎么添加md5版本控制

### ISSUE THREAD

**Issue by zouhuigang** [fex-team/fis#765]
{
	"groups":[
		{
			"keys":"pin-inactive_png,point_png,power2_png,power3_png,power5_png,querstionbg_png,question_png,share_png,wrong_png,back_png,bubble_png,close_png,correct_png,dot_png,finished_png,map-js_png,pin-active_png,button_down_png,button_up_png,start-btn_png,promotion-btn_png,restart-btn_png,failed-bg_png,sound_stop_png,sound_png,Music_mp3,button_orange_up_png,colse_w_png,guideMC_json,guideMC_png,avatar-bg@1125_png,bubble@1125_png,logo@1125_png,qrcode@1125_png,linec_png,share-btn_png,iknow-btn_png",
			"name":"ResGroupwelcome"
		},
		{
			"keys":"buttonclick_mp3,right_mp3,type_word_mp3,wrong_mp3",
			"name":"ResGroupSound"
		},
		{
			"keys":"bg_png,loadingUI_progresBar_1_png,loadingUI_progresBar_2_png",
			"name":"preload"
		}
	],
	"resources":[
		{
			"name":"pin-inactive_png",
			"type":"image",
			"url":"assets/preload/pin-inactive.png"
		},
		{
			"name":"point_png",
			"type":"image",
			"url":"assets/preload/point.png"
		},
		{
			"name":"power2_png",
			"type":"image",
			"url":"assets/preload/power2.png"
		},
		{
			"name":"power3_png",
			"type":"image",
			"url":"assets/preload/power3.png"
		},
		{
			"name":"power5_png",
			"type":"image",
			"url":"assets/preload/power5.png"
		},
		{
			"name":"querstionbg_png",
			"type":"image",
			"url":"assets/preload/querstionbg.png"
		},
		{
			"name":"question_png",
			"type":"image",
			"url":"assets/preload/question.png"
		},
		{
			"name":"share_png",
			"type":"image",
			"url":"assets/preload/share.png"
		},
		{
			"name":"wrong_png",
			"type":"image",
			"url":"assets/preload/wrong.png"
		},
		{
			"name":"back_png",
			"type":"image",
			"url":"assets/preload/back.png"
		},
		{
			"name":"bubble_png",
			"type":"image",
			"url":"assets/preload/bubble.png"
		},
		{
			"name":"close_png",
			"type":"image",
			"url":"assets/preload/close.png"
		},
		{
			"name":"correct_png",
			"type":"image",
			"url":"assets/preload/correct.png"
		},
		{
			"name":"dot_png",
			"type":"image",
			"url":"assets/preload/dot.png"
		},
		{
			"name":"finished_png",
			"type":"image",
			"url":"assets/preload/finished.png"
		},
		{
			"name":"map-js_png",
			"type":"image",
			"url":"assets/preload/map-js.png"
		},
		{
			"name":"pin-active_png",
			"type":"image",
			"url":"assets/preload/pin-active.png"
		},
		{
			"name":"button_down_png",
			"type":"image",
			"url":"assets/compoent/Button/button_down.png"
		},
		{
			"name":"button_up_png",
			"type":"image",
			"url":"assets/compoent/Button/button_up.png"
		},
		{
			"name":"start-btn_png",
			"type":"image",
			"url":"assets/preload/start-btn.png"
		},
		{
			"name":"promotion-btn_png",
			"type":"image",
			"url":"assets/preload/promotion-btn.png"
		},
		{
			"name":"restart-btn_png",
			"type":"image",
			"url":"assets/preload/restart-btn.png"
		},
		{
			"name":"failed-bg_png",
			"type":"image",
			"url":"assets/preload/failed-bg.png"
		},
		{
			"name":"sound_stop_png",
			"type":"image",
			"url":"assets/preload/sound_stop.png"
		},
		{
			"name":"sound_png",
			"type":"image",
			"url":"assets/preload/sound.png"
		},
		{
			"name":"buttonclick_mp3",
			"type":"sound",
			"url":"assets/sound/buttonclick.mp3"
		},
		{
			"name":"Music_mp3",
			"type":"sound",
			"url":"assets/sound/Music.mp3"
		},
		{
			"name":"right_mp3",
			"type":"sound",
			"url":"assets/sound/right.mp3"
		},
		{
			"name":"type_word_mp3",
			"type":"sound",
			"url":"assets/sound/type_word.mp3"
		},
		{
			"name":"wrong_mp3",
			"type":"sound",
			"url":"assets/sound/wrong.mp3"
		},
		{
			"name":"button_orange_up_png",
			"type":"image",
			"url":"assets/compoent/Button/button_orange_up.png"
		},
		{
			"name":"colse_w_png",
			"type":"image",
			"url":"assets/preload/colse_w.png"
		},
		{
			"name":"guideMC_json",
			"type":"json",
			"url":"assets/guide/guideMC.json"
		},
		{
			"name":"guideMC_png",
			"type":"image",
			"url":"assets/guide/guideMC.png"
		},
		{
			"name":"bg_png",
			"type":"image",
			"url":"assets/guide/bg.png"
		},
		{
			"name":"loadingUI_progresBar_1_png",
			"type":"image",
			"url":"assets/guide/loadingUI_progresBar_1.png"
		},
		{
			"name":"loadingUI_progresBar_2_png",
			"type":"image",
			"url":"assets/guide/loadingUI_progresBar_2.png"
		},
		{
			"name":"avatar-bg@1125_png",
			"type":"image",
			"url":"assets/share/avatar-bg@1125.png"
		},
		{
			"name":"bubble@1125_png",
			"type":"image",
			"url":"assets/share/bubble@1125.png"
		},
		{
			"name":"logo@1125_png",
			"type":"image",
			"url":"assets/share/logo@1125.png"
		},
		{
			"name":"qrcode@1125_png",
			"type":"image",
			"url":"assets/share/qrcode@1125.png"
		},
		{
			"name":"linec_png",
			"type":"image",
			"url":"assets/preload/linec.png"
		},
		{
			"name":"share-btn_png",
			"type":"image",
			"url":"assets/preload/share-btn.png"
		},
		{
			"name":"iknow-btn_png",
			"type":"image",
			"url":"assets/preload/iknow-btn.png"
		}
	]
}

**Comment by liuqingqian** [comment]
fis.match('*.{css,js,png,jpg,jpeg,gif,ico}', {
    useHash: true
});

**Comment by hefangshi** [comment]
不支持这种定义形式，只能使用js+__uri()函数定义
