### ISSUE TITLE
deploy阶段, file.url 丢失

### ISSUE THREAD

**Issue by maxming2333** [fex-team/fis#770]
![image](https://cloud.githubusercontent.com/assets/8816730/17355756/6f1bd826-5985-11e6-8d70-d003a669ae8b.png)

**输出：**

![image](https://cloud.githubusercontent.com/assets/8816730/17355790/b70fded4-5985-11e6-8459-975a3ec3c23f.png)

可以看到 deloy 阶段， `file.getUrl()` 获取不到资源 url

**Comment by maxming2333** [comment]
file.extras 字段 获取正确，只有 file.url 获取不到

**Comment by maxming2333** [comment]
![image](https://cloud.githubusercontent.com/assets/8816730/17355846/2afc4684-5986-11e6-9c7e-553dc5393c5b.png)

对 images 文件，加了以下属性

**Comment by maxming2333** [comment]
难道我工程哪里代码写错了？

**Comment by 2betop** [comment]
用最新 fis3 试试？

**Comment by maxming2333** [comment]
现在可以了

[https://github.com/fex-team/fis3-command-release/commit/345cc445e5532125fd4ac593efbc1f5ff2da2aab](https://github.com/fex-team/fis3-command-release/commit/345cc445e5532125fd4ac593efbc1f5ff2da2aab)

修复后，就可以了
