### ISSUE TITLE
fis3 运行-WL以后 无法自动刷新，网页没有看到livereload.js,加注释也没用

### ISSUE THREAD

**Issue by changbibi** [fex-team/fis#779]
为什么我release -wl 后修改文件无法及时刷新 ，因为有虚拟机所以加了ip 配置但是还是无效 查看网页效果发现没有livereload， 在页面body中加了还是没有用，求解 求解

**Comment by xiangshouding** [comment]
`-wL`

**Comment by changbibi** [comment]
谢谢，我大小写 弄错了
