### ISSUE TITLE
minimatch@2.0.4:Please update to minimatch 3.0.2  or higher to avoid a RegExp Dos issue

### ISSUE THREAD

**Issue by chaihongjun** [fex-team/fis#781]
npm warn deprecated minimatch@2.0.4:Please update to minimatch 3.0.2  or higher to avoid a RegExp Dos issue

这样之后 npm install -g minimatch  依然提示

**Comment by yuluhuang** [comment]
npm install -g npm
npm install -g minimatch
Node 版本要求 0.8.x，0.10.x, 0.12.x，4.x，6.x，不在此列表中的版本不予支持。最新版本 node 支持会第一时间跟进，支持后更新支持列表。
