### ISSUE TITLE
我的电脑是xp系统 安装的是fis1.8版本，安装后执行命令错误，请问各位大侠怎么回事？该怎样解决？

### ISSUE THREAD

**Issue by menglei0602** [fex-team/fis#784]
这条命令执行正确：
C:\Documents and Settings\Administrator>fis -v 

这条命令执行错误：
C:\Documents and Settings\Administrator>ls
显示错误信息为：
'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by yangfanzz** [comment]
立即更换你的xp系统电脑

**Comment by menglei0602** [comment]
为啥要更换xp系统啊

**Comment by xiangshouding** [comment]
ls 。。是 *nix 的命令。
