### ISSUE TITLE
报错“parser.less: Cannot read property 'contents' of undefined ”

### ISSUE THREAD

**Issue by yuyuFish** [fex-team/fis#785]
![qq 20161017155340](https://cloud.githubusercontent.com/assets/16677733/19429360/e5296a38-9481-11e6-9d1d-273c8689dbdb.jpg)

安装了“fis3-parser-less”的最新版本2.0+。。电脑win10系统。。其他win7电脑跑都没有报错可以生成css文件。但是换成win10电脑就报错“parser.less: Cannot read property 'contents' of undefined ”。。。谁有遇到一样的问题吗。请问有知道如何解决吗？

**Comment by xiangshouding** [comment]
fis3-parser-less 貌似是个社区插件，貌似有问题。请用 fis-parser-less

**Comment by yuyuFish** [comment]
谢谢，用你说的解决问题了。非常感谢~
