### ISSUE TITLE
使用deploy上传项目报错

### ISSUE THREAD

**Issue by liaowp** [fex-team/fis#786]
配置：
 deploy: {
        remote: {  
            receiver: 'http://10.19.1.170',  // 接收服务的地址
            from: '/',
            to: '/temp' // 服务器上部署的的路径
        }  
    } 
执行命令fis release -d remote
[ERROR] invalid deploy destination options [remote]
有没有懂的人告诉一下，谢谢

**Comment by zhuyingda** [comment]
看下你执行fis release的当前目录，是否与fis-conf中设置的不符.
