### ISSUE TITLE
对图片进行压缩的路径问题

### ISSUE THREAD

**Issue by KarloyWu** [fex-team/fis#787]
![image](https://cloud.githubusercontent.com/assets/23184875/19881821/e31edb38-a043-11e6-9285-1d70f6378d56.png)
![image](https://cloud.githubusercontent.com/assets/23184875/19881831/fb6a9150-a043-11e6-8a45-dc58b78d3c75.png)
![image](https://cloud.githubusercontent.com/assets/23184875/19881835/05f695b0-a044-11e6-8c5f-cdbe3aba03be.png)
配置文件在根目录下，跟style是同级的。
路径那样设置对css、js文件都是有效的，就对png失效了。
想请问一下，这个路径要怎么设置呢~

**Comment by xiangshouding** [comment]
已经显示的很明确了，某个文件不是图片。
