### ISSUE TITLE
node 6.0.0 还是会有csssprite的warning

### ISSUE THREAD

**Issue by shellphon** [fex-team/fis#789]
https://github.com/fex-team/fis/blob/master/CHANGELOG.md#1100--wed-may-11-2016

changelog写着支持6.x， 我试了6.0.0和7.1.0 都有warning

看fis-spriter-csssprites 目录，github上好像也是 2years ago了。

是现在还不支持么？

**Comment by xiangshouding** [comment]
看你什么机器，如果是 linux 内核太老不支持，内核太新估计也会不支持。
如果是 windows 6.x 是支持的

**Comment by shellphon** [comment]
清了遍fis-tmp 确实可以了6.0.0，  我的是win7 32位。

不过7.1.0 应该是不支持吧，node-pngcrush和csssprites
