### ISSUE TITLE
MD5文件指纹以及文件打包的问题

### ISSUE THREAD

**Issue by 6best** [fex-team/fis#793]
```
fis.match('::package', {
  packager: fis.plugin('map', {
    '/dist/js/script.min.js': [
      '/assets/js/a.js',
      '/assets/js/b.js',
      '/assets/js/c.js',
      '/assets/js/**.js'
    ]
  })
})
```
页面加载
```
<script src="dist/js/script.min.js" ></script>
```

release 之后会生成 dist/js/script.min_230b90c.js

但也页面上引用的js 没有加md5，这么怎么破？
另外因为我是打包成一个文件了，所以那些 a、b、c、d之类的js我是不需要生成到发布目录的，该如何过滤？ 求指点！谢谢～

**Comment by zhangtao07** [comment]
页面引用应该是开发目录中的文件，而不是发布后的文件，这样对开发不友好。你如果引用了/dist/js/script.min.js中的文件，结合前端loader 插件或不同的后端解决方案，会自动替换成打包后的文件路径

**Comment by 6best** [comment]
@zhangtao07  谢谢～
我改成用loader了，然后我写了个shell脚本来发布和删除那些不要的a,b,c,d之类的不要的文件，问题解决了
