### ISSUE TITLE
fis3不能监听文件修改了，报错

### ISSUE THREAD

**Issue by icemanjin** [fex-team/fis#794]
fis3 release -wL

 [INFO] Currently running fis3 (/usr/local/lib/node_modules/fis3/)

 Ω  33ms
/usr/local/lib/node_modules/fis3/node_modules/.0.2.1@websocket.io-spec/lib/socket.js:49
Socket.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/fis3/node_modules/.0.2.1@websocket.io-spec/lib/socket.js:49:42)

**Comment by jokechat** [comment]
同样的问题,似乎是node 7.x的不支持吧

**Comment by xiangshouding** [comment]
安装最新版本。
