### ISSUE TITLE
用fis打包过程中发现，js里包含了一些html代码字符串，这些字符串里的图片路径没有hash

### ISSUE THREAD

**Issue by RogerHuangZB** [fex-team/fis#796]
用fis打包过程中发现，jquery替换img标签src的方法引用的图片路径是字符串，
这些字符串里的图片路径没有hash，但是实际图片名已经hash了，导致js找不到图片

**$('#logo’).attr('src','./images/logo.png');**

查阅了文档，官方的js里文件路径是用 var img = __uri('images/logo.gif');这个方式来用的；
但是这样开发的时候怎么办？

我应用fis的场景是：
1.多人一起开发，完成后提交SVN；
2.将svn上的HTML\JS\CSS\PNG等文件用fis进行统一压缩Hash打包；
3.发布。

开发的时候每个人都得用fis？

**Comment by xiangshouding** [comment]
开发期间引入编译工具已经是前端研发的标配，不要再感觉麻烦而不去接受当下业内开发模式了。

所以，需要每一个人都用 fis

**Comment by guoweiTang** [comment]
html字符串中的图片地址单拿出来进行__uri函数调用
