### ISSUE TITLE
fis3安装失败

### ISSUE THREAD

**Issue by yvtang** [fex-team/fis#797]
C:\Users\DON>node -v
v6.10.2

C:\Users\DON>npm -v
3.10.10

C:\Users\DON>npm install -g fis3
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated ignore@2.2.7: several bugs fixed in v3.2.1
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "fis3"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\DON\AppData\Local\Temp\npm-296-4b82ca4
b\registry.npmjs.org\node-pngcrush\-\node-pngcrush-0.3.7.tgz
npm ERR! Expected: 07b462bf2423452603d43eea465595f1db20f217
npm ERR! Actual:   132d5f0a7949460318ff138bb16f581fe923081d
npm ERR! From:     https://registry.npmjs.org/node-pngcrush/-/node-pngcrush-0.3.
7.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DON\npm-debug.log

**Comment by g8up** [comment]
推荐是用`nrm`切换一下 npm 的 registry

**Comment by xiangshouding** [comment]
请参考 #565 看看。
