### ISSUE TITLE
内置的fis-optimizer-png-compressor压缩png图大小没有变化

### ISSUE THREAD

**Issue by yjqphp** [fex-team/fis#803]
内置的fis-optimizer-png-compressor

配置代码如下：

`fis.match('*.png', {
  // fis-optimizer-png-compressor 插件进行压缩，已内置
  optimizer: fis.plugin('png-compressor')
});`

**Comment by xiangshouding** [comment]
请到 fis3 仓库下提 fis3 的问题，thx。
