### ISSUE TITLE
<img src="<%=staticDomain%>/stc/bt/a01/images/service.png" /> 这种情况如何构建 <%=staticDomain%> 不变，stc是独立的目录

### ISSUE THREAD

**Issue by shean023** [fex-team/fis#805]
<--img src="<%=staticDomain%>/stc/bt/a01/images/service.png" /--> 这种情况如何构建 ？
构建要求：
1）仅构建 <%=staticDomain%>  开头的静态资源，其它不构建；
2）需要给静态资源加上MD5指纹；

fis.match：  selector  冒似不支持 <> 符号的转义，构建 后<>符号变为  - - 符号，请问什么好的方法或插件来编译这种案例，谢谢！

**Comment by shean023** [comment]
查找说明需要将<%=staticDomain%>/去掉，直接STC相对路径，然后进行构建的时候再增加域名
 <%=staticDomain%>  Domain

不知道是否有其它更好的方法，如果有其它更好的方法请留言，谢谢！

**Comment by xiangshouding** [comment]
请参考 domain 功能。
