### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by begins24** [fex-team/fis#806]
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! angular2-webpack-starter@5.4.1 build:prod: `npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@5.4.1 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-03T10_11_30_992Z-debug.log

**Comment by xiangshouding** [comment]
我就想问，这个跟 fis  有什么关系？
