### ISSUE TITLE
FIS3安装不了

### ISSUE THREAD

**Issue by HoneyJoanna** [fex-team/fis#807]
![fis](https://user-images.githubusercontent.com/19523820/29509418-cdc8c8ce-868a-11e7-8b5b-67e6b74f6127.jpg)

node安装好了,
执行 node -v 后显示 v6.11.2 
执行 npm -v 后显示 3.10.10
npm install -g fis3之后，一直卡在这里不动了，图片如上所示

**Comment by xiangshouding** [comment]
@HoneyJoanna 多等会儿，或者换个国内的源
