### ISSUE TITLE
能不能加入前端路由的功能

### ISSUE THREAD

**Issue by lancer07** [fex-team/fis#808]
能不能加入前端路由的功能

**Comment by xiangshouding** [comment]
前端路由不是应该业务方自己处理的么，你具体需要什么功能，说一下？

**Comment by lancer07** [comment]
我觉得fis 应该还能帮忙做些更强大的事情，比如构建spa的单页应用之类的。

**Comment by xiangshouding** [comment]
@lancer07 构建单页的本身就能构建啊，没遇到什么大问题。
