### ISSUE TITLE
请问：我在fis3 release -wL 时候怎么报出这样信息（(node:8096) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.）

### ISSUE THREAD

**Issue by SHUAIBEST** [fex-team/fis#810]
fis3 的版本3.4.36，我对一个test项目，执行fis3 release -wL 时候，出现“(node:8096) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.”，是怎么回事？

![qq 20171027165211](https://user-images.githubusercontent.com/16318650/32095906-5d87f422-bb37-11e7-8e99-e761eb3624df.jpg)

**Comment by xiangshouding** [comment]
首先，这个问题从字面来看是说用到的某些接口在当前 node 版本下过时了。
其次，我感觉遇到此类问题查 Google 会更快
再次，这个 warn 不影响使用

**Comment by SHUAIBEST** [comment]
那是否对fis3做一下升级呢（建议）
没搜索出来解决方法。
这确实不影响使用。
